import type { RecipeSource } from "./recipe-types";

export const MESA: RecipeSource[] = [
  {
    slug: "huevos-rancheros",
    name: "Huevos rancheros",
    nameLocal: "Huevos rancheros",
    country: "México",
    city: "Ciudad de México",
    regionId: "latam",
    flavors: ["picante", "umami", "citrico"],
    profile: { picante: 6, umami: 6, acido: 5, dulce: 2, grasa: 6, aroma: 6 },
    timeMin: 25,
    servings: 2,
    difficulty: "fácil",
    moods: ["fiesta", "ligero"],
    ingredients: [
      { item: "Huevos", amount: "4", key: "huevo" },
      { item: "Tortillas de maíz", amount: "4", key: "maiz" },
      { item: "Salsa ranchera de tomate y chile", amount: "2 tazas", key: "tomate" },
      { item: "Aguacate", amount: "1", key: "aguacate" },
      { item: "Queso fresco", amount: "80 g", key: "queso" },
      { item: "Cilantro y lima", amount: "al gusto", key: "cilantro" },
    ],
    steps: [
      "Sofríe cebolla, tomate y chile hasta una salsa espesa. Sal y un toque de comino.",
      "Calienta las tortillas en comal. Fríe los huevos: clara cuajada, yema blanda.",
      "Tortilla, huevo, salsa generosa. Aguacate, queso, cilantro, lima.",
      "Se come de inmediato, con cuchara y tortilla extra para recoger.",
    ],
    story: "El rancho entra a la ciudad en un plato: huevo, maíz y chile. El desayuno mexicano no pide permiso.",
    tip: "La yema tiene que correr sobre la salsa. Si se cuaja del todo, el plato pierde el acuerdo.",
    image: "/dishes/huevos-rancheros.jpg",
    tags: ["desayuno", "huevo", "maíz", "cdmx"],
  },
  {
    slug: "chilaquiles-verdes",
    name: "Chilaquiles verdes",
    nameLocal: "Chilaquiles verdes",
    country: "México",
    city: "Ciudad de México",
    regionId: "latam",
    flavors: ["picante", "citrico", "cremoso"],
    profile: { picante: 6, umami: 5, acido: 6, dulce: 2, grasa: 6, aroma: 6 },
    timeMin: 30,
    servings: 4,
    difficulty: "fácil",
    moods: ["consuelo", "fiesta"],
    ingredients: [
      { item: "Totopos o tortillas fritas", amount: "400 g", key: "maiz" },
      { item: "Tomatillo y chile serrano", amount: "500 g", key: "tomate" },
      { item: "Crema y queso fresco", amount: "al gusto", key: "leche" },
      { item: "Huevos", amount: "4", key: "huevo" },
      { item: "Cebolla y cilantro", amount: "al gusto", key: "cebolla" },
      { item: "Pollo deshebrado (opcional)", amount: "200 g", key: "pollo" },
    ],
    steps: [
      "Asa tomatillo, chile y ajo. Licúa con cilantro y sal: salsa verde.",
      "Hierve la salsa 8 min. Suma los totopos y revuelve apenas: que queden con cuerpo.",
      "Huevo frito o estrellado encima. Crema, queso, cebolla, cilantro.",
      "El punto es el crujiente que se rinde, no el totopo sopa.",
    ],
    story: "La resaca y el domingo se entienden en verde. Los chilaquiles son el maíz que volvió a nacer en salsa.",
    tip: "No dejes los totopos nadando. Diez segundos en la salsa, a la mesa.",
    image: "/dishes/chilaquiles-verdes.jpg",
    tags: ["desayuno", "maíz", "salsa", "cdmx"],
  },
  {
    slug: "changua",
    name: "Changua",
    nameLocal: "Changua",
    country: "Colombia",
    city: "Bogotá",
    regionId: "latam",
    flavors: ["cremoso", "herbal", "umami"],
    profile: { picante: 0, umami: 4, acido: 1, dulce: 2, grasa: 5, aroma: 4 },
    timeMin: 20,
    servings: 2,
    difficulty: "fácil",
    moods: ["consuelo", "ligero"],
    ingredients: [
      { item: "Leche", amount: "500 ml", key: "leche" },
      { item: "Agua", amount: "250 ml", key: "agua" },
      { item: "Huevos", amount: "2", key: "huevo" },
      { item: "Cebolla larga y cilantro", amount: "un manojo", key: "cebolla" },
      { item: "Calado o pan tostado", amount: "2", key: "trigo" },
      { item: "Sal", amount: "al gusto", key: "sal" },
    ],
    steps: [
      "Hierve leche y agua con sal y cebolla larga picada. No dejes que se desborde.",
      "Rompe los huevos en la olla, uno por persona. Tapa 3 minutos: clara cuajada, yema blanda.",
      "Cilantro fresco al apagar. Calado tostado para mojar.",
      "Se come con cuchara, de pie o en cama. Es el altiplano en un plato hondo.",
    ],
    story: "En Bogotá el frío se responde con leche, huevo y cilantro. La changua no es sopa: es manta.",
    tip: "El huevo no se revuelve. Se pocha en la leche. Si se deshace, ya no es changua.",
    image: "/dishes/changua.jpg",
    tags: ["desayuno", "bogota", "leche", "huevo"],
  },
  {
    slug: "kaya-toast",
    name: "Kaya toast",
    nameLocal: "Kaya toast",
    country: "Singapur",
    city: "Singapur",
    regionId: "asia-sur",
    flavors: ["dulce", "cremoso", "umami"],
    profile: { picante: 0, umami: 4, acido: 1, dulce: 6, grasa: 6, aroma: 5 },
    timeMin: 20,
    servings: 2,
    difficulty: "fácil",
    moods: ["ligero", "consuelo"],
    ingredients: [
      { item: "Pan de molde", amount: "4 rebanadas", key: "trigo" },
      { item: "Kaya (mermelada de coco y pandano)", amount: "6 cdas", key: "coco" },
      { item: "Mantequilla fría", amount: "40 g", key: "leche" },
      { item: "Huevos", amount: "2", key: "huevo" },
      { item: "Salsa de soya oscura", amount: "1 cda", key: "soya" },
      { item: "Pimienta blanca", amount: "una pizca", key: "pimienta" },
    ],
    steps: [
      "Tuesta el pan hasta que cruja. Unta kaya, pon una losa de mantequilla fría, cierra.",
      "Huevos a 6½ min. Pela con cuidado: la yema debe correr.",
      "Soya oscura y pimienta blanca sobre el huevo. Corta el tostada en tiras.",
      "Se moja el pan en el huevo. El kopitiam entero cabe en ese gesto.",
    ],
    story: "Desayuno de Hainan en Singapur: coco, pandano y yema. El día empieza dulce y salado a la vez.",
    tip: "La mantequilla tiene que estar fría. Si se derrite antes de morder, perdiste el contraste.",
    image: "/dishes/kaya-toast.jpg",
    tags: ["desayuno", "pan", "coco", "kopitiam"],
  },
  {
    slug: "ful-medames",
    name: "Ful medames",
    nameLocal: "فول مدمس",
    country: "Egipto",
    city: "El Cairo",
    regionId: "africa",
    flavors: ["umami", "citrico", "herbal"],
    profile: { picante: 2, umami: 7, acido: 5, dulce: 2, grasa: 5, aroma: 6 },
    timeMin: 40,
    servings: 4,
    difficulty: "fácil",
    moods: ["consuelo", "ligero"],
    ingredients: [
      { item: "Habas o ful", amount: "500 g", key: "frijol" },
      { item: "Ajo", amount: "3 dientes", key: "ajo" },
      { item: "Comino", amount: "1 cdita", key: "comino" },
      { item: "Limón", amount: "2", key: "limon" },
      { item: "Aceite de oliva", amount: "4 cdas", key: "aceite" },
      { item: "Tomate, perejil y pan pita", amount: "para servir", key: "tomate" },
    ],
    steps: [
      "Cocina las habas hasta que se deshagan un poco. Reserva caldo.",
      "Machaca ajo, comino y sal. Suma a las habas con limón y aceite.",
      "Deja un poco enteras, un poco puré. Aceite en hilo.",
      "Tomate, perejil, huevo duro si quieres. Pan pita caliente. El Cairo de mañana.",
    ],
    story: "El ful es el desayuno del Nilo: haba, ajo y limón. Se come en la calle antes de que el sol pique.",
    tip: "El comino va crudo, al final. Si se cocina de más, amarga el plato.",
    image: "/dishes/ful-medames.jpg",
    tags: ["desayuno", "habas", "cairo", "calle"],
  },
  {
    slug: "menemen",
    name: "Menemen",
    nameLocal: "Menemen",
    country: "Turquía",
    city: "Esmirna",
    regionId: "medio-oriente",
    flavors: ["umami", "herbal", "picante"],
    profile: { picante: 3, umami: 6, acido: 4, dulce: 3, grasa: 6, aroma: 6 },
    timeMin: 20,
    servings: 2,
    difficulty: "fácil",
    moods: ["consuelo", "ligero"],
    ingredients: [
      { item: "Huevos", amount: "4", key: "huevo" },
      { item: "Tomates maduros", amount: "3", key: "tomate" },
      { item: "Pimiento verde", amount: "2", key: "tomate" },
      { item: "Cebolla (opcional)", amount: "1/2", key: "cebolla" },
      { item: "Mantequilla o aceite", amount: "2 cdas", key: "leche" },
      { item: "Queso blanco y pan", amount: "para servir", key: "queso" },
    ],
    steps: [
      "Sofríe pimiento (y cebolla si la usas) en mantequilla hasta que se rinda.",
      "Tomate picado. Cocina hasta salsa, no agua. Sal, pimentón.",
      "Huevos. Revuelve apenas: cuajado cremoso, no revuelto seco.",
      "Queso, pan, té. Se come de la sartén, en el centro de la mesa.",
    ],
    story: "En Esmirna el desayuno es tomate y huevo en una sola sartén. El menemen no se sirve: se comparte.",
    tip: "Apaga el fuego cuando aún brille. El calor residual termina el huevo.",
    image: "/dishes/menemen.jpg",
    tags: ["desayuno", "huevo", "tomate", "turquia"],
  },
  {
    slug: "tiramisu",
    name: "Tiramisú",
    nameLocal: "Tiramisù",
    country: "Italia",
    city: "Treviso",
    regionId: "mediterraneo",
    flavors: ["dulce", "cremoso", "ahumado"],
    profile: { picante: 0, umami: 3, acido: 2, dulce: 7, grasa: 7, aroma: 8 },
    timeMin: 40,
    servings: 6,
    difficulty: "media",
    moods: ["impresionar", "consuelo"],
    ingredients: [
      { item: "Mascarpone", amount: "500 g", key: "leche" },
      { item: "Huevos", amount: "4", key: "huevo" },
      { item: "Café espresso", amount: "300 ml", key: "cafe" },
      { item: "Bizcochos de soletilla", amount: "300 g", key: "trigo" },
      { item: "Cacao en polvo", amount: "3 cdas", key: "chocolate" },
      { item: "Azúcar", amount: "80 g", key: "azucar" },
    ],
    steps: [
      "Separa huevos. Batir yemas con azúcar hasta cinta. Incorpora mascarpone frío.",
      "Claros a nieve firme. Envuelve con paciencia: aire, no sopa.",
      "Moja soletillas un segundo en café. Capa, crema, capa, crema.",
      "Nevera 4 horas. Cacao al servir. El tiramisú se gana esperando.",
    ],
    story: "Veneto: café, yema y mascarpone. El nombre promete levantarte; el postre te sienta.",
    tip: "El bizcocho se moja, no se ahoga. Un segundo. Si chorrea, la crema se rinde.",
    image: "/dishes/tiramisu.jpg",
    tags: ["postre", "cafe", "italia", "crema"],
  },
  {
    slug: "creme-brulee",
    name: "Crème brûlée",
    nameLocal: "Crème brûlée",
    country: "Francia",
    city: "París",
    regionId: "europa",
    flavors: ["dulce", "cremoso"],
    profile: { picante: 0, umami: 2, acido: 1, dulce: 7, grasa: 8, aroma: 6 },
    timeMin: 60,
    servings: 4,
    difficulty: "media",
    moods: ["impresionar", "consuelo"],
    ingredients: [
      { item: "Nata para montar", amount: "500 ml", key: "leche" },
      { item: "Yemas", amount: "5", key: "huevo" },
      { item: "Azúcar", amount: "80 g + extra para quemar", key: "azucar" },
      { item: "Vainilla", amount: "1 rama", key: "vainilla" },
    ],
    steps: [
      "Calienta nata con vainilla. Infusiona 10 min. Cuela.",
      "Yemas y azúcar apenas mezcladas. Nata tibia, poco a poco.",
      "Ramequines al baño maría, horno 150 °C 35 min: el centro tiembla.",
      "Frío total. Azúcar en capa fina, soplete hasta cristal. Se rompe con la cuchara.",
    ],
    story: "La crema espera bajo un techo de azúcar quemado. Francia enseña que el postre también tiene corteza.",
    tip: "El centro debe temblar como gelatina. Si está firme en el horno, ya está pasado.",
    image: "/dishes/creme-brulee.jpg",
    tags: ["postre", "crema", "vainilla", "francia"],
  },
  {
    slug: "tres-leches",
    name: "Tres leches",
    nameLocal: "Pastel de tres leches",
    country: "Colombia",
    city: "Barranquilla",
    regionId: "latam",
    flavors: ["dulce", "cremoso"],
    profile: { picante: 0, umami: 2, acido: 1, dulce: 8, grasa: 6, aroma: 4 },
    timeMin: 70,
    servings: 8,
    difficulty: "fácil",
    moods: ["fiesta", "consuelo"],
    ingredients: [
      { item: "Huevos", amount: "5", key: "huevo" },
      { item: "Harina", amount: "150 g", key: "trigo" },
      { item: "Leche evaporada, condensada y entera", amount: "1 lata + 1 lata + 200 ml", key: "leche" },
      { item: "Azúcar", amount: "150 g", key: "azucar" },
      { item: "Crema para batir", amount: "250 ml", key: "leche" },
      { item: "Canela", amount: "al gusto", key: "canela" },
    ],
    steps: [
      "Bizcocho de huevo: yemas con azúcar, harina, claros a nieve. Horno 180 °C 25 min.",
      "Enfría. Pica con tenedor. Mezcla las tres leches y empapa sin prisa.",
      "Nevera 4 horas mínimo. El bizcocho debe beberse entero.",
      "Crema batida, canela. Se corta frío. El cuchillo sale lechoso.",
    ],
    story: "Tres leches, un solo pastel. En el Caribe el postre no se seca: se rinde al azúcar.",
    tip: "Empapa en dos tandas. Si echas todo de golpe, el centro nada y el borde se queda seco.",
    image: "/dishes/tres-leches.jpg",
    tags: ["postre", "leche", "fiesta", "caribe"],
  },
  {
    slug: "alfajores",
    name: "Alfajores",
    nameLocal: "Alfajores de maicena",
    country: "Argentina",
    city: "Buenos Aires",
    regionId: "latam",
    flavors: ["dulce", "cremoso"],
    profile: { picante: 0, umami: 1, acido: 1, dulce: 8, grasa: 6, aroma: 5 },
    timeMin: 50,
    servings: 12,
    difficulty: "fácil",
    moods: ["consuelo", "fiesta"],
    ingredients: [
      { item: "Maicena y harina", amount: "200 g y 80 g", key: "trigo" },
      { item: "Manteca", amount: "150 g", key: "leche" },
      { item: "Yemas", amount: "3", key: "huevo" },
      { item: "Dulce de leche", amount: "300 g", key: "leche" },
      { item: "Coco rallado", amount: "80 g", key: "coco" },
      { item: "Esencia de vainilla", amount: "1 cdita", key: "vainilla" },
    ],
    steps: [
      "Amasa manteca, yemas, maicena, harina, vainilla. Frío 30 min.",
      "Estira, corta círculos. Horno 180 °C 10 min: apenas dorados.",
      "Fríos. Dulce de leche generoso. Cierra, rueda por coco.",
      "Reposan un día. El alfajor de verdad se come al siguiente.",
    ],
    story: "Buenos Aires cabe en dos tapas de maicena. El dulce de leche es la patria entre galletas.",
    tip: "No las dore. Si se tuestan, se ponen galleta y el alfajor pierde el desmayo.",
    image: "/dishes/alfajores.jpg",
    tags: ["postre", "dulce de leche", "galleta", "argentina"],
  },
  {
    slug: "baklava",
    name: "Baklava",
    nameLocal: "Baklava",
    country: "Turquía",
    city: "Gaziantep",
    regionId: "medio-oriente",
    flavors: ["dulce", "ahumado"],
    profile: { picante: 0, umami: 2, acido: 1, dulce: 9, grasa: 7, aroma: 6 },
    timeMin: 90,
    servings: 12,
    difficulty: "alta",
    moods: ["fiesta", "impresionar"],
    ingredients: [
      { item: "Masa filo", amount: "400 g", key: "trigo" },
      { item: "Pistacho o nuez", amount: "300 g", key: "cacahuete" },
      { item: "Mantequilla clarificada", amount: "250 g", key: "leche" },
      { item: "Azúcar y agua", amount: "300 g y 200 ml", key: "azucar" },
      { item: "Limón", amount: "1", key: "limon" },
    ],
    steps: [
      "Almíbar: azúcar, agua, limón. Hierve 10 min. Enfría.",
      "Capa filo, mantequilla, capa. A la mitad, pistacho picado. Sigue hasta el final.",
      "Corta en diamantes antes del horno. 170 °C 40 min, dorado.",
      "Almíbar frío sobre baklava caliente. Reposa. El crujiente pide espera.",
    ],
    story: "Gaziantep corta el pistacho como quien corta un tesoro. El baklava es arquitectura de miel y mantequilla.",
    tip: "Caliente sobre frío, o frío sobre caliente. Nunca los dos calientes: se empapa y se rinde.",
    image: "/dishes/baklava.jpg",
    tags: ["postre", "pistacho", "filo", "turquia"],
  },
  {
    slug: "mango-sticky-rice",
    name: "Mango sticky rice",
    nameLocal: "ข้าวเหนียวมะม่วง",
    country: "Tailandia",
    city: "Bangkok",
    regionId: "asia-sur",
    flavors: ["dulce", "cremoso", "fresco"],
    profile: { picante: 0, umami: 2, acido: 2, dulce: 8, grasa: 5, aroma: 5 },
    timeMin: 45,
    servings: 4,
    difficulty: "fácil",
    moods: ["ligero", "fiesta"],
    ingredients: [
      { item: "Arroz glutinoso", amount: "300 g", key: "arroz" },
      { item: "Leche de coco", amount: "400 ml", key: "coco" },
      { item: "Azúcar de palma", amount: "80 g", key: "azucar" },
      { item: "Mango maduro", amount: "2", key: "mango" },
      { item: "Sal", amount: "una pizca", key: "sal" },
      { item: "Frijol mungo tostado", amount: "2 cdas", key: "frijol" },
    ],
    steps: [
      "Remoja el arroz 4 horas. Cuece al vapor 25 min.",
      "Calienta coco, azúcar, sal. Vierte sobre el arroz caliente. Tapa 15 min.",
      "Corta el mango en abanico. Una cucharada de coco espeso encima.",
      "Frijol tostado. Se come a temperatura de patio, no de nevera.",
    ],
    story: "Tailandia pone el mango al lado del arroz, no encima. El postre es un acuerdo entre fruta y coco.",
    tip: "El mango tiene que ceder al cuchillo. Si está verde, espera. El plato no perdona la prisa.",
    image: "/dishes/mango-sticky-rice.jpg",
    tags: ["postre", "mango", "coco", "tailandia"],
  },
  {
    slug: "churros",
    name: "Churros",
    nameLocal: "Churros con chocolate",
    country: "España",
    city: "Madrid",
    regionId: "mediterraneo",
    flavors: ["dulce", "cremoso"],
    profile: { picante: 0, umami: 2, acido: 1, dulce: 7, grasa: 7, aroma: 5 },
    timeMin: 40,
    servings: 4,
    difficulty: "media",
    moods: ["fiesta", "consuelo"],
    ingredients: [
      { item: "Harina", amount: "250 g", key: "trigo" },
      { item: "Agua y sal", amount: "250 ml y 1 cdita", key: "sal" },
      { item: "Aceite para freír", amount: "1 l", key: "aceite" },
      { item: "Azúcar", amount: "para rebozar", key: "azucar" },
      { item: "Chocolate negro", amount: "200 g", key: "chocolate" },
      { item: "Leche", amount: "250 ml", key: "leche" },
    ],
    steps: [
      "Hierve agua con sal. Harina de golpe, remueve hasta masa lisa. Enfría un poco.",
      "Manga de estrella. Churros en aceite a 180 °C hasta dorar. Azúcar.",
      "Chocolate y leche a fuego bajo, espeso como nata.",
      "Se moja de pie, de madrugada o de resaca. El chocolate no se bebe: se empuja.",
    ],
    story: "Madrid frita el desayuno y lo moja en chocolate. El churro es calle, aceite y madrugada.",
    tip: "La masa tiene que estar caliente al salir por la manga. Si está fría, el churro se abre.",
    image: "/dishes/churros.jpg",
    tags: ["postre", "frito", "chocolate", "madrid"],
  },
  {
    slug: "pastel-de-nata",
    name: "Pastel de nata",
    nameLocal: "Pastel de nata",
    country: "Portugal",
    city: "Lisboa",
    regionId: "europa",
    flavors: ["dulce", "cremoso", "ahumado"],
    profile: { picante: 0, umami: 2, acido: 2, dulce: 7, grasa: 7, aroma: 6 },
    timeMin: 70,
    servings: 12,
    difficulty: "alta",
    moods: ["impresionar", "fiesta"],
    ingredients: [
      { item: "Hojaldre", amount: "300 g", key: "trigo" },
      { item: "Leche", amount: "500 ml", key: "leche" },
      { item: "Yemas", amount: "6", key: "huevo" },
      { item: "Azúcar", amount: "200 g", key: "azucar" },
      { item: "Harina", amount: "40 g", key: "trigo" },
      { item: "Canela y cáscara de limón", amount: "al gusto", key: "canela" },
    ],
    steps: [
      "Hojaldre en rollito, corta, abre en moldes con los dedos: paredes altas.",
      "Leche, azúcar, limón, canela. Harina disuelta. Cuece hasta crema.",
      "Fuera del fuego, yemas. Rellena los moldes a tres cuartos.",
      "Horno al máximo 12 min: manchas negras en la crema. Se come tibio.",
    ],
    story: "Belém enseña que la crema se quema a propósito. El pastel de nata es fuego y yema.",
    tip: "El horno tiene que estar brutal. Sin manchas, no es nata: es flan.",
    image: "/dishes/pastel-de-nata.jpg",
    tags: ["postre", "hojaldre", "lisboa", "crema"],
  },
  {
    slug: "knafeh",
    name: "Knafeh",
    nameLocal: "كنافة",
    country: "Palestina",
    city: "Nablus",
    regionId: "medio-oriente",
    flavors: ["dulce", "cremoso"],
    profile: { picante: 0, umami: 3, acido: 2, dulce: 8, grasa: 7, aroma: 6 },
    timeMin: 50,
    servings: 8,
    difficulty: "media",
    moods: ["fiesta", "impresionar"],
    ingredients: [
      { item: "Kataifi o masa rallada", amount: "400 g", key: "trigo" },
      { item: "Queso fresco para hornear", amount: "400 g", key: "queso" },
      { item: "Mantequilla", amount: "150 g", key: "leche" },
      { item: "Azúcar, agua y agua de azahar", amount: "para almíbar", key: "azucar" },
      { item: "Pistacho", amount: "80 g", key: "cacahuete" },
    ],
    steps: [
      "Almíbar con azahar. Enfría.",
      "Kataifi con mantequilla. Capa, queso, capa. Prensa.",
      "Horno 180 °C 30 min, dorado. Voltea si te atreves.",
      "Almíbar sobre el knafeh caliente. Pistacho. Se corta en caliente, el queso hila.",
    ],
    story: "Nablus hace el queso dulce y el almíbar de azahar. El knafeh se come de pie, todavía humeando.",
    tip: "El queso no puede ser cualquiera: que hile y no amargue. Si se suelta agua, escúrrelo antes.",
    image: "/dishes/knafeh.jpg",
    tags: ["postre", "queso", "azahar", "palestina"],
  },
  {
    slug: "arroz-con-leche",
    name: "Arroz con leche",
    nameLocal: "Arroz con leche",
    country: "Colombia",
    city: "Medellín",
    regionId: "latam",
    flavors: ["dulce", "cremoso"],
    profile: { picante: 0, umami: 2, acido: 1, dulce: 7, grasa: 5, aroma: 6 },
    timeMin: 50,
    servings: 6,
    difficulty: "fácil",
    moods: ["consuelo"],
    ingredients: [
      { item: "Arroz", amount: "200 g", key: "arroz" },
      { item: "Leche", amount: "1.2 l", key: "leche" },
      { item: "Canela en rama", amount: "2", key: "canela" },
      { item: "Azúcar", amount: "150 g", key: "azucar" },
      { item: "Cáscara de limón", amount: "1", key: "limon" },
      { item: "Pasas (opcional)", amount: "un puñado", key: "pasa" },
    ],
    steps: [
      "Tuesta el arroz 2 min en seco. Leche, canela, limón. Fuego bajo.",
      "Remueve. 35 min hasta crema, el grano tierno.",
      "Azúcar al final, 5 min más. Apaga. La canela se queda.",
      "Tibio o frío. Canela en polvo. Es el postre de abuela que no se discute.",
    ],
    story: "En Colombia el arroz también se endulza. La canela es el país; la leche, la casa.",
    tip: "El azúcar al final. Si va al principio, el grano no se abre.",
    image: "/dishes/arroz-con-leche.jpg",
    tags: ["postre", "arroz", "canela", "consuelo"],
  },
  {
    slug: "cafe-de-olla",
    name: "Café de olla",
    nameLocal: "Café de olla",
    country: "México",
    city: "Michoacán",
    regionId: "latam",
    flavors: ["dulce", "ahumado", "herbal"],
    profile: { picante: 0, umami: 3, acido: 2, dulce: 5, grasa: 1, aroma: 8 },
    timeMin: 15,
    servings: 4,
    difficulty: "fácil",
    moods: ["consuelo", "ligero"],
    ingredients: [
      { item: "Café de olla molido grueso", amount: "6 cdas", key: "cafe" },
      { item: "Piloncillo", amount: "80 g", key: "azucar" },
      { item: "Canela", amount: "2 ramas", key: "canela" },
      { item: "Agua", amount: "1 l", key: "agua" },
      { item: "Anís o naranja (opcional)", amount: "una pizca", key: "anís" },
    ],
    steps: [
      "Agua, piloncillo y canela. Hierve hasta disolver.",
      "Apaga. Café. Tapa 5 min. No hiervas el café.",
      "Cuela. Sirve en jarrito de barro si hay.",
      "Se bebe humeante. El piloncillo no es azúcar: es tierra dulce.",
    ],
    story: "El café mexicano se cocina en olla, con canela y piloncillo. No es espresso: es fogón.",
    tip: "Nunca hiervas el café. Se amarga y pierdes el acuerdo con la canela.",
    image: "/dishes/cafe-de-olla.jpg",
    tags: ["bebida", "cafe", "canela", "mexico"],
  },
  {
    slug: "masala-chai",
    name: "Masala chai",
    nameLocal: "मसाला चाय",
    country: "India",
    city: "Mumbai",
    regionId: "asia-sur",
    flavors: ["dulce", "picante", "herbal"],
    profile: { picante: 3, umami: 2, acido: 1, dulce: 5, grasa: 3, aroma: 8 },
    timeMin: 15,
    servings: 2,
    difficulty: "fácil",
    moods: ["consuelo", "ligero"],
    ingredients: [
      { item: "Té negro", amount: "2 cditas", key: "te" },
      { item: "Leche", amount: "300 ml", key: "leche" },
      { item: "Jengibre fresco", amount: "3 cm", key: "jengibre" },
      { item: "Cardamomo, canela, clavo", amount: "al gusto", key: "canela" },
      { item: "Azúcar", amount: "2 cditas", key: "azucar" },
      { item: "Agua", amount: "200 ml", key: "agua" },
    ],
    steps: [
      "Machaca jengibre y cardamomo. Agua, especias, hierve 3 min.",
      "Té. 1 min. Leche. Hierve hasta que suba.",
      "Azúcar. Cuela con fuerza, de alto, para espuma.",
      "Vaso pequeño. Se bebe en la calle, de pie, antes del tren.",
    ],
    story: "El chai no es té con leche: es especias que encontraron la vaca. Mumbai lo sirve a mil por hora.",
    tip: "El jengibre va fresco y a golpes. En polvo, el chai se vuelve perfume barato.",
    image: "/dishes/masala-chai.jpg",
    tags: ["bebida", "te", "jengibre", "india"],
  },
  {
    slug: "mate",
    name: "Mate",
    nameLocal: "Mate",
    country: "Argentina",
    city: "Buenos Aires",
    regionId: "latam",
    flavors: ["herbal", "fresco", "umami"],
    profile: { picante: 0, umami: 3, acido: 3, dulce: 0, grasa: 0, aroma: 7 },
    timeMin: 10,
    servings: 2,
    difficulty: "fácil",
    moods: ["ligero", "consuelo"],
    ingredients: [
      { item: "Yerba mate", amount: "2/3 de la calabaza", key: "yerba" },
      { item: "Agua a 75 °C", amount: "1 l", key: "agua" },
      { item: "Bombilla", amount: "1", key: "agua" },
    ],
    steps: [
      "Llena la calabaza a dos tercios. Tapa, agita, deja un hueco a un lado.",
      "Agua tibia en el hueco. Bombilla, sin revolver.",
      "Ceba siempre en el mismo lado. Agua que no hierva.",
      "Se comparte en ronda. El mate no es bebida: es conversación.",
    ],
    story: "El Río de la Plata se entiende por la bombilla. El mate amarga, junta y no se termina.",
    tip: "Si el agua hierve, quemas la yerba y el mate se pone agresivo. 70 a 80 °C.",
    image: "/dishes/mate.jpg",
    tags: ["bebida", "yerba", "ronda", "argentina"],
  },
  {
    slug: "horchata",
    name: "Horchata",
    nameLocal: "Horchata de arroz",
    country: "México",
    city: "Oaxaca",
    regionId: "latam",
    flavors: ["dulce", "cremoso"],
    profile: { picante: 0, umami: 1, acido: 1, dulce: 6, grasa: 2, aroma: 5 },
    timeMin: 25,
    servings: 6,
    difficulty: "fácil",
    moods: ["ligero", "fiesta"],
    ingredients: [
      { item: "Arroz", amount: "200 g", key: "arroz" },
      { item: "Canela", amount: "1 rama", key: "canela" },
      { item: "Leche (opcional)", amount: "250 ml", key: "leche" },
      { item: "Azúcar", amount: "100 g", key: "azucar" },
      { item: "Vainilla", amount: "1 cdita", key: "vainilla" },
      { item: "Agua", amount: "1.2 l", key: "agua" },
    ],
    steps: [
      "Remoja arroz y canela 4 horas o toda la noche.",
      "Licúa con parte del agua. Cuela fino, dos veces.",
      "Azúcar, vainilla, el resto del agua. Hielo.",
      "Vaso alto. Canela encima. El mercado se oye en el vaso.",
    ],
    story: "Oaxaca cuela el arroz hasta que se vuelve leche. La horchata es sombra y canela.",
    tip: "Cuela dos veces. Si queda grano, no es horchata: es atole disfrazado.",
    image: "/dishes/horchata.jpg",
    tags: ["bebida", "arroz", "canela", "oaxaca"],
  },
  {
    slug: "mango-lassi",
    name: "Lassi de mango",
    nameLocal: "आम लस्सी",
    country: "India",
    city: "Delhi",
    regionId: "asia-sur",
    flavors: ["dulce", "cremoso", "fresco"],
    profile: { picante: 0, umami: 2, acido: 3, dulce: 7, grasa: 4, aroma: 4 },
    timeMin: 10,
    servings: 2,
    difficulty: "fácil",
    moods: ["ligero", "fiesta"],
    ingredients: [
      { item: "Mango maduro", amount: "2", key: "mango" },
      { item: "Yogur natural", amount: "300 g", key: "yogurt" },
      { item: "Leche o agua", amount: "100 ml", key: "leche" },
      { item: "Azúcar o miel", amount: "2 cdas", key: "azucar" },
      { item: "Cardamomo", amount: "1 pizca", key: "canela" },
    ],
    steps: [
      "Pela el mango. Pulpa sin hebras.",
      "Licúa con yogur, leche, azúcar, cardamomo. Hielo si hace calor.",
      "Vaso alto. Un mango más encima si hay.",
      "Se bebe después del curry, o en su lugar cuando el día pica.",
    ],
    story: "El lassi enfría lo que el chile encendió. Delhi lo sirve espeso, casi cuchara.",
    tip: "El mango Alphonso si aparece. Si no, el más perfumado que encuentres, nunca verde.",
    image: "/dishes/mango-lassi.jpg",
    tags: ["bebida", "mango", "yogurt", "india"],
  },
  {
    slug: "ca-phe-trung",
    name: "Cà phê trứng",
    nameLocal: "Cà phê trứng",
    country: "Vietnam",
    city: "Hanoi",
    regionId: "asia-este",
    flavors: ["dulce", "cremoso", "ahumado"],
    profile: { picante: 0, umami: 4, acido: 2, dulce: 6, grasa: 6, aroma: 7 },
    timeMin: 15,
    servings: 2,
    difficulty: "media",
    moods: ["impresionar", "consuelo"],
    ingredients: [
      { item: "Café robusta fuerte", amount: "80 ml", key: "cafe" },
      { item: "Yema", amount: "2", key: "huevo" },
      { item: "Leche condensada", amount: "3 cdas", key: "leche" },
      { item: "Azúcar", amount: "1 cdita", key: "azucar" },
    ],
    steps: [
      "Bate yema, condensada y azúcar hasta espuma pálida, 4 min.",
      "Café bien corto, bien amargo, en la taza.",
      "Espuma de yema encima, como un sombrero.",
      "No se revuelve al principio. Se bebe la crema, después el café, después el acuerdo.",
    ],
    story: "Hanoi bate yema sobre robusta. El café de huevo nació de la escasez y se quedó por lujo.",
    tip: "La yema tiene que montar. Si queda líquida, no es cà phê trứng: es revuelto dulce.",
    image: "/dishes/ca-phe-trung.jpg",
    tags: ["bebida", "cafe", "huevo", "hanoi"],
  },
  {
    slug: "pisco-sour",
    name: "Pisco sour",
    nameLocal: "Pisco sour",
    country: "Perú",
    city: "Lima",
    regionId: "latam",
    flavors: ["citrico", "dulce", "fresco"],
    profile: { picante: 0, umami: 1, acido: 8, dulce: 5, grasa: 1, aroma: 6 },
    timeMin: 10,
    servings: 2,
    difficulty: "fácil",
    moods: ["fiesta", "impresionar"],
    ingredients: [
      { item: "Pisco quebradito o acholado", amount: "120 ml", key: "pisco" },
      { item: "Jugo de limón", amount: "40 ml", key: "limon" },
      { item: "Jarabe de goma", amount: "30 ml", key: "azucar" },
      { item: "Clara de huevo", amount: "1", key: "huevo" },
      { item: "Amargo de angostura", amount: "3 gotas", key: "amargo" },
      { item: "Hielo", amount: "1 taza", key: "hielo" },
    ],
    steps: [
      "Pisco, limón, jarabe, clara. Dry shake sin hielo 10 segundos.",
      "Hielo. Agita fuerte 15 segundos.",
      "Cuela en copa fría. Tres gotas de amargo sobre la espuma.",
      "No se brinda hasta ver la espuma. Lima enseña que el cóctel también tiene merengue.",
    ],
    story: "El pisco sour es la bandera líquida. El limón de Lima y la uva del valle se pelean en la copa y se reconcilian en la espuma.",
    tip: "La clara va fresca. Si la espuma no sostiene las gotas de amargo, faltó muñeca.",
    image: "/dishes/pisco-sour.jpg",
    tags: ["bebida", "pisco", "coctel", "lima"],
  },
  {
    slug: "canelazo",
    name: "Canelazo",
    nameLocal: "Canelazo",
    country: "Colombia",
    city: "Bogotá",
    regionId: "latam",
    flavors: ["dulce", "picante", "herbal"],
    profile: { picante: 2, umami: 1, acido: 1, dulce: 6, grasa: 0, aroma: 8 },
    timeMin: 20,
    servings: 4,
    difficulty: "fácil",
    moods: ["consuelo", "fiesta"],
    ingredients: [
      { item: "Agua", amount: "800 ml", key: "agua" },
      { item: "Panela", amount: "150 g", key: "azucar" },
      { item: "Canela", amount: "3 ramas", key: "canela" },
      { item: "Aguardiente o naranja (opcional)", amount: "120 ml", key: "aguardiente" },
      { item: "Clavos de olor", amount: "3", key: "clavo" },
    ],
    steps: [
      "Agua, panela, canela, clavo. Hierve 10 min hasta agua de canela.",
      "Apaga. Aguardiente si va, fuera del fuego.",
      "Vaso pequeño, humeante. La canela se queda en la jarra.",
      "Se bebe en el páramo, en diciembre, o cuando Bogotá muerde.",
    ],
    story: "El canelazo es la manta líquida de la cordillera. Panela, canela y un trago si la noche pide.",
    tip: "El alcohol se suma apagado. Si hierve, se va el ánimo y queda solo el dulce.",
    image: "/dishes/canelazo.jpg",
    tags: ["bebida", "canela", "panela", "bogota"],
  },
];
