import type { RecipeSource } from "./recipe-types";

export const EXPANSION: RecipeSource[] = [
  {
    slug: "ropa-vieja",
    name: "Ropa vieja",
    nameLocal: "Ropa vieja",
    country: "Cuba",
    city: "La Habana",
    regionId: "caribe",
    flavors: ["umami", "dulce", "picante"],
    profile: { picante: 3, umami: 8, acido: 4, dulce: 4, grasa: 5, aroma: 7 },
    timeMin: 150,
    servings: 6,
    difficulty: "fácil",
    moods: ["consuelo", "fiesta"],
    ingredients: [
      { item: "Falda de res", amount: "1 kg", key: "res" },
      { item: "Pimiento rojo y verde", amount: "2", key: "tomate" },
      { item: "Tomate triturado", amount: "400 g", key: "tomate" },
      { item: "Cebolla y ajo", amount: "2 y 4", key: "cebolla" },
      { item: "Vino seco y comino", amount: "al ras", key: "comino" },
      { item: "Aceitunas y alcaparras", amount: "un puñado", key: "aceituna" },
      { item: "Arroz y plátano maduro", amount: "para servir", key: "arroz" },
      { item: "Frijoles negros", amount: "para servir", key: "frijol" },
    ],
    steps: [
      "Hierve la falda con laurel hasta que se deshaga. Reserva el caldo. Deshebra.",
      "Sofríe cebolla, pimiento y ajo. Tomate, comino, un chorro de vino.",
      "Suma la carne y caldo. 25 minutos. Aceitunas al final.",
      "Arroz blanco, frijoles negros, plátano maduro frito. El trío cubano.",
    ],
    story: "La ropa de quien volvió: hebras de res que parecen tela vieja. El plato nacional que sabe a domingo en La Habana.",
    tip: "Deshebra en caliente. En frío se pone terca y el sofrito no la abraza.",
    image: "/dishes/ropa-vieja.jpg",
    tags: ["cuba", "res", "estofado", "clasico"],
  },
  {
    slug: "mofongo",
    name: "Mofongo",
    nameLocal: "Mofongo",
    country: "Puerto Rico",
    city: "San Juan",
    regionId: "caribe",
    flavors: ["ahumado", "umami", "cremoso"],
    profile: { picante: 2, umami: 7, acido: 2, dulce: 2, grasa: 7, aroma: 6 },
    timeMin: 40,
    servings: 4,
    difficulty: "media",
    moods: ["consuelo", "fiesta"],
    ingredients: [
      { item: "Plátanos verdes", amount: "4", key: "platano" },
      { item: "Ajo", amount: "6 dientes", key: "ajo" },
      { item: "Chicharrón de cerdo", amount: "150 g", key: "cerdo" },
      { item: "Aceite de oliva o manteca", amount: "3 cdas", key: "ajo" },
      { item: "Caldo de pollo", amount: "1 taza", key: "pollo" },
      { item: "Cilantro", amount: "al gusto", key: "cilantro" },
    ],
    steps: [
      "Pela y corta los plátanos. Fríe hasta dorar sin secar.",
      "En el pilón: ajo, sal, chicharrón. Machaca los plátanos todavía calientes.",
      "Un hilo de caldo para unir. Forma un volcán o una bola.",
      "Sirve con más caldo en jarrita. El mofongo se bebe tanto como se come.",
    ],
    story: "Taíno y africano en un pilón. El plátano verde es el pan de la isla, y el ajo no se negocia.",
    tip: "Si se pone pegote, le falta chicharrón o aceite. Si se desmorona, un chorro de caldo.",
    image: "/dishes/mofongo.jpg",
    tags: ["puerto-rico", "platano", "ajo", "cerdo"],
  },
  {
    slug: "jerk-chicken",
    name: "Pollo jerk",
    nameLocal: "Jerk chicken",
    country: "Jamaica",
    city: "Boston Bay",
    regionId: "caribe",
    flavors: ["picante", "ahumado", "dulce"],
    profile: { picante: 8, umami: 7, acido: 4, dulce: 4, grasa: 5, aroma: 9 },
    timeMin: 80,
    servings: 4,
    difficulty: "media",
    moods: ["fiesta", "impresionar"],
    ingredients: [
      { item: "Pollo en cuartos", amount: "1.5 kg", key: "pollo" },
      { item: "Scotch bonnet", amount: "2", key: "chile" },
      { item: "Cebolla y cebollín", amount: "1 y 4", key: "cebolla" },
      { item: "Jengibre, ajo, tomillo", amount: "pasta", key: "jengibre" },
      { item: "Pimentón, pimienta de Jamaica", amount: "1 cda c/u", key: "pimenton" },
      { item: "Soya y azúcar moreno", amount: "2 cdas c/u", key: "soya" },
      { item: "Lima", amount: "1", key: "limon" },
    ],
    steps: [
      "Licúa el jerk: chile, allspice, tomillo, soya, azúcar, jengibre, ajo.",
      "Marina el pollo mínimo 4 horas, mejor de un día para otro.",
      "Parrilla o horno 200 °C, piel abajo primero. Carbón de pimento si puedes.",
      "Deja reposar. Festival o arroz con guandú. El humo es medio plato.",
    ],
    story: "Maroon y cimarrón: carne al pimento wood, chile que habla alto. Jamaica no pide permiso.",
    tip: "Quita las semillas del bonnet si comes con gente educada. Déjalas si comes con gente honesta.",
    image: "/dishes/jerk-chicken.jpg",
    tags: ["jamaica", "parrilla", "picante", "humo"],
  },
  {
    slug: "sancocho",
    name: "Sancocho",
    nameLocal: "Sancocho",
    country: "República Dominicana",
    city: "Santo Domingo",
    regionId: "caribe",
    flavors: ["umami", "herbal", "fresco"],
    profile: { picante: 2, umami: 8, acido: 3, dulce: 3, grasa: 5, aroma: 6 },
    timeMin: 120,
    servings: 8,
    difficulty: "fácil",
    moods: ["consuelo", "fiesta"],
    ingredients: [
      { item: "Pollo y res", amount: "800 g c/u", key: "pollo" },
      { item: "Yuca y ñame", amount: "400 g c/u", key: "papa" },
      { item: "Plátano verde", amount: "2", key: "platano" },
      { item: "Mazorca de maíz", amount: "2", key: "maiz" },
      { item: "Cilantro y recao", amount: "un manojo", key: "cilantro" },
      { item: "Ajo y cebolla", amount: "4 y 1", key: "ajo" },
      { item: "Limón", amount: "1", key: "limon" },
    ],
    steps: [
      "Dora las carnes. Cubre con agua, ajo, cilantro. Espuma.",
      "A los 40 minutos, yuca, ñame, plátano, maíz. Fuego medio.",
      "Cuando las raíces cedan, ajusta sal y un chorro de limón.",
      "Aguacate y arroz al lado. El sancocho es reunión, no ración.",
    ],
    story: "Cada isla tiene el suyo. El dominicano es el de siete carnes cuando hay fiesta, y de una cuando hay resaca.",
    tip: "El cilantro se parte: tallos al caldo, hojas al final. Si va todo junto, se apaga.",
    image: "/dishes/sancocho.jpg",
    tags: ["caribe", "sopa", "yuca", "fiesta"],
  },
  {
    slug: "chiles-en-nogada",
    name: "Chiles en nogada",
    nameLocal: "Chiles en nogada",
    country: "México",
    city: "Puebla",
    regionId: "latam",
    flavors: ["dulce", "cremoso", "picante"],
    profile: { picante: 3, umami: 6, acido: 3, dulce: 6, grasa: 7, aroma: 7 },
    timeMin: 90,
    servings: 6,
    difficulty: "alta",
    moods: ["impresionar", "fiesta"],
    ingredients: [
      { item: "Chiles poblanos", amount: "6", key: "chile" },
      { item: "Picadillo de cerdo y res", amount: "500 g", key: "cerdo" },
      { item: "Fruta (durazno, manzana, plátano)", amount: "300 g", key: "platano" },
      { item: "Nuez de Castilla", amount: "250 g", key: "cacahuete" },
      { item: "Queso fresco y leche", amount: "para nogada", key: "leche" },
      { item: "Granada", amount: "2", key: "citrico" },
      { item: "Perejil", amount: "un ramito", key: "cilantro" },
    ],
    steps: [
      "Tosta y pela los poblanos. Desvena con cuidado.",
      "Picadillo con fruta, almendras, canela. Rellena.",
      "Nogada: nuez pelada, queso, leche, un toque de jerez. Fría.",
      "Cubre, granada, perejil. Bandera comestible de septiembre.",
    ],
    story: "Puebla, 1821: las monjas delatan la independencia en un chile. Dulce, blanco y verde.",
    tip: "Pela cada nuez. La piel amarga la nogada y arruina el mes patrio.",
    image: "/dishes/chiles-en-nogada.jpg",
    tags: ["mexico", "puebla", "fiesta", "nuez"],
  },
  {
    slug: "pastel-de-choclo",
    name: "Pastel de choclo",
    nameLocal: "Pastel de choclo",
    country: "Chile",
    city: "Santiago",
    regionId: "latam",
    flavors: ["dulce", "umami", "herbal"],
    profile: { picante: 1, umami: 7, acido: 2, dulce: 6, grasa: 6, aroma: 5 },
    timeMin: 80,
    servings: 6,
    difficulty: "media",
    moods: ["consuelo", "fiesta"],
    ingredients: [
      { item: "Choclo tierno", amount: "1 kg", key: "maiz" },
      { item: "Carne molida de res", amount: "500 g", key: "res" },
      { item: "Cebolla", amount: "2", key: "cebolla" },
      { item: "Pollo deshebrado", amount: "200 g", key: "pollo" },
      { item: "Huevo duro y aceitunas", amount: "3 y 80 g", key: "huevo" },
      { item: "Albahaca y azúcar", amount: "al ras", key: "albahaca" },
      { item: "Leche y mantequilla", amount: "para la pasta", key: "leche" },
    ],
    steps: [
      "Pino: sofríe cebolla y carne. Comino. Enfría. Suma pollo, huevo, aceituna.",
      "Muele el choclo con albahaca, leche y un pellizco de azúcar.",
      "En pailas: pino abajo, choclo arriba. Azúcar para gratinar.",
      "Horno 200 °C hasta que la costra se manche de oro.",
    ],
    story: "El choclo andino cubriendo el pino. Dulce y salado, como las mesas de campo chilenas en marzo.",
    tip: "El choclo tiene que ser tierno. El de choclo viejo sale arenoso y no hay horno que lo salve.",
    image: "/dishes/pastel-de-choclo.jpg",
    tags: ["chile", "maiz", "horno", "campo"],
  },
  {
    slug: "tteokbokki",
    name: "Tteokbokki",
    nameLocal: "떡볶이",
    country: "Corea del Sur",
    city: "Seúl",
    regionId: "asia-este",
    flavors: ["picante", "dulce", "umami"],
    profile: { picante: 7, umami: 7, acido: 2, dulce: 6, grasa: 4, aroma: 6 },
    timeMin: 25,
    servings: 2,
    difficulty: "fácil",
    moods: ["fiesta", "consuelo"],
    ingredients: [
      { item: "Tteok (pastel de arroz)", amount: "400 g", key: "arroz" },
      { item: "Gochujang", amount: "3 cdas", key: "chile" },
      { item: "Gochugaru", amount: "1 cda", key: "chile" },
      { item: "Caldo de anchoa o dashi", amount: "400 ml", key: "pescado" },
      { item: "Eomuk (pastel de pescado)", amount: "4 láminas", key: "pescado" },
      { item: "Huevo duro y cebollín", amount: "2", key: "huevo" },
      { item: "Azúcar y soya", amount: "1 cda c/u", key: "soya" },
    ],
    steps: [
      "Remoja el tteok si viene frío. Caldo a fuego medio.",
      "Gochujang, gochugaru, soya, azúcar. Disuelve.",
      "Tteok y eomuk. Reduce 8 minutos hasta que la salsa abrace.",
      "Huevo, sésamo, cebollín. Se come en el puesto, soplando.",
    ],
    story: "El antojo de las calles de Seúl. Picante-dulce que pega en los palillos y en la memoria.",
    tip: "Si se espesa de más, un cucharón de caldo. El tteok sigue absorbiendo después de apagar.",
    image: "/dishes/tteokbokki.jpg",
    tags: ["corea", "picante", "calle", "arroz"],
  },
  {
    slug: "banh-mi",
    name: "Bánh mì",
    nameLocal: "Bánh mì thịt",
    country: "Vietnam",
    city: "Saigón",
    regionId: "asia-este",
    flavors: ["fresco", "umami", "citrico"],
    profile: { picante: 4, umami: 7, acido: 6, dulce: 3, grasa: 5, aroma: 7 },
    timeMin: 30,
    servings: 4,
    difficulty: "fácil",
    moods: ["ligero", "fiesta"],
    ingredients: [
      { item: "Baguette ligera", amount: "4", key: "trigo" },
      { item: "Cerdo asado o fiambre", amount: "300 g", key: "cerdo" },
      { item: "Paté de hígado", amount: "4 cdas", key: "cerdo" },
      { item: "Daikon y zanahoria encurtidos", amount: "200 g", key: "zanahoria" },
      { item: "Cilantro y chile", amount: "al gusto", key: "cilantro" },
      { item: "Mayonesa y soya", amount: "al ras", key: "soya" },
      { item: "Pepino", amount: "1", key: "limon" },
    ],
    steps: [
      "Encurtido rápido: daikon, zanahoria, vinagre, azúcar, sal. 20 minutos.",
      "Abre el pan, tosta el interior. Paté y mayo.",
      "Carne, pepino, encurtido, cilantro, chile.",
      "Un chorro de soya. Se come en la calle, de pie, desmigando.",
    ],
    story: "Francia dejó el pan; Vietnam lo llenó de hierba, paté y chile. El sándwich más justo del mundo.",
    tip: "El pan tiene que ser corteza fina y miga aireada. Un pan rústico europeo lo aplasta.",
    image: "/dishes/banh-mi.jpg",
    tags: ["vietnam", "sandwich", "calle", "cerdo"],
  },
  {
    slug: "dan-dan-mian",
    name: "Dan dan mian",
    nameLocal: "担担面",
    country: "China",
    city: "Chengdu",
    regionId: "asia-este",
    flavors: ["picante", "umami", "ahumado"],
    profile: { picante: 8, umami: 8, acido: 3, dulce: 2, grasa: 7, aroma: 8 },
    timeMin: 25,
    servings: 2,
    difficulty: "fácil",
    moods: ["consuelo", "impresionar"],
    ingredients: [
      { item: "Fideos de trigo", amount: "300 g", key: "fideos" },
      { item: "Cerdo picado", amount: "150 g", key: "cerdo" },
      { item: "Pasta de sésamo", amount: "2 cdas", key: "cacahuete" },
      { item: "Aceite de chile y soya", amount: "2 cdas c/u", key: "chile" },
      { item: "Pimienta de Sichuan", amount: "1 cdita", key: "chile" },
      { item: "Ya cai (mostaza conservada)", amount: "2 cdas", key: "soya" },
      { item: "Cebollín y cacahuete", amount: "para servir", key: "cacahuete" },
    ],
    steps: [
      "Sofríe el cerdo con ya cai hasta que quede tostado y seco.",
      "En el plato: sésamo, chile, soya, un chorro de agua de pasta, Sichuan.",
      "Fideos, carne encima, cebollín, cacahuete.",
      "Mezcla en la mesa. El aceite tiene que teñir cada hebra.",
    ],
    story: "Los vendedores de palo (dàn) en Sichuan. Málà otra vez: duele y alegra a la vez.",
    tip: "Sin ya cai se queda cojo. Un poco de col fermentada es el plan B.",
    image: "/dishes/dan-dan-mian.jpg",
    tags: ["sichuan", "fideos", "picante", "sésamo"],
  },
  {
    slug: "tonkatsu",
    name: "Tonkatsu",
    nameLocal: "とんかつ",
    country: "Japón",
    city: "Tokio",
    regionId: "asia-este",
    flavors: ["umami", "cremoso", "citrico"],
    profile: { picante: 1, umami: 7, acido: 3, dulce: 3, grasa: 8, aroma: 4 },
    timeMin: 35,
    servings: 2,
    difficulty: "media",
    moods: ["consuelo", "impresionar"],
    ingredients: [
      { item: "Lomo o chuleta de cerdo", amount: "2 gruesas", key: "cerdo" },
      { item: "Panko", amount: "2 tazas", key: "trigo" },
      { item: "Harina y huevo", amount: "para empanar", key: "huevo" },
      { item: "Repollo rallado", amount: "1/4", key: "repollo" },
      { item: "Salsa tonkatsu", amount: "al gusto", key: "soya" },
      { item: "Arroz japonés", amount: "para servir", key: "arroz" },
      { item: "Limón", amount: "1", key: "limon" },
    ],
    steps: [
      "Maja el cerdo, sala, reposa. Harina, huevo, panko. Presiona.",
      "Aceite a 170 °C. Fríe hasta oro. Reposa en rejilla.",
      "Corta en tiras. Repollo, arroz, salsa, limón.",
      "El crujiente tiene que oírse. Si no, el aceite estaba frío.",
    ],
    story: "Occidente empanado a la japonesa: grueso, jugoso, panko que parece nieve frita.",
    tip: "Descansa el katsu 3 minutos. El jugo se queda; si cortas ya, se va al plato.",
    image: "/dishes/tonkatsu.jpg",
    tags: ["japon", "cerdo", "frito", "panko"],
  },
  {
    slug: "niu-rou-mian",
    name: "Sopa de res de Taiwán",
    nameLocal: "牛肉麵",
    country: "Taiwán",
    city: "Taipéi",
    regionId: "asia-este",
    flavors: ["umami", "picante", "herbal"],
    profile: { picante: 4, umami: 10, acido: 3, dulce: 2, grasa: 6, aroma: 8 },
    timeMin: 180,
    servings: 4,
    difficulty: "media",
    moods: ["consuelo"],
    ingredients: [
      { item: "Jarret o falda de res", amount: "1 kg", key: "res" },
      { item: "Fideos de trigo", amount: "400 g", key: "fideos" },
      { item: "Doubanjiang y soya oscura", amount: "2 cdas c/u", key: "soya" },
      { item: "Jengibre, ajo, cebolla", amount: "al ras", key: "jengibre" },
      { item: "Anís, canela, tomillo chino", amount: "1 ramo", key: "anís" },
      { item: "Bok choy", amount: "4", key: "repollo" },
      { item: "Mostaza encurtida y chile", amount: "para servir", key: "chile" },
    ],
    steps: [
      "Blanchea la res. Sofríe doubanjiang, ajo, jengibre.",
      "Res, soya, especias, agua. 2 horas hasta que ceda.",
      "Fideos aparte. Caldo colado, carne, bok choy.",
      "Mostaza encurtida, cebollín, aceite de chile. El caldo es el plato.",
    ],
    story: "El almuerzo nacional de Taiwán. Cada puesto jura que el suyo es el único correcto.",
    tip: "Haz el caldo el día anterior. El frío desnuda la grasa y el sabor se hunde.",
    image: "/dishes/niu-rou-mian.jpg",
    tags: ["taiwan", "res", "fideos", "caldo"],
  },
  {
    slug: "char-siu",
    name: "Char siu",
    nameLocal: "叉燒",
    country: "China",
    city: "Cantón",
    regionId: "asia-este",
    flavors: ["dulce", "ahumado", "umami"],
    profile: { picante: 1, umami: 8, acido: 2, dulce: 7, grasa: 6, aroma: 7 },
    timeMin: 90,
    servings: 4,
    difficulty: "media",
    moods: ["fiesta", "impresionar"],
    ingredients: [
      { item: "Aguja o panceta de cerdo", amount: "800 g", key: "cerdo" },
      { item: "Miel y azúcar", amount: "3 cdas", key: "miel" },
      { item: "Soya y hoisin", amount: "2 cdas c/u", key: "soya" },
      { item: "Vino de arroz y cinco especias", amount: "al ras", key: "anís" },
      { item: "Ajo y color rojo (opcional)", amount: "3 dientes", key: "ajo" },
      { item: "Arroz blanco", amount: "para servir", key: "arroz" },
    ],
    steps: [
      "Marina el cerdo mínimo 6 horas: hoisin, soya, miel, cinco especias, ajo.",
      "Horno 190 °C sobre rejilla. Voltea a mitad. 40 minutos.",
      "Últimos 8 minutos: pincela miel. Que lacas, no que queme.",
      "Reposa, lonchea. Arroz y el jugo de la bandeja.",
    ],
    story: "El rojo de Cantón. Cuelga en los escaparates de los siu mei como joya comestible.",
    tip: "No uses lomo magro. El char siu pide veta o se come a seco.",
    image: "/dishes/char-siu.jpg",
    tags: ["canton", "cerdo", "horno", "dulce"],
  },
  {
    slug: "japchae",
    name: "Japchae",
    nameLocal: "잡채",
    country: "Corea del Sur",
    city: "Seúl",
    regionId: "asia-este",
    flavors: ["umami", "dulce", "herbal"],
    profile: { picante: 1, umami: 7, acido: 2, dulce: 5, grasa: 4, aroma: 6 },
    timeMin: 40,
    servings: 4,
    difficulty: "media",
    moods: ["fiesta", "ligero"],
    ingredients: [
      { item: "Fideos de boniato (dangmyeon)", amount: "250 g", key: "fideos" },
      { item: "Res en tiras", amount: "150 g", key: "res" },
      { item: "Espinaca", amount: "150 g", key: "espinaca" },
      { item: "Zanahoria y pimiento", amount: "1 y 1", key: "zanahoria" },
      { item: "Setas shiitake", amount: "6", key: "hongo" },
      { item: "Soya, sésamo, azúcar", amount: "al ras", key: "soya" },
      { item: "Ajo y cebollín", amount: "2 y 2", key: "ajo" },
    ],
    steps: [
      "Hierve los fideos, pasa por aceite de sésamo para que no se peguen.",
      "Saltea cada verdura aparte: tiene que quedar viva, no podrida.",
      "Res con soya y ajo. Mezcla todo con soya, azúcar, sésamo.",
      "Se sirve a temperatura de sala. Es plato de banquete, no de wok apresurado.",
    ],
    story: "Bodas y años nuevos. El fideo de boniato brilla como laca y no se pasa de listo.",
    tip: "Corta los fideos un par de veces. Un nido de un metro no se come con elegancia.",
    image: "/dishes/japchae.jpg",
    tags: ["corea", "fideos", "fiesta", "sesamo"],
  },
  {
    slug: "masala-dosa",
    name: "Masala dosa",
    nameLocal: "மசாலா தோசை",
    country: "India",
    city: "Chennai",
    regionId: "asia-sur",
    flavors: ["herbal", "picante", "cremoso"],
    profile: { picante: 4, umami: 5, acido: 5, dulce: 2, grasa: 4, aroma: 7 },
    timeMin: 40,
    servings: 4,
    difficulty: "media",
    moods: ["ligero", "consuelo"],
    ingredients: [
      { item: "Masa de dosa (arroz y urad dal)", amount: "500 ml", key: "arroz" },
      { item: "Papa", amount: "4", key: "papa" },
      { item: "Mostaza en grano y cúrcuma", amount: "1 cdita c/u", key: "comino" },
      { item: "Hoja de curry y chile", amount: "al ras", key: "chile" },
      { item: "Cebolla", amount: "1", key: "cebolla" },
      { item: "Chutney de coco", amount: "para servir", key: "coco" },
      { item: "Sambar", amount: "para servir", key: "lenteja" },
    ],
    steps: [
      "Palya: sofríe mostaza, hoja de curry, chile, cebolla. Papa, cúrcuma, un chapuzón de agua.",
      "Plancha muy caliente. Extiende la masa en círculo fino. Aceite en los bordes.",
      "Cuando cruje, relleno, dobla.",
      "Chutney y sambar. El dosa se come con la mano, rompiendo desde la punta.",
    ],
    story: "El desayuno del sur que cabe en una mesa entera. Fermento, papa y coco: el trío tamil.",
    tip: "Si la masa no se extiende, le falta agua o la plancha está fría. Tiene que silbar.",
    image: "/dishes/masala-dosa.jpg",
    tags: ["india", "desayuno", "fermentado", "papa"],
  },
  {
    slug: "green-curry",
    name: "Curry verde",
    nameLocal: "แกงเขียวหวาน",
    country: "Tailandia",
    city: "Bangkok",
    regionId: "asia-sur",
    flavors: ["picante", "herbal", "cremoso"],
    profile: { picante: 7, umami: 7, acido: 4, dulce: 4, grasa: 7, aroma: 9 },
    timeMin: 35,
    servings: 4,
    difficulty: "fácil",
    moods: ["fiesta", "consuelo"],
    ingredients: [
      { item: "Pasta de curry verde", amount: "3 cdas", key: "chile" },
      { item: "Leche de coco", amount: "400 ml", key: "coco" },
      { item: "Pollo o tofu", amount: "400 g", key: "pollo" },
      { item: "Berenjena thai", amount: "8", key: "berenjena" },
      { item: "Albahaca thai y kaffir", amount: "un manojo", key: "albahaca" },
      { item: "Salsa de pescado y palma", amount: "al ras", key: "pescado" },
      { item: "Chile rojo y arroz jazmín", amount: "para servir", key: "arroz" },
    ],
    steps: [
      "Sofríe la pasta en la crema espesa del coco hasta que el aceite se separe.",
      "Resto del coco, pollo, berenjena. 8 minutos.",
      "Pescado, azúcar de palma, hojas de lima. Albahaca al apagar.",
      "Arroz jazmín. El verde tiene que oler a albahaca, no a lata.",
    ],
    story: "Dulce-picante de Bangkok. El curry más aromático de Tailandia, y el que más miente con el color.",
    tip: "Usa la pasta de buena nevera asiática. La de supermercado occidental sabe a pasta de dientes.",
    image: "/dishes/green-curry.jpg",
    tags: ["tailandia", "curry", "coco", "picante"],
  },
  {
    slug: "chicken-adobo",
    name: "Adobo de pollo",
    nameLocal: "Chicken adobo",
    country: "Filipinas",
    city: "Manila",
    regionId: "asia-sur",
    flavors: ["umami", "citrico", "ahumado"],
    profile: { picante: 3, umami: 9, acido: 7, dulce: 2, grasa: 6, aroma: 6 },
    timeMin: 55,
    servings: 4,
    difficulty: "fácil",
    moods: ["consuelo"],
    ingredients: [
      { item: "Pollo en trozos", amount: "1.2 kg", key: "pollo" },
      { item: "Vinagre de caña", amount: "120 ml", key: "limon" },
      { item: "Salsa de soya", amount: "80 ml", key: "soya" },
      { item: "Ajo", amount: "8 dientes", key: "ajo" },
      { item: "Hoja de laurel y pimienta en grano", amount: "al ras", key: "pimienta" },
      { item: "Cebolla", amount: "1", key: "cebolla" },
      { item: "Arroz blanco", amount: "para servir", key: "arroz" },
    ],
    steps: [
      "Dora el pollo. Ajo hasta que perfuma, sin quemar.",
      "Soya, vinagre, laurel, pimienta. No remuevas hasta que hierva —el vinagre se pone agresivo.",
      "Tapa 30 minutos. Reduce la salsa al final, destapado.",
      "Arroz para el jugo oscuro. Al día siguiente está más hondo.",
    ],
    story: "El plato que cada familia filipina jura cocinar mejor. Vinagre y soya: conservación hecha fiesta.",
    tip: "No cubras de más con soya. El adobo se equilibra; si se vuelve salmuera, no hay arroz que alcance.",
    image: "/dishes/chicken-adobo.jpg",
    tags: ["filipinas", "pollo", "vinagre", "soya"],
  },
  {
    slug: "hainanese-chicken",
    name: "Pollo hainanés",
    nameLocal: "海南鸡饭",
    country: "Singapur",
    city: "Singapur",
    regionId: "asia-sur",
    flavors: ["umami", "herbal", "fresco"],
    profile: { picante: 3, umami: 8, acido: 4, dulce: 2, grasa: 5, aroma: 7 },
    timeMin: 70,
    servings: 4,
    difficulty: "media",
    moods: ["ligero", "impresionar"],
    ingredients: [
      { item: "Pollo entero", amount: "1.4 kg", key: "pollo" },
      { item: "Arroz jazmín", amount: "400 g", key: "arroz" },
      { item: "Jengibre y ajo", amount: "al ras", key: "jengibre" },
      { item: "Cebollín", amount: "4", key: "cebolla" },
      { item: "Salsa de chile y jengibre", amount: "para servir", key: "chile" },
      { item: "Soya oscura y pepino", amount: "al gusto", key: "soya" },
    ],
    steps: [
      "Sumerge el pollo en agua a 85 °C con jengibre y cebollín. 45 minutos. Hielo.",
      "Sofríe ajo y jengibre en la grasa de la piel. Cocina el arroz con ese aceite y caldo.",
      "Pela, corta. Pepino, soya, chile, jengibre machacado.",
      "La piel tiene que brillar. Si está mate, el hielo tardó.",
    ],
    story: "Hainan viajó a Singapur y se volvió religión. El pollo parece simple: por eso no perdona.",
    tip: "El agua no hierve. Si hierve, la piel se rompe y el plato se vuelve vulgar.",
    image: "/dishes/hainanese-chicken.jpg",
    tags: ["singapur", "pollo", "arroz", "jengibre"],
  },
  {
    slug: "khao-soi",
    name: "Khao soi",
    nameLocal: "ข้าวซอย",
    country: "Tailandia",
    city: "Chiang Mai",
    regionId: "asia-sur",
    flavors: ["picante", "cremoso", "citrico"],
    profile: { picante: 6, umami: 8, acido: 5, dulce: 3, grasa: 7, aroma: 8 },
    timeMin: 45,
    servings: 4,
    difficulty: "media",
    moods: ["consuelo", "impresionar"],
    ingredients: [
      { item: "Fideos de huevo", amount: "400 g", key: "fideos" },
      { item: "Pasta khao soi o curry rojo", amount: "3 cdas", key: "chile" },
      { item: "Leche de coco", amount: "400 ml", key: "coco" },
      { item: "Muslos de pollo", amount: "600 g", key: "pollo" },
      { item: "Mostaza encurtida y chalota", amount: "para servir", key: "cebolla" },
      { item: "Lima y chile frito", amount: "al gusto", key: "limon" },
      { item: "Fideos fritos crujientes", amount: "un nido", key: "fideos" },
    ],
    steps: [
      "Sofríe la pasta en coco espeso. Pollo, resto del coco, un poco de agua. 25 minutos.",
      "Fideos hervidos al bowl. Caldo y pollo.",
      "Nido frito encima. Encurtidos, lima, chalota cruda.",
      "Cada cucharada es crujiente, crema y ácido. El norte de Tailandia en un tazón.",
    ],
    story: "Ruta birmana y yunnanesa en Chiang Mai. El nido frito no es adorno: es la mitad del texto.",
    tip: "El caldo debe ser más espeso que un pho y más líquido que un curry de cuchara.",
    image: "/dishes/khao-soi.jpg",
    tags: ["tailandia", "curry", "fideos", "coco"],
  },
  {
    slug: "som-tam",
    name: "Som tam",
    nameLocal: "ส้มตำ",
    country: "Tailandia",
    city: "Bangkok",
    regionId: "asia-sur",
    flavors: ["picante", "citrico", "fresco"],
    profile: { picante: 8, umami: 6, acido: 8, dulce: 4, grasa: 2, aroma: 7 },
    timeMin: 20,
    servings: 2,
    difficulty: "fácil",
    moods: ["ligero", "fiesta"],
    ingredients: [
      { item: "Papaya verde rallada", amount: "300 g", key: "papaya" },
      { item: "Tomate cherry", amount: "8", key: "tomate" },
      { item: "Judía larga", amount: "6", key: "frijol" },
      { item: "Chile, ajo, cacahuete", amount: "al ras", key: "chile" },
      { item: "Jugo de lima y salsa de pescado", amount: "2 cdas c/u", key: "limon" },
      { item: "Azúcar de palma y camarón seco", amount: "al gusto", key: "camaron" },
    ],
    steps: [
      "En el mortero: ajo, chile, palma. Machaca.",
      "Judía, tomate, camarón seco, cacahuete. Golpes cortos.",
      "Papaya, pescado, lima. Mezcla, no purés.",
      "Se come al momento. A los diez minutos el ácido cocina y se apaga.",
    ],
    story: "Isaan en un mortero. Picante, ácido, dulce, salado: las cuatro esquinas en cada bocado.",
    tip: "La papaya tiene que ser verde y crujiente. La madura es otro plato, y peor.",
    image: "/dishes/som-tam.jpg",
    tags: ["tailandia", "ensalada", "picante", "lima"],
  },
  {
    slug: "satay",
    name: "Satay",
    nameLocal: "Sate ayam",
    country: "Indonesia",
    city: "Yogyakarta",
    regionId: "asia-sur",
    flavors: ["ahumado", "dulce", "picante"],
    profile: { picante: 5, umami: 7, acido: 4, dulce: 5, grasa: 6, aroma: 8 },
    timeMin: 40,
    servings: 4,
    difficulty: "fácil",
    moods: ["fiesta"],
    ingredients: [
      { item: "Pechuga o muslo de pollo", amount: "600 g", key: "pollo" },
      { item: "Cacahuete tostado", amount: "150 g", key: "cacahuete" },
      { item: "Kecap manis", amount: "3 cdas", key: "soya" },
      { item: "Leche de coco", amount: "150 ml", key: "coco" },
      { item: "Chile, ajo, chalota", amount: "al ras", key: "chile" },
      { item: "Lima y pepino", amount: "para servir", key: "limon" },
      { item: "Cúrcuma y comino", amount: "1 cdita", key: "comino" },
    ],
    steps: [
      "Marina el pollo en cúrcuma, kecap, ajo. Ensarta.",
      "Salsa: sofríe chile y ajo, cacahuete molido, coco, kecap, lima.",
      "Parrilla o plancha bien marcada. Pincela kecap.",
      "Pepino, cebolla, salsa. El humo vale más que la carne.",
    ],
    story: "El archipiélago en una varilla. De Java al mundo, con la salsa de cacahuete como pasaporte.",
    tip: "Remoja las brochetas. Si se queman, el pollo sabe a fogata y no a sate.",
    image: "/dishes/satay.jpg",
    tags: ["indonesia", "parrilla", "cacahuete", "calle"],
  },
  {
    slug: "amok-trey",
    name: "Amok trey",
    nameLocal: "អាម៉ុកត្រី",
    country: "Camboya",
    city: "Siem Reap",
    regionId: "asia-sur",
    flavors: ["cremoso", "herbal", "picante"],
    profile: { picante: 4, umami: 7, acido: 3, dulce: 3, grasa: 6, aroma: 8 },
    timeMin: 50,
    servings: 4,
    difficulty: "media",
    moods: ["impresionar", "ligero"],
    ingredients: [
      { item: "Pescado blanco", amount: "500 g", key: "pescado" },
      { item: "Pasta kroeung (lemongrass, galanga, cúrcuma)", amount: "4 cdas", key: "jengibre" },
      { item: "Leche de coco", amount: "300 ml", key: "coco" },
      { item: "Pasta de camarón y chile", amount: "al ras", key: "camaron" },
      { item: "Hoja de kaffir y huevo", amount: "1", key: "huevo" },
      { item: "Hojas de plátano", amount: "para vapor", key: "platano" },
    ],
    steps: [
      "Mezcla kroeung, coco, huevo, pescado en cubos, un toque de palma.",
      "Forma cestas de hoja de plátano. Llena, cubre con un poco de coco espeso.",
      "Vapor 20 minutos hasta que cuaje como mousse.",
      "Chile y kaffir. Se come de la hoja, con arroz.",
    ],
    story: "El plato real de Camboya. El Mekong, el coco y el lemongrass se sientan en una hoja.",
    tip: "El amok cuaja, no hierve. Si sale sopa, le faltó huevo o vapor.",
    image: "/dishes/amok-trey.jpg",
    tags: ["camboya", "pescado", "coco", "vapor"],
  },
  {
    slug: "hummus",
    name: "Hummus",
    nameLocal: "حمص",
    country: "Líbano",
    city: "Beirut",
    regionId: "medio-oriente",
    flavors: ["cremoso", "citrico", "herbal"],
    profile: { picante: 1, umami: 6, acido: 6, dulce: 1, grasa: 6, aroma: 6 },
    timeMin: 20,
    servings: 4,
    difficulty: "fácil",
    moods: ["ligero", "fiesta"],
    ingredients: [
      { item: "Garbanzos cocidos", amount: "400 g", key: "garbanzo" },
      { item: "Tahini", amount: "80 g", key: "cacahuete" },
      { item: "Limón", amount: "2", key: "limon" },
      { item: "Ajo", amount: "1 diente", key: "ajo" },
      { item: "Comino", amount: "1/2 cdita", key: "comino" },
      { item: "Aceite de oliva", amount: "para servir", key: "aceite" },
      { item: "Pan pita", amount: "para servir", key: "trigo" },
    ],
    steps: [
      "Pela los garbanzos si buscas seda. Reserva agua de cocción.",
      "Licúa tahini y limón primero —se aclara. Luego ajo, garbanzo, comino, hielo o agua.",
      "Sal. Unta el plato con el dorso de la cuchara.",
      "Aceite, pimentón, un garbanzo entero. Pan caliente.",
    ],
    story: "Guerra de cunas entre Beirut, Tel Aviv y Damasco. Da igual: el bueno es el que se come el mismo día.",
    tip: "El tahini con el limón primero. Si tiras todo junto, queda pasta de arena.",
    image: "/dishes/hummus.jpg",
    tags: ["libano", "garbanzo", "tahini", "meze"],
  },
  {
    slug: "shawarma",
    name: "Shawarma",
    nameLocal: "شاورما",
    country: "Líbano",
    city: "Beirut",
    regionId: "medio-oriente",
    flavors: ["ahumado", "picante", "cremoso"],
    profile: { picante: 4, umami: 8, acido: 5, dulce: 2, grasa: 6, aroma: 8 },
    timeMin: 60,
    servings: 4,
    difficulty: "fácil",
    moods: ["fiesta"],
    ingredients: [
      { item: "Muslos de pollo", amount: "800 g", key: "pollo" },
      { item: "Yogur", amount: "150 g", key: "yogurt" },
      { item: "Comino, pimentón, cardamomo", amount: "1 cdita c/u", key: "comino" },
      { item: "Ajo y limón", amount: "4 y 1", key: "ajo" },
      { item: "Pan pita", amount: "4", key: "trigo" },
      { item: "Salsa de ajo (toum)", amount: "al gusto", key: "ajo" },
      { item: "Pepinillos y tomate", amount: "al gusto", key: "tomate" },
    ],
    steps: [
      "Marina el pollo en yogur, especias, ajo, limón. Mínimo 2 horas.",
      "Horno 220 °C o plancha. Corta en tiras finas.",
      "Pita tibia, toum, pollo, pepinillo, tomate.",
      "Envuelve y aprieta. El jugo tiene que manchar la muñeca.",
    ],
    story: "El asador vertical que alimenta a medianoche desde Estambul hasta Ciudad del Cabo, pasando por Beirut.",
    tip: "El toum se emulsiona como alioli: ajo, aceite, limón, paciencia. Sin él, es pollo en pan.",
    image: "/dishes/shawarma.jpg",
    tags: ["libano", "pollo", "calle", "especias"],
  },
  {
    slug: "mansaf",
    name: "Mansaf",
    nameLocal: "منسف",
    country: "Jordania",
    city: "Amán",
    regionId: "medio-oriente",
    flavors: ["umami", "cremoso", "herbal"],
    profile: { picante: 1, umami: 9, acido: 4, dulce: 2, grasa: 7, aroma: 7 },
    timeMin: 150,
    servings: 8,
    difficulty: "media",
    moods: ["fiesta", "impresionar"],
    ingredients: [
      { item: "Pierna de cordero", amount: "1.5 kg", key: "cordero" },
      { item: "Jameed o yogur tenso", amount: "500 g", key: "yogurt" },
      { item: "Arroz", amount: "500 g", key: "arroz" },
      { item: "Pan shrak o pita", amount: "4", key: "trigo" },
      { item: "Almendras y piñones", amount: "80 g", key: "cacahuete" },
      { item: "Cardamomo y laurel", amount: "al ras", key: "cardamomo" },
      { item: "Cúrcuma para el arroz", amount: "1 cdita", key: "comino" },
    ],
    steps: [
      "Cocina el cordero con especias hasta que se rinda.",
      "Disuelve el jameed, suma al caldo. No hierva a saltos o se corta.",
      "Arroz con cúrcuma. Platter: pan, arroz, cordero, salsa, frutos secos.",
      "Se come con la mano derecha, haciendo bolas. Es hospitalidad, no ración.",
    ],
    story: "El plato nacional jordano. El jameed —yogur de piel de cabra— es el sabor del desierto hecho fiesta.",
    tip: "Si no hay jameed, yogur griego batido con un toque de sal. No es lo mismo, pero acerca.",
    image: "/dishes/mansaf.jpg",
    tags: ["jordania", "cordero", "yogur", "fiesta"],
  },
  {
    slug: "kibbeh",
    name: "Kibbeh",
    nameLocal: "كبة",
    country: "Siria",
    city: "Alepo",
    regionId: "medio-oriente",
    flavors: ["umami", "herbal", "ahumado"],
    profile: { picante: 3, umami: 8, acido: 2, dulce: 2, grasa: 7, aroma: 7 },
    timeMin: 70,
    servings: 6,
    difficulty: "alta",
    moods: ["fiesta", "impresionar"],
    ingredients: [
      { item: "Bulgur fino", amount: "250 g", key: "trigo" },
      { item: "Cordero magro molido", amount: "500 g", key: "cordero" },
      { item: "Cebolla", amount: "2", key: "cebolla" },
      { item: "Piñones", amount: "50 g", key: "cacahuete" },
      { item: "Canela, allspice, menta", amount: "al ras", key: "comino" },
      { item: "Aceite para freír", amount: "necesario", key: "aceite" },
      { item: "Yogur de menta", amount: "para servir", key: "yogurt" },
    ],
    steps: [
      "Hidratar el bulgur. Amasa con la mitad del cordero, cebolla y especias hasta masa lisa.",
      "Relleno: sofríe el resto del cordero, piñones, especias.",
      "Forma óvalos, hueco, rellena, cierra. Fríe a 170 °C.",
      "Yogur con menta. Se comen de pie, de a tres, discutiendo Alepo contra Beirut.",
    ],
    story: "La joyería de Levante. El crujiente de bulgur y el cordero especiado: técnica de abuela, orgullo de barrio.",
    tip: "Manos mojadas. El kibbeh se agrieta si la masa está seca o el relleno caliente.",
    image: "/dishes/kibbeh.jpg",
    tags: ["siria", "cordero", "frito", "mezze"],
  },
  {
    slug: "spanakopita",
    name: "Espinakopita",
    nameLocal: "Σπανακόπιτα",
    country: "Grecia",
    city: "Atenas",
    regionId: "mediterraneo",
    flavors: ["herbal", "cremoso", "citrico"],
    profile: { picante: 1, umami: 6, acido: 3, dulce: 1, grasa: 7, aroma: 6 },
    timeMin: 70,
    servings: 6,
    difficulty: "media",
    moods: ["ligero", "fiesta"],
    ingredients: [
      { item: "Masa filo", amount: "12 hojas", key: "trigo" },
      { item: "Espinaca", amount: "600 g", key: "espinaca" },
      { item: "Queso feta", amount: "300 g", key: "leche" },
      { item: "Cebolla de verdeo", amount: "4", key: "cebolla" },
      { item: "Eneldo y huevo", amount: "1 manojo y 2", key: "huevo" },
      { item: "Mantequilla o aceite", amount: "80 g", key: "leche" },
      { item: "Limón", amount: "1", key: "limon" },
    ],
    steps: [
      "Marchita la espinaca, escurre bien. Mezcla feta, verdeo, eneldo, huevo.",
      "Capa de filo untada, relleno, más filo. Marca porciones.",
      "Horno 180 °C 40 minutos hasta oro.",
      "Reposa 10 minutos. Un chorro de limón. Se come tibia.",
    ],
    story: "El picnic griego. Filo que se rompe, feta que sala, espinaca que finge ligereza.",
    tip: "Escurre la espinaca como si te fuera la vida. El agua es el enemigo del crujiente.",
    image: "/dishes/spanakopita.jpg",
    tags: ["grecia", "horno", "feta", "espinaca"],
  },
  {
    slug: "pesto-alla-genovese",
    name: "Pesto alla genovese",
    nameLocal: "Trofie al pesto",
    country: "Italia",
    city: "Génova",
    regionId: "mediterraneo",
    flavors: ["herbal", "cremoso", "fresco"],
    profile: { picante: 0, umami: 6, acido: 2, dulce: 1, grasa: 7, aroma: 9 },
    timeMin: 25,
    servings: 4,
    difficulty: "fácil",
    moods: ["ligero", "impresionar"],
    ingredients: [
      { item: "Albahaca genovesa", amount: "80 g", key: "albahaca" },
      { item: "Piñones", amount: "30 g", key: "cacahuete" },
      { item: "Parmesano y pecorino", amount: "40 g c/u", key: "leche" },
      { item: "Ajo", amount: "1 diente", key: "ajo" },
      { item: "Aceite de oliva", amount: "120 ml", key: "aceite" },
      { item: "Trofie o linguine", amount: "400 g", key: "trigo" },
      { item: "Papa y judía verde", amount: "200 g c/u", key: "papa" },
    ],
    steps: [
      "Pesto: albahaca, piñón, ajo, quesos, aceite. Mármol y paciencia, o un procesador a pulsos fríos.",
      "Agua de pasta: papa en cubos, luego judía, luego pasta.",
      "Fuera del fuego, pesto y un cucharón de agua. Nunca saltees el pesto.",
      "El verde tiene que oler a jardín. Si huele a ajo solo, te pasaste.",
    ],
    story: "Liguria en un mortero. La DOP se pelea por la albahaca; tú preocúpate de que no se oxide.",
    tip: "Un cubo de hielo en el procesador evita el pesto oscuro, color de arrepentimiento.",
    image: "/dishes/pesto-alla-genovese.jpg",
    tags: ["liguria", "albahaca", "pasta", "verde"],
  },
  {
    slug: "souvlaki",
    name: "Souvlaki",
    nameLocal: "Σουβλάκι",
    country: "Grecia",
    city: "Atenas",
    regionId: "mediterraneo",
    flavors: ["ahumado", "citrico", "herbal"],
    profile: { picante: 2, umami: 7, acido: 5, dulce: 1, grasa: 5, aroma: 7 },
    timeMin: 40,
    servings: 4,
    difficulty: "fácil",
    moods: ["fiesta", "ligero"],
    ingredients: [
      { item: "Cerdo o pollo en cubos", amount: "700 g", key: "cerdo" },
      { item: "Orégano, ajo, limón", amount: "al ras", key: "limon" },
      { item: "Aceite de oliva", amount: "4 cdas", key: "aceite" },
      { item: "Pita griega", amount: "4", key: "trigo" },
      { item: "Yogur, pepino, ajo (tzatziki)", amount: "al gusto", key: "yogurt" },
      { item: "Tomate y cebolla", amount: "al gusto", key: "tomate" },
    ],
    steps: [
      "Marina la carne 1 hora: limón, orégano, ajo, aceite.",
      "Ensarta y grilla a fuego alto. Marca, no ahúmes de más.",
      "Tzatziki: yogur, pepino rallado escurrido, ajo, eneldo.",
      "Pita, carne, tomate, cebolla, tzatziki, papas. De pie, en la esquina.",
    ],
    story: "El almuerzo ateniense. Varilla, pan y yogur: nada que un turista no entienda y un local no extrañe.",
    tip: "El pepino del tzatziki se sala y se escurre. Si no, es sopa de yogur.",
    image: "/dishes/souvlaki.jpg",
    tags: ["grecia", "parrilla", "cerdo", "calle"],
  },
  {
    slug: "ratatouille",
    name: "Ratatouille",
    nameLocal: "Ratatouille",
    country: "Francia",
    city: "Niza",
    regionId: "mediterraneo",
    flavors: ["herbal", "dulce", "fresco"],
    profile: { picante: 1, umami: 6, acido: 4, dulce: 4, grasa: 5, aroma: 7 },
    timeMin: 70,
    servings: 4,
    difficulty: "fácil",
    moods: ["ligero", "consuelo"],
    ingredients: [
      { item: "Berenjena", amount: "2", key: "berenjena" },
      { item: "Calabacín", amount: "2", key: "calabacin" },
      { item: "Pimiento", amount: "2", key: "pimiento" },
      { item: "Tomate maduro", amount: "4", key: "tomate" },
      { item: "Cebolla y ajo", amount: "1 y 3", key: "cebolla" },
      { item: "Tomillo y albahaca", amount: "al ras", key: "tomillo" },
      { item: "Aceite de oliva", amount: "6 cdas", key: "aceite" },
    ],
    steps: [
      "Saltea cada verdura aparte, en aceite generoso. No las amontones.",
      "Sofríe cebolla, ajo, tomate. Junta todo. Tomillo.",
      "Fuego bajo 30 minutos. Albahaca al final.",
      "Frío o tibio. Pan. Al día siguiente discute menos y sabe más.",
    ],
    story: "Provenza de huerta. No es el milhojas de la película: es un pisto que se sienta al sol.",
    tip: "Cocinar junto desde el inicio da papilla. Cada verdura pide su minuto de sartén.",
    image: "/dishes/ratatouille.jpg",
    tags: ["provenza", "verdura", "verano", "aceite"],
  },
  {
    slug: "schnitzel",
    name: "Schnitzel",
    nameLocal: "Wiener Schnitzel",
    country: "Austria",
    city: "Viena",
    regionId: "europa",
    flavors: ["cremoso", "citrico", "umami"],
    profile: { picante: 0, umami: 6, acido: 4, dulce: 1, grasa: 7, aroma: 3 },
    timeMin: 35,
    servings: 2,
    difficulty: "media",
    moods: ["consuelo", "impresionar"],
    ingredients: [
      { item: "Escalope de ternera", amount: "2 grandes", key: "res" },
      { item: "Harina, huevo, pan rallado", amount: "para empanar", key: "huevo" },
      { item: "Mantequilla clarificada", amount: "para freír", key: "leche" },
      { item: "Limón", amount: "1", key: "limon" },
      { item: "Papa y perejil", amount: "para servir", key: "papa" },
      { item: "Arándano rojo", amount: "opcional", key: "dulce" },
    ],
    steps: [
      "Maja la ternera hasta 4 mm. Sala. Harina, huevo, pan. No aprietes el pan.",
      "Fríe en mantequilla a 170 °C, agitando para que se hinche.",
      "Rejilla, no papel. Limón, papa, ensalada.",
      "Tiene que cubrir el plato. Un schnitzel tímido no es vienés.",
    ],
    story: "Viena se pone seria con esto. Si es cerdo, es Schnitzel; si es ternera, es Wiener. No lo mezcles.",
    tip: "El empanado suelto crea burbujas. Si lo aplastas, queda suela.",
    image: "/dishes/schnitzel.jpg",
    tags: ["austria", "frito", "ternera", "limon"],
  },
  {
    slug: "borscht",
    name: "Borscht",
    nameLocal: "Борщ",
    country: "Ucrania",
    city: "Kyiv",
    regionId: "europa",
    flavors: ["citrico", "umami", "herbal"],
    profile: { picante: 1, umami: 8, acido: 6, dulce: 4, grasa: 4, aroma: 6 },
    timeMin: 100,
    servings: 6,
    difficulty: "fácil",
    moods: ["consuelo"],
    ingredients: [
      { item: "Remolacha", amount: "3", key: "remolacha" },
      { item: "Res para caldo", amount: "500 g", key: "res" },
      { item: "Repollo", amount: "1/4", key: "repollo" },
      { item: "Papa y zanahoria", amount: "3 y 2", key: "papa" },
      { item: "Tomate y vinagre", amount: "2 cdas", key: "tomate" },
      { item: "Eneldo y nata agria", amount: "para servir", key: "leche" },
      { item: "Ajo y laurel", amount: "al ras", key: "ajo" },
    ],
    steps: [
      "Caldo de res 1 hora. Reserva la carne.",
      "Ralla remolacha y zanahoria, sofríe con tomate y un chorro de vinagre para fijar el rojo.",
      "Papa, repollo, sofrito al caldo. 20 minutos. Ajo al final.",
      "Nata, eneldo, pan negro. El rojo tiene que manchar la cuchara.",
    ],
    story: "Patrimonio ucraniano. Cada oblast tiene dogma: ¿con frijol? ¿con champiñón? El vinagre no se discute.",
    tip: "El vinagre o el limón en la remolacha guarda el color. Sin ácido, el borscht se pone ladrillo.",
    image: "/dishes/borscht.jpg",
    tags: ["ucrania", "sopa", "remolacha", "invierno"],
  },
  {
    slug: "swedish-meatballs",
    name: "Albóndigas suecas",
    nameLocal: "Köttbullar",
    country: "Suecia",
    city: "Estocolmo",
    regionId: "europa",
    flavors: ["cremoso", "umami", "dulce"],
    profile: { picante: 1, umami: 7, acido: 4, dulce: 4, grasa: 7, aroma: 5 },
    timeMin: 50,
    servings: 4,
    difficulty: "fácil",
    moods: ["consuelo"],
    ingredients: [
      { item: "Carne de res y cerdo", amount: "400 g y 200 g", key: "res" },
      { item: "Pan remojado en leche", amount: "80 g", key: "leche" },
      { item: "Cebolla", amount: "1", key: "cebolla" },
      { item: "Nuez moscada y pimienta", amount: "al ras", key: "pimienta" },
      { item: "Nata y caldo para salsa", amount: "300 ml", key: "leche" },
      { item: "Mermelada de arándano", amount: "para servir", key: "dulce" },
      { item: "Puré de papa", amount: "para servir", key: "papa" },
    ],
    steps: [
      "Mezcla carnes, pan, cebolla, nuez. Forma bolas pequeñas.",
      "Dora en mantequilla. Reserva.",
      "Salsa: fond, nata, un toque de soya. Vuelve las albóndigas.",
      "Puré, pepino encurtido, lingonberry. El dúo agridulce es ley.",
    ],
    story: "Antes de la tienda de muebles, las köttbullar ya viajaban. El arándano no es postre: es contraste.",
    tip: "Mitad res, mitad cerdo. Solo res queda seco; solo cerdo, blando.",
    image: "/dishes/swedish-meatballs.jpg",
    tags: ["suecia", "albondiga", "nata", "consuelo"],
  },
  {
    slug: "cassoulet",
    name: "Cassoulet",
    nameLocal: "Cassoulet",
    country: "Francia",
    city: "Castelnaudary",
    regionId: "europa",
    flavors: ["umami", "ahumado", "herbal"],
    profile: { picante: 1, umami: 10, acido: 2, dulce: 2, grasa: 8, aroma: 7 },
    timeMin: 240,
    servings: 8,
    difficulty: "alta",
    moods: ["consuelo", "impresionar"],
    ingredients: [
      { item: "Alubias blancas", amount: "500 g", key: "frijol" },
      { item: "Confit de pato", amount: "4 muslos", key: "pollo" },
      { item: "Salchicha de Toulouse", amount: "4", key: "cerdo" },
      { item: "Panceta", amount: "150 g", key: "cerdo" },
      { item: "Cebolla, zanahoria, ajo", amount: "al ras", key: "cebolla" },
      { item: "Tomate y tomillo", amount: "al ras", key: "tomate" },
      { item: "Pan rallado", amount: "para la costra", key: "trigo" },
    ],
    steps: [
      "Remoja las alubias. Cocínalas con hueso y verdura.",
      "Dora salchicha y panceta. En cassole: alubias, carnes, un poco de caldo.",
      "Horno 150 °C 2 horas. Rompe la costra siete veces, dice la leyenda.",
      "Pan rallado al final. Reposa. Se sirve en la cazuela, en el centro.",
    ],
    story: "Guerra santa entre Castelnaudary, Carcasona y Toulouse. El frijol gana siempre.",
    tip: "No es sopa de alubias con adorno. El caldo se reduce hasta que la cuchara se planta.",
    image: "/dishes/cassoulet.jpg",
    tags: ["occitania", "frijol", "pato", "invierno"],
  },
  {
    slug: "bacalhau-bras",
    name: "Bacalhau à Brás",
    nameLocal: "Bacalhau à Brás",
    country: "Portugal",
    city: "Lisboa",
    regionId: "europa",
    flavors: ["umami", "cremoso", "citrico"],
    profile: { picante: 1, umami: 8, acido: 3, dulce: 1, grasa: 7, aroma: 5 },
    timeMin: 40,
    servings: 4,
    difficulty: "fácil",
    moods: ["consuelo", "fiesta"],
    ingredients: [
      { item: "Bacalao desalado", amount: "500 g", key: "pescado" },
      { item: "Papa paja", amount: "300 g", key: "papa" },
      { item: "Cebolla", amount: "2", key: "cebolla" },
      { item: "Huevo", amount: "6", key: "huevo" },
      { item: "Aceituna negra y perejil", amount: "al gusto", key: "aceituna" },
      { item: "Ajo y aceite de oliva", amount: "al ras", key: "ajo" },
    ],
    steps: [
      "Deshebra el bacalao. Sofríe cebolla y ajo hasta cristal.",
      "Suma el bacalao, luego la papa paja.",
      "Huevos batidos. Remueve fuera del fuego hasta crema.",
      "Aceitunas, perejil. Tiene que quedar húmedo, no tortilla seca.",
    ],
    story: "Lisboa tiene mil bacalaos. El Brás es el de diario: paja, huevo, y el mar que Portugal no suelta.",
    tip: "Desala 24 horas, cambiando agua. Un bacalao salado de más no se discute: se tira.",
    image: "/dishes/bacalhau-bras.jpg",
    tags: ["portugal", "bacalao", "huevo", "papa"],
  },
  {
    slug: "tortilla-espanola",
    name: "Tortilla española",
    nameLocal: "Tortilla de patatas",
    country: "España",
    city: "Madrid",
    regionId: "europa",
    flavors: ["cremoso", "umami"],
    profile: { picante: 0, umami: 6, acido: 1, dulce: 2, grasa: 7, aroma: 3 },
    timeMin: 40,
    servings: 4,
    difficulty: "media",
    moods: ["consuelo", "fiesta"],
    ingredients: [
      { item: "Papa", amount: "800 g", key: "papa" },
      { item: "Huevo", amount: "6", key: "huevo" },
      { item: "Cebolla", amount: "1", key: "cebolla" },
      { item: "Aceite de oliva", amount: "250 ml", key: "aceite" },
      { item: "Sal", amount: "al ras", key: "sal" },
    ],
    steps: [
      "Papa en láminas. Confitá en aceite a fuego bajo con cebolla. 20 minutos. Escurre.",
      "Mezcla con huevo. Reposa 5 minutos. La papa bebe.",
      "Sartén caliente, 3 minutos. Voltea con plato. 2 minutos más. El centro jugo.",
      "Bar. Caña. Discusión sobre la cebolla.",
    ],
    story: "La pelea nacional: ¿con cebolla? ¿cuajada? Madrid no resuelve. Tú decide y no te disculpes.",
    tip: "El aceite se reserva para otras tortillas. Tirarlo es pecado venial.",
    image: "/dishes/tortilla-espanola.jpg",
    tags: ["espana", "huevo", "papa", "bar"],
  },
  {
    slug: "fish-and-chips",
    name: "Fish and chips",
    nameLocal: "Fish and chips",
    country: "Reino Unido",
    city: "Londres",
    regionId: "europa",
    flavors: ["citrico", "umami", "fresco"],
    profile: { picante: 1, umami: 6, acido: 5, dulce: 1, grasa: 8, aroma: 3 },
    timeMin: 40,
    servings: 2,
    difficulty: "media",
    moods: ["fiesta", "consuelo"],
    ingredients: [
      { item: "Lomo de bacalao o abadejo", amount: "2", key: "pescado" },
      { item: "Harina y cerveza fría", amount: "para rebozar", key: "trigo" },
      { item: "Papa para chips", amount: "800 g", key: "papa" },
      { item: "Guisante para mushy peas", amount: "200 g", key: "frijol" },
      { item: "Limón y vinagre de malta", amount: "al gusto", key: "limon" },
      { item: "Sal", amount: "al ras", key: "sal" },
    ],
    steps: [
      "Chips: doble fritura, 140 °C y 180 °C.",
      "Rebozado de cerveza helada. Pescado seco, harina, masa. 180 °C hasta globo.",
      "Guisante machacado con menta y mantequilla.",
      "Vinagre, sal, limón. Se come en papel, andando.",
    ],
    story: "Viernes de isla. El rebozado tiene que crujir; el pescado, vapor. Si está aceitoso, el puesto miente.",
    tip: "La masa de cerveza se hace y se usa. Si reposa, pierde el aire y el pez se pone empanada.",
    image: "/dishes/fish-and-chips.jpg",
    tags: ["reino-unido", "frito", "pescado", "pub"],
  },
  {
    slug: "bobotie",
    name: "Bobotie",
    nameLocal: "Bobotie",
    country: "Sudáfrica",
    city: "Ciudad del Cabo",
    regionId: "africa",
    flavors: ["dulce", "ahumado", "cremoso"],
    profile: { picante: 3, umami: 7, acido: 3, dulce: 5, grasa: 6, aroma: 8 },
    timeMin: 80,
    servings: 6,
    difficulty: "fácil",
    moods: ["consuelo", "fiesta"],
    ingredients: [
      { item: "Carne molida de res", amount: "800 g", key: "res" },
      { item: "Pan remojado en leche", amount: "2 rebanadas", key: "leche" },
      { item: "Cebolla y ajo", amount: "2 y 2", key: "cebolla" },
      { item: "Curry en polvo y cúrcuma", amount: "2 cdas", key: "comino" },
      { item: "Pasas y chutney", amount: "al ras", key: "dulce" },
      { item: "Huevo y leche para custard", amount: "2 y 250 ml", key: "huevo" },
      { item: "Hoja de laurel", amount: "3", key: "laurel" },
      { item: "Arroz amarillo", amount: "para servir", key: "arroz" },
    ],
    steps: [
      "Sofríe cebolla, curry, carne. Pan, pasas, chutney, un toque de vinagre.",
      "Al horno en fuente. Cubre con huevo batido en leche y laurel.",
      "180 °C 30 minutos hasta que el custard dore.",
      "Arroz con cúrcuma y más chutney. Dulce-salado del Cabo.",
    ],
    story: "Cocina malaya del Cabo: especias de Batavia, horno de colonia, carne de domingo.",
    tip: "El custard no es quiche: una capa fina. Si está grueso, parece flan y se pelea con el curry.",
    image: "/dishes/bobotie.jpg",
    tags: ["sudafrica", "curry", "horno", "res"],
  },
  {
    slug: "egusi",
    name: "Sopa egusi",
    nameLocal: "Egusi soup",
    country: "Nigeria",
    city: "Lagos",
    regionId: "africa",
    flavors: ["umami", "picante", "herbal"],
    profile: { picante: 6, umami: 8, acido: 2, dulce: 2, grasa: 8, aroma: 7 },
    timeMin: 70,
    servings: 6,
    difficulty: "media",
    moods: ["consuelo", "fiesta"],
    ingredients: [
      { item: "Semilla de melón egusi molida", amount: "250 g", key: "cacahuete" },
      { item: "Aceite de palma", amount: "80 ml", key: "aceite" },
      { item: "Carne de res o chivo", amount: "500 g", key: "res" },
      { item: "Pescado ahumado y stockfish", amount: "al gusto", key: "pescado" },
      { item: "Espinaca o ugu", amount: "300 g", key: "espinaca" },
      { item: "Chile, cebolla, caldo", amount: "al ras", key: "chile" },
      { item: "Fufu o iyan", amount: "para servir", key: "papa" },
    ],
    steps: [
      "Cocina las carnes con cebolla y chile. Reserva el caldo.",
      "Palma caliente. Egusi en bolitas o suelta, hasta que tueste.",
      "Caldo, carnes, pescado ahumado. 20 minutos. Hoja verde al final.",
      "Fufu. Se come con la mano, arrastrando el estofado.",
    ],
    story: "El egusi no es sopa ligera: es semilla, palma y humo. Nigeria en su registro más hondo.",
    tip: "Tuesta el egusi. Crudo sabe a semilla de jardín; tostado, a fiesta.",
    image: "/dishes/egusi.jpg",
    tags: ["nigeria", "estofado", "palma", "semilla"],
  },
  {
    slug: "maafe",
    name: "Maafe",
    nameLocal: "Mafé",
    country: "Malí",
    city: "Bamako",
    regionId: "africa",
    flavors: ["dulce", "picante", "umami"],
    profile: { picante: 4, umami: 8, acido: 3, dulce: 5, grasa: 7, aroma: 7 },
    timeMin: 80,
    servings: 6,
    difficulty: "fácil",
    moods: ["consuelo", "fiesta"],
    ingredients: [
      { item: "Pollo o cordero", amount: "1 kg", key: "pollo" },
      { item: "Mantequilla de cacahuete natural", amount: "200 g", key: "cacahuete" },
      { item: "Pasta de tomate", amount: "3 cdas", key: "tomate" },
      { item: "Cebolla y ajo", amount: "2 y 4", key: "cebolla" },
      { item: "Chile", amount: "1", key: "chile" },
      { item: "Zanahoria y berenjena", amount: "al gusto", key: "zanahoria" },
      { item: "Arroz blanco", amount: "para servir", key: "arroz" },
    ],
    steps: [
      "Dora la carne. Sofríe cebolla, tomate, chile.",
      "Disuelve el cacahuete en agua caliente. Suma. 40 minutos.",
      "Verduras a mitad de cocción. La salsa se espesa y brilla.",
      "Arroz. Un chorro de limón si pide brillo.",
    ],
    story: "De Malí a Senegal y Gambia: el estofado de cacahuete que viaja con los mercados.",
    tip: "Cacahuete sin azúcar. El de merienda infantil convierte el maafe en postre.",
    image: "/dishes/maafe.jpg",
    tags: ["mali", "cacahuete", "estofado", "pollo"],
  },
  {
    slug: "piri-piri-chicken",
    name: "Pollo piri-piri",
    nameLocal: "Frango piri-piri",
    country: "Mozambique",
    city: "Maputo",
    regionId: "africa",
    flavors: ["picante", "citrico", "ahumado"],
    profile: { picante: 8, umami: 7, acido: 6, dulce: 2, grasa: 5, aroma: 8 },
    timeMin: 60,
    servings: 4,
    difficulty: "fácil",
    moods: ["fiesta"],
    ingredients: [
      { item: "Pollo abierto a la espalda", amount: "1.5 kg", key: "pollo" },
      { item: "Chiles piri-piri o bird's eye", amount: "8", key: "chile" },
      { item: "Ajo", amount: "6 dientes", key: "ajo" },
      { item: "Limón y vinagre", amount: "2 y 2 cdas", key: "limon" },
      { item: "Pimentón y orégano", amount: "1 cda", key: "pimenton" },
      { item: "Aceite", amount: "80 ml", key: "aceite" },
    ],
    steps: [
      "Licúa el piri-piri: chile, ajo, limón, vinagre, pimentón, aceite.",
      "Marina el pollo 2 horas. Abre en mariposa para que asemeje.",
      "Parrilla o horno 220 °C. Pincela cada 10 minutos.",
      "Reposa. Más salsa cruda al lado. Dedos rojos, sonrisa igual.",
    ],
    story: "Chilena africana que Portugal llevó a Lisboa y el mundo a la brasa. Maputo lo hace primero.",
    tip: "Mitad de la salsa se cocina; la otra mitad, cruda, al final. Si va toda al fuego, se apaga el chile.",
    image: "/dishes/piri-piri-chicken.jpg",
    tags: ["mozambique", "parrilla", "picante", "pollo"],
  },
  {
    slug: "couscous-royal",
    name: "Cuscús real",
    nameLocal: "كسكس",
    country: "Marruecos",
    city: "Fez",
    regionId: "africa",
    flavors: ["umami", "herbal", "dulce"],
    profile: { picante: 3, umami: 8, acido: 3, dulce: 4, grasa: 5, aroma: 8 },
    timeMin: 120,
    servings: 8,
    difficulty: "media",
    moods: ["fiesta", "impresionar"],
    ingredients: [
      { item: "Cuscús de sémola", amount: "500 g", key: "trigo" },
      { item: "Cordero y pollo", amount: "800 g y 400 g", key: "cordero" },
      { item: "Garbanzos", amount: "250 g", key: "garbanzo" },
      { item: "Zanahoria, calabacín, nabo", amount: "al gusto", key: "zanahoria" },
      { item: "Ras el hanout y azafrán", amount: "al ras", key: "comino" },
      { item: "Cebolla y tomate", amount: "2 y 2", key: "cebolla" },
      { item: "Pasas y almendras", amount: "opcional", key: "dulce" },
    ],
    steps: [
      "Estofado de carnes con cebolla, ras el hanout, azafrán. 1 hora.",
      "Verduras y garbanzos al caldo. El cuscús se vaporiza dos veces sobre el estofado.",
      "Hila con mantequilla y un cucharón de caldo.",
      "Monta el montículo, carnes y verduras alrededor. Harissa al lado.",
    ],
    story: "El viernes magrebí. El vapor del cuscús es el rezo de la cocina: paciencia, sémola, caldo.",
    tip: "No hiervas el cuscús como pasta. Se hincha al vapor; si hierve, se vuelve goma.",
    image: "/dishes/couscous-royal.jpg",
    tags: ["marruecos", "cuscus", "cordero", "viernes"],
  },
];
