import type { FamilyId, Recipe } from "./recipe-types";

export const FAMILIES: {
  id: FamilyId;
  label: string;
  hint: string;
  blurb: string;
  cover: string;
}[] = [
  {
    id: "empanada",
    label: "Empanadas del mundo",
    hint: "Masa, relleno, borde",
    blurb: "De Salta a Osaka, la masa se cierra sobre un secreto. El relleno es el pasaporte.",
    cover: "/dishes/empanadas-criollas.jpg",
  },
  {
    id: "maiz",
    label: "Maíz de ida y vuelta",
    hint: "Nixtamal, comal, hoja",
    blurb: "El maíz viaja como tortilla, arepa, pupusa o humita. Cada país lo cierra a su modo.",
    cover: "/dishes/tacos-al-pastor.jpg",
  },
  {
    id: "caldo",
    label: "Caldos del mundo",
    hint: "Hueso, vapor, cuchara",
    blurb: "Un hueso, agua y tiempo. De Hanoi a Bogotá, el país cabe en un plato hondo.",
    cover: "/dishes/ramen-tonkotsu.jpg",
  },
  {
    id: "estofado",
    label: "Estofados lentos",
    hint: "Tapa, vino, paciencia",
    blurb: "Fuego bajo, tapa entreabierta. El domingo de Francia es el de Padang y el de La Habana.",
    cover: "/dishes/boeuf-bourguignon.jpg",
  },
  {
    id: "arroz",
    label: "Arroces",
    hint: "Grano, socarrat, fiesta",
    blurb: "Un grano que se comporta distinto en cada olla: paella, jollof, biryani, risotto.",
    cover: "/dishes/paella-valenciana.jpg",
  },
  {
    id: "fideo",
    label: "Fideos y pasta",
    hint: "Trigo, wok, queso",
    blurb: "El hilo que une Roma, Bangkok y Chengdu. Se come con palillos, tenedor o cuchara.",
    cover: "/dishes/pad-thai.jpg",
  },
  {
    id: "brasa",
    label: "Brasa y parrilla",
    hint: "Humo, carbón, piel",
    blurb: "El fuego es el restaurante. Jerk, anticucho, koobideh, brisket: el mismo oficio.",
    cover: "/dishes/jerk-chicken.jpg",
  },
  {
    id: "curry",
    label: "Curry y especias",
    hint: "Tadka, coco, ghee",
    blurb: "No es un polvo: es un orden. De Delhi a Durban, el curry cambia de idioma.",
    cover: "/dishes/butter-chicken.jpg",
  },
  {
    id: "frito",
    label: "Fritos y empanados",
    hint: "Aceite, crujiente, limón",
    blurb: "El panko, el pan rallado y el garbanzo se entienden en el aceite caliente.",
    cover: "/dishes/tonkatsu.jpg",
  },
  {
    id: "pan",
    label: "Panes y sándwiches",
    hint: "Masa, calle, relleno",
    blurb: "El pan es plato y cubierto. Bánh mì, pizza, chivito, lahmacun: el mundo en la mano.",
    cover: "/dishes/pizza-margherita.jpg",
  },
  {
    id: "crudo",
    label: "Crudo y fresco",
    hint: "Limón, hierba, cuchillo",
    blurb: "Sin fuego, o casi. El ceviche, el poke y el larb se resuelven en el minuto.",
    cover: "/dishes/ceviche-limeno.jpg",
  },
  {
    id: "desayuno",
    label: "Desayunos del mundo",
    hint: "Huevo, pan, mañana",
    blurb: "El día se decide en el primer plato. Changua, shakshuka, dosa, kaya: cada país despierta distinto.",
    cover: "/dishes/shakshuka.jpg",
  },
  {
    id: "postre",
    label: "Postres",
    hint: "Azúcar, nata, canela",
    blurb: "El final también viaja. Tiramisú, tres leches, knafeh, mango sticky rice: el mundo se endulza.",
    cover: "/dishes/tiramisu.jpg",
  },
  {
    id: "bebida",
    label: "Bebidas",
    hint: "Taza, vaso, ronda",
    blurb: "Café de olla, mate, chai, canelazo. Hay países que se entienden mejor en un vaso.",
    cover: "/dishes/cafe-de-olla.jpg",
  },
];

const SLUG: Record<string, FamilyId> = {
  "empanadas-criollas": "empanada",
  gyoza: "empanada",
  "xiao-long-bao": "empanada",
  pierogi: "empanada",
  pelmeni: "empanada",
  kibbeh: "empanada",
  spanakopita: "empanada",
  brik: "empanada",
  arancini: "empanada",
  takoyaki: "empanada",
  "pani-puri": "empanada",
  "wonton-soup": "caldo",
  "tacos-al-pastor": "maiz",
  pupusas: "maiz",
  arepas: "maiz",
  humitas: "maiz",
  "pastel-de-choclo": "maiz",
  "cochinita-pibil": "maiz",
  "chiles-en-nogada": "maiz",
  "gallo-pinto": "desayuno",
  "pozole-rojo": "caldo",
  "ramen-tonkotsu": "caldo",
  "pho-bo": "caldo",
  "ajiaco-santafereno": "caldo",
  "tom-yum-goong": "caldo",
  sancocho: "caldo",
  gumbo: "caldo",
  "clam-chowder": "caldo",
  borscht: "caldo",
  "caldo-verde": "caldo",
  "niu-rou-mian": "caldo",
  sinigang: "caldo",
  "hot-and-sour-soup": "caldo",
  samgyetang: "caldo",
  "light-soup": "caldo",
  "kimchi-jjigae": "caldo",
  "sundubu-jjigae": "caldo",
  "tom-kha-gai": "caldo",
  egusi: "caldo",
  locro: "estofado",
  "boeuf-bourguignon": "estofado",
  rendang: "estofado",
  "tagine-cordero": "estofado",
  "ropa-vieja": "estofado",
  goulash: "estofado",
  "coq-au-vin": "estofado",
  cassoulet: "estofado",
  "irish-stew": "estofado",
  pepperpot: "estofado",
  "chicken-adobo": "estofado",
  "rabo-encendido": "estofado",
  fesenjan: "estofado",
  "ghormeh-sabzi": "estofado",
  ndole: "estofado",
  maafe: "estofado",
  bigos: "estofado",
  paprikash: "estofado",
  muamba: "estofado",
  "doro-wat": "estofado",
  "mole-poblano": "estofado",
  "seco-de-pollo": "estofado",
  "aji-de-gallina": "estofado",
  rondon: "estofado",
  callaloo: "estofado",
  nikujaga: "estofado",
  sauerbraten: "estofado",
  "shepherds-pie": "estofado",
  stroganoff: "estofado",
  youvetsi: "estofado",
  "lomo-saltado": "estofado",
  feijoada: "estofado",
  "moqueca-baiana": "estofado",
  "mapo-tofu": "estofado",
  "poulet-yassa": "estofado",
  mofongo: "estofado",
  pepian: "estofado",
  "tacu-tacu": "arroz",
  ackee: "estofado",
  "ackee-saltfish": "desayuno",
  "cioppino": "estofado",
  "kare-kare": "estofado",
  ribollita: "estofado",
  choucroute: "estofado",
  shiro: "estofado",
  matoke: "estofado",
  asaro: "estofado",
  "poulet-dg": "estofado",
  zaalouk: "estofado",
  caponata: "estofado",
  ratatouille: "estofado",
  "imam-bayildi": "estofado",
  kleftiko: "estofado",
  moussaka: "estofado",
  "dal-makhani": "estofado",
  "chole-bhature": "frito",
  koshari: "arroz",
  mujadara: "arroz",
  "paella-valenciana": "arroz",
  "jollof-rice": "arroz",
  "chicken-biryani": "arroz",
  "risotto-ai-funghi": "arroz",
  "nasi-goreng": "arroz",
  "nasi-lemak": "desayuno",
  bibimbap: "arroz",
  oyakodon: "arroz",
  jambalaya: "arroz",
  maqluba: "arroz",
  "arroz-con-gandules": "arroz",
  "com-tam": "arroz",
  "yangzhou-fried-rice": "arroz",
  thieboudienne: "arroz",
  waakye: "arroz",
  "hainanese-chicken": "arroz",
  congee: "desayuno",
  dolma: "arroz",
  musakhan: "arroz",
  "pad-thai": "fideo",
  "dan-dan-mian": "fideo",
  japchae: "fideo",
  laksa: "fideo",
  "khao-soi": "fideo",
  jajangmyeon: "fideo",
  "mee-goreng": "fideo",
  vongole: "fideo",
  "spaghetti-carbonara": "fideo",
  "cacio-e-pepe": "fideo",
  "pesto-alla-genovese": "fideo",
  fideua: "fideo",
  "bun-cha": "fideo",
  lasagna: "fideo",
  "pasta-alla-norma": "fideo",
  "gnocchi-sorrentina": "fideo",
  kaesespaetzle: "fideo",
  tteokbokki: "fideo",
  "jerk-chicken": "brasa",
  satay: "brasa",
  souvlaki: "brasa",
  anticuchos: "brasa",
  "carne-asada": "brasa",
  "texas-brisket": "brasa",
  koobideh: "brasa",
  "nyama-choma": "brasa",
  "piri-piri-chicken": "brasa",
  "pato-pekin": "brasa",
  "char-siu": "brasa",
  shawarma: "brasa",
  "shish-taouk": "brasa",
  "siu-yuk": "brasa",
  "butter-chicken": "curry",
  "green-curry": "curry",
  "massaman-curry": "curry",
  "panang-curry": "curry",
  "palak-paneer": "curry",
  "katsu-curry": "curry",
  vindaloo: "curry",
  "bunny-chow": "curry",
  bobotie: "curry",
  falafel: "frito",
  tonkatsu: "frito",
  schnitzel: "frito",
  "fish-and-chips": "frito",
  "nashville-hot-chicken": "frito",
  "milanesa-napolitana": "frito",
  "chicken-fried-steak": "frito",
  "crab-cakes": "frito",
  poutine: "frito",
  "swedish-meatballs": "frito",
  "pizza-margherita": "pan",
  "banh-mi": "pan",
  "sandwich-cubano": "pan",
  "lobster-roll": "pan",
  chivito: "pan",
  francesinha: "pan",
  lahmacun: "pan",
  manakish: "desayuno",
  "pan-con-tomate": "desayuno",
  smorrebrod: "desayuno",
  "masala-dosa": "desayuno",
  "idli-sambar": "desayuno",
  shakshuka: "desayuno",
  "huevos-rancheros": "desayuno",
  "chilaquiles-verdes": "desayuno",
  changua: "desayuno",
  "kaya-toast": "desayuno",
  "ful-medames": "desayuno",
  menemen: "desayuno",
  calentado: "desayuno",
  "huevos-pericos": "desayuno",
  "huevos-motulenos": "desayuno",
  "croque-madame": "desayuno",
  "full-english": "desayuno",
  jianbing: "desayuno",
  "roti-canai": "desayuno",
  "breakfast-burrito": "desayuno",
  "bagels-lox": "desayuno",
  "acai-bowl": "desayuno",
  omurice: "desayuno",
  kaiserschmarrn: "desayuno",
  "waffles-liege": "desayuno",
  "banh-cuon": "desayuno",
  tiramisu: "postre",
  "creme-brulee": "postre",
  "tres-leches": "postre",
  alfajores: "postre",
  baklava: "postre",
  "mango-sticky-rice": "postre",
  churros: "postre",
  "pastel-de-nata": "postre",
  knafeh: "postre",
  "arroz-con-leche": "postre",
  "panna-cotta": "postre",
  cannoli: "postre",
  "sacher-torte": "postre",
  "sticky-toffee": "postre",
  "cheesecake-ny": "postre",
  brigadeiros: "postre",
  picarones: "postre",
  "flan-napolitano": "postre",
  "halo-halo": "postre",
  daifuku: "postre",
  "gulab-jamun": "postre",
  chocotorta: "postre",
  bunuelos: "postre",
  "selva-negra": "postre",
  "tarte-citron": "postre",
  milhojas: "postre",
  "suspiro-limeno": "postre",
  kanelbulle: "postre",
  "tarta-santiago": "postre",
  cendol: "postre",
  "cafe-de-olla": "bebida",
  "masala-chai": "bebida",
  mate: "bebida",
  horchata: "bebida",
  "mango-lassi": "bebida",
  "ca-phe-trung": "bebida",
  "pisco-sour": "bebida",
  canelazo: "bebida",
  matcha: "bebida",
  "cafe-turco": "bebida",
  "te-menta": "bebida",
  "thai-iced-tea": "bebida",
  "bubble-tea": "bebida",
  "ca-phe-sua-da": "bebida",
  "agua-de-jamaica": "bebida",
  champurrado: "bebida",
  "chicha-morada": "bebida",
  "agua-de-panela": "bebida",
  "limonada-de-coco": "bebida",
  michelada: "bebida",
  caipirinha: "bebida",
  mojito: "bebida",
  sangria: "bebida",
  "chocolate-a-la-taza": "bebida",
  "teh-tarik": "bebida",
  paloma: "bebida",
  ayran: "bebida",
  negroni: "bebida",
  "irish-coffee": "bebida",
  gluhwein: "bebida",
  doubles: "pan",
  sabich: "pan",
  "beef-wellington": "pan",
  "tortilla-espanola": "pan",
  okonomiyaki: "pan",
  "ceviche-limeno": "crudo",
  "poke-bowl": "crudo",
  kitfo: "crudo",
  gazpacho: "crudo",
  fattoush: "crudo",
  "som-tam": "crudo",
  larb: "crudo",
  "salade-nicoise": "crudo",
  dakos: "crudo",
  hummus: "crudo",
  "couscous-royal": "estofado",
  mansaf: "estofado",
  fondue: "estofado",
  "amok-trey": "estofado",
  "bacalhau-bras": "frito",
};

export function familyOf(slug: string, name: string, tags: string[]): FamilyId {
  const hit = SLUG[slug];
  if (hit) return hit;
  const tagged = FAMILIES.find((f) => tags.includes(f.id));
  if (tagged) return tagged.id;
  const hay = `${slug} ${name} ${tags.join(" ")}`.toLowerCase();
  if (/desayuno|breakfast|changua|shakshuka|dosa|kaya|menemen|chilaquiles/.test(hay)) return "desayuno";
  if (/postre|dessert|tiramisu|knafeh|baklava|churro|alfajor|nata|tres leches/.test(hay)) return "postre";
  if (/bebida|drink|café|cafe |chai|mate|lassi|horchata|canelazo|pisco sour/.test(hay)) return "bebida";
  if (/empanada|dumpling|gyoza|bao|pierogi/.test(hay)) return "empanada";
  if (/taco|arepa|pupusa|maíz|maiz/.test(hay)) return "maiz";
  if (/sopa|caldo|soup|pho|ramen/.test(hay)) return "caldo";
  if (/curry|masala|tandoor/.test(hay)) return "curry";
  if (/pasta|fideo|noodle|spaghetti/.test(hay)) return "fideo";
  if (/parrilla|brasa|asado|jerk|kebab/.test(hay)) return "brasa";
  if (/arroz|rice|risotto|paella/.test(hay)) return "arroz";
  if (/frito|empanado|panko|schnitzel/.test(hay)) return "frito";
  if (/sandwich|pizza|pan |bread/.test(hay)) return "pan";
  if (/ceviche|crudo|ensalada/.test(hay)) return "crudo";
  return "estofado";
}

export function getFamily(id: string) {
  return FAMILIES.find((f) => f.id === id);
}

export function recipesInFamily(recipes: Recipe[], id: FamilyId) {
  return recipes.filter((r) => r.familyId === id);
}

export const COURSE_IDS: FamilyId[] = ["desayuno", "postre", "bebida"];