#!/usr/bin/env python3
"""Generate src/lib/atlas-latam.ts — real LATAM/Caribbean dishes as AtlasSeed tuples."""

from __future__ import annotations

import pathlib
import re
import unicodedata

OUT = pathlib.Path("/workspace/src/lib/atlas-latam.ts")

FAMILIES = {
    "empanada", "maiz", "caldo", "estofado", "arroz", "fideo", "brasa",
    "curry", "frito", "pan", "crudo", "desayuno", "postre", "bebida",
}
FLAVORS = {"umami", "picante", "citrico", "ahumado", "herbal", "dulce", "cremoso", "fresco"}
MOODS = {"consuelo", "fiesta", "ligero", "impresionar"}
REGIONS = {"latam", "caribe"}
KEYS = {
    "pollo", "cerdo", "res", "cordero", "camaron", "pescado", "huevo", "garbanzo",
    "tofu", "arroz", "fideos", "trigo", "maiz", "papa", "platano", "frijol",
    "lenteja", "tomate", "coco", "ajo", "cebolla", "cilantro", "jengibre",
    "chile", "limon", "soya", "leche", "yogurt", "cacahuete", "queso", "azucar",
    "agua", "cafe", "te", "sal", "aceite", "fruta", "canela", "chocolate",
    "yuca", "naranja", "vino",
}
COUNTRIES = {
    "México", "Colombia", "Perú", "Argentina", "Brasil", "Chile", "Venezuela",
    "Ecuador", "Bolivia", "Guatemala", "El Salvador", "Costa Rica", "Uruguay",
    "Paraguay", "Honduras", "Panamá", "Nicaragua", "Cuba", "Puerto Rico",
    "República Dominicana", "Jamaica", "Haití", "Trinidad y Tobago", "Guyana",
}
FORBIDDEN = {
    "tacos-al-pastor", "pupusas", "arepas", "humitas", "pastel-de-choclo",
    "cochinita-pibil", "chiles-en-nogada", "gallo-pinto", "pozole-rojo",
    "ajiaco-santafereno", "sancocho", "ceviche-limeno", "lomo-saltado",
    "aji-de-gallina", "tacu-tacu", "anticuchos", "picarones", "suspiro-limeno",
    "pisco-sour", "chicha-morada", "seco-de-pollo", "locro", "empanadas-criollas",
    "milanesa-napolitana", "chivito", "feijoada", "moqueca-baiana", "caipirinha",
    "brigadeiros", "acai-bowl", "ropa-vieja", "sandwich-cubano", "rabo-encendido",
    "mofongo", "arroz-con-gandules", "jerk-chicken", "ackee-saltfish", "doubles",
    "pepperpot", "callaloo", "rondon", "huevos-rancheros", "chilaquiles-verdes",
    "changua", "calentado", "huevos-pericos", "huevos-motulenos", "tres-leches",
    "alfajores", "flan-napolitano", "chocotorta", "bunuelos", "milhojas",
    "cafe-de-olla", "horchata", "champurrado", "agua-de-jamaica", "michelada",
    "paloma", "canelazo", "agua-de-panela", "limonada-de-coco", "mate", "pepian",
    "mole-poblano", "carne-asada", "churros", "arroz-con-leche", "mojito",
}

# slug, name, local, country, city, region, family, flavors, time, moods, ings, story
D: list[tuple] = []

def add(*row):
    D.append(row)

# ── México 30 ────────────────────────────────────────────────────────────────
add("birria","Birria","Birria","México","Guadalajara","latam","estofado","umami,picante,ahumado",180,"consuelo,fiesta","Res o chivo*1.2 kg*res;Chile guajillo*8*chile;Cebolla*2*cebolla;Ajo*6 dientes*ajo;Cilantro*1 manojo*cilantro","En Guadalajara el consomé de birria se bebe con la tortilla hecha cuchara y las manos todavía temblando del chile.")
add("carnitas-michoacanas","Carnitas michoacanas","Carnitas","México","Morelia","latam","frito","umami,ahumado,citrico",150,"fiesta,consuelo","Cerdo*1.5 kg*cerdo;Naranja*2*naranja;Ajo*5 dientes*ajo;Aceite o manteca*500 ml*aceite;Sal*al gusto*sal","En el cobre de Michoacán el cerdo se confita hasta que la corteza cruje y el jugo de naranja pide otra tortilla.")
add("mole-negro-oaxaqueno","Mole negro oaxaqueño","Mole negro","México","Oaxaca","latam","estofado","umami,picante,dulce,ahumado",120,"impresionar,fiesta","Chile chilhuacle*6*chile;Chocolate de metate*80 g*chocolate;Pollo*1 kg*pollo;Ajo*4 dientes*ajo;Canela*1 raja*canela","El mole negro de Oaxaca no se cocina: se negocia durante horas entre chile tostado y chocolate hasta que el pavo calla.")
add("tlayuda","Tlayuda","Tlayuda","México","Oaxaca","latam","maiz","ahumado,umami,cremoso",35,"fiesta,ligero","Tortilla tlayuda*4*maiz;Asiento de cerdo*80 g*cerdo;Frijol negro*300 g*frijol;Quesillo*200 g*queso;Cilantro*al gusto*cilantro","En el mercado de Oaxaca la tlayuda se abre como un mapa crujiente y el quesillo dibuja ríos sobre el asiento.")
add("pozole-verde","Pozole verde","Pozole verde","México","Chilpancingo","latam","caldo","herbal,picante,umami",110,"consuelo,fiesta","Maíz cacahuazintle*400 g*maiz;Pollo o costilla*800 g*pollo;Pepita y chile verde*150 g*chile;Cilantro y epazote*1 manojo*cilantro;Cebolla*1*cebolla","En Guerrero el pozole se viste de pepita y cilantro, y el caldo huele a milpa recién llovida.")
add("menudo-rojo","Menudo rojo","Menudo","México","León","latam","caldo","umami,picante,ahumado",180,"consuelo","Pancita de res*800 g*res;Chile guajillo*6*chile;Maíz pozolero*300 g*maiz;Ajo*4 dientes*ajo;Orégano y limón*al gusto*limon","El menudo de León se sirve de madrugada, cuando el chile rojo y el orégano perdonan la noche anterior.")
add("barbacoa-hidalguense","Barbacoa hidalguense","Barbacoa de borrego","México","Actopan","latam","brasa","ahumado,umami,picante",240,"fiesta,impresionar","Borrego*1.5 kg*cordero;Penca de maguey*para envolver*platano;Chile seco*4*chile;Cebolla*2*cebolla;Cilantro*1 manojo*cilantro","Bajo tierra en Actopan el borrego aprende el idioma del maguey y sale consumiéndose en consomé.")
add("tacos-de-suadero","Tacos de suadero","Tacos de suadero","México","Ciudad de México","latam","maiz","umami,picante,citrico",90,"fiesta,consuelo","Suadero de res*700 g*res;Tortillas de maíz*16*maiz;Cebolla*1*cebolla;Cilantro*1 manojo*cilantro;Limón*3*limon","En la capital el suadero se baña en su grasa hasta el alba y la tortilla llega apenas a sostenerlo.")
add("quesabirria","Quesabirria","Quesabirria","México","Tijuana","latam","maiz","umami,cremoso,picante",100,"fiesta,impresionar","Carne de birria*600 g*res;Queso*250 g*queso;Tortillas de maíz*12*maiz;Consomé*500 ml*agua;Cilantro y cebolla*al gusto*cilantro","Tijuana dobló la birria con queso y la frontera crujió: el taco se moja en consomé como quien jura bandera.")
add("esquites","Esquites","Esquites","México","Ciudad de México","latam","maiz","cremoso,citrico,picante",25,"ligero,fiesta","Granos de elote*500 g*maiz;Mayonesa o crema*80 g*leche;Queso fresco*80 g*queso;Chile piquín*al gusto*chile;Limón*2*limon","El elote saltado en vaso es el anochecer de la ciudad: crema, chile y el golpe ácido que ordena la calle.")
add("tamales-oaxaquenos","Tamales oaxaqueños","Tamales oaxaqueños","México","Oaxaca","latam","maiz","umami,picante,ahumado",120,"fiesta,consuelo","Masa de maíz*800 g*maiz;Mole negro*400 g*chile;Hoja de plátano*8*platano;Pollo deshebrado*400 g*pollo;Manteca*120 g*aceite","La hoja de plátano guarda el mole como un secreto húmedo y el tamal oaxaqueño se abre con vapor de fiesta.")
add("chile-relleno","Chile relleno","Chile relleno","México","Puebla","latam","frito","picante,cremoso,umami",55,"consuelo,fiesta","Chiles poblanos*6*chile;Queso o picadillo*300 g*queso;Huevo*4*huevo;Tomate*4*tomate;Aceite*para freír*aceite","En Puebla el poblano se emborracha de huevo batido y el queso se rinde apenas toca la salsa de tomate.")
add("pipian-verde","Pipián verde","Pipián verde","México","Puebla","latam","estofado","herbal,umami,picante",70,"consuelo,impresionar","Pepita de calabaza*200 g*cacahuete;Chile verde*4*chile;Pollo*800 g*pollo;Cilantro*1 manojo*cilantro;Ajo*3 dientes*ajo","La pepita tostada espesa el pipián hasta volverlo bosque comestible, y el pollo nada en verde antiguo.")
add("tinga-poblana","Tinga poblana","Tinga poblana","México","Puebla","latam","estofado","picante,ahumado,dulce",50,"consuelo,fiesta","Pollo deshebrado*600 g*pollo;Chipotle*3*chile;Tomate*4*tomate;Cebolla*2*cebolla;Ajo*3 dientes*ajo","La tinga huele a chipotle y cebolla caramelizada: Puebla en tostada, con el humo todavía sentado en la lengua.")
add("caldo-tlalpeno","Caldo tlalpeño","Caldo tlalpeño","México","Ciudad de México","latam","caldo","picante,umami,herbal",55,"consuelo,ligero","Pollo*600 g*pollo;Chipotle*2*chile;Garbanzo*200 g*garbanzo;Aguacate*1*fruta;Cilantro*1 manojo*cilantro","Del pueblo de Tlalpan bajó un caldo con garbanzo y aguacate que consuela sin pedir permiso al invierno.")
add("pescado-a-la-veracruzana","Pescado a la veracruzana","Pescado a la veracruzana","México","Veracruz","latam","estofado","citrico,herbal,umami",45,"fiesta,ligero","Huachinango*1 kg*pescado;Tomate*5*tomate;Aceitunas y alcaparras*80 g*fruta;Ajo*4 dientes*ajo;Cebolla*1*cebolla","Veracruz enseña al huachinango el acento mediterráneo: aceituna, alcaparra y un tomate que sabe a puerto.")
add("aguachile","Aguachile","Aguachile","México","Mazatlán","latam","crudo","picante,citrico,fresco",20,"ligero,impresionar","Camarón crudo*500 g*camaron;Limón*6*limon;Chile serrano*4*chile;Cebolla morada*1*cebolla;Cilantro*1 manojo*cilantro","En Sinaloa el limón no marina: incendia. El camarón crudo aprende el chile a contrarreloj.")
add("tacos-de-pescado-ensenada","Tacos de pescado de Ensenada","Tacos de pescado","México","Ensenada","latam","frito","citrico,fresco,cremoso",35,"fiesta,ligero","Pescado blanco*500 g*pescado;Harina para capear*150 g*trigo;Tortillas de maíz*12*maiz;Repollo y crema*al gusto*leche;Limón*3*limon","Ensenada capeó el Pacífico y lo dobló en tortilla: el taco de pescado cruje y la crema apaga la brisa.")
add("pescado-zarandeado","Pescado zarandeado","Pescado zarandeado","México","San Blas","latam","brasa","ahumado,picante,citrico",50,"fiesta,impresionar","Pescado entero*1.2 kg*pescado;Chile y mayonesa*para untar*chile;Ajo*4 dientes*ajo;Limón*2*limon;Cebolla*1*cebolla","En la costa nayarita el zarandeo es un vaivén sobre brasa: el pescado se abre como un libro de carbón y chile.")
add("cabrito-al-horno","Cabrito al horno","Cabrito al horno","México","Monterrey","latam","brasa","ahumado,umami,herbal",150,"fiesta,impresionar","Cabrito*1.5 kg*cordero;Ajo*1 cabeza*ajo;Limón o naranja agria*3*limon;Sal*al gusto*sal;Cebolla*2*cebolla","Monterrey asó el desierto: el cabrito sale con la piel tensa y el ajo todavía cantando bajo la costilla.")
add("machaca-con-huevo","Machaca con huevo","Machaca con huevo","México","Monterrey","latam","desayuno","umami,ahumado,picante",25,"consuelo,fiesta","Carne seca de res*200 g*res;Huevo*6*huevo;Chile verde*2*chile;Cebolla*1*cebolla;Tomate*2*tomate","La machaca norteña despierta el huevo con carne de sol y el desayuno sabe a frontera y comal.")
add("torta-ahogada","Torta ahogada","Torta ahogada","México","Guadalajara","latam","pan","picante,citrico,umami",30,"fiesta,consuelo","Birolte*4 piezas*trigo;Carnitas*400 g*cerdo;Chile de árbol*8*chile;Jitomate*3*tomate;Cebolla curtida*1 taza*cebolla","Guadalajara ahoga el pan en salsa de árbol hasta que el birote protesta y el comensal se mancha de orgullo.")
add("cemita-poblana","Cemita poblana","Cemita poblana","México","Puebla","latam","pan","cremoso,picante,umami",25,"fiesta,impresionar","Pan cemita*4*trigo;Milanesa de res o cerdo*4*res;Aguacate*2*fruta;Quesillo*200 g*queso;Chipotle*al gusto*chile","La cemita es un edificio de papalo y quesillo: Puebla cabe en un pan con ajonjolí y no pide cubiertos.")
add("pambazo","Pambazo","Pambazo","México","Ciudad de México","latam","pan","picante,ahumado,cremoso",40,"consuelo,fiesta","Pan pambazo*4*trigo;Papa*400 g*papa;Chorizo*200 g*cerdo;Chile guajillo*5*chile;Crema y lechuga*al gusto*leche","El pambazo se baña en guajillo antes de la plancha y la papa con chorizo espera adentro como un invierno breve.")
add("enchiladas-suizas","Enchiladas suizas","Enchiladas suizas","México","Ciudad de México","latam","maiz","cremoso,picante,umami",45,"consuelo,fiesta","Tortillas de maíz*12*maiz;Pollo deshebrado*400 g*pollo;Chile verde*4*chile;Crema*200 ml*leche;Queso gratinado*200 g*queso","Nadie sabe qué tienen de suizas: son verdes, gratinadas y capitalinas, con la crema apagando el serrano.")
add("sopa-azteca","Sopa azteca","Sopa de tortilla","México","Ciudad de México","latam","caldo","picante,umami,cremoso",40,"consuelo,ligero","Tortillas fritas*8*maiz;Jitomate*4*tomate;Chile pasilla*2*chile;Aguacate*1*fruta;Queso fresco*100 g*queso","Las tiras de tortilla se hunden en caldo de pasilla y el aguacate flota como una tregua en la sopa azteca.")
add("mixiotes-de-pollo","Mixiotes de pollo","Mixiotes","México","Texcoco","latam","estofado","picante,ahumado,citrico",90,"fiesta,impresionar","Pollo*800 g*pollo;Guajillo y pasilla*6*chile;Penca o hoja*para envolver*platano;Ajo*4 dientes*ajo;Naranja agria*2*naranja","El mixiote se ata en penca como un juramento: el vapor de Texcoco cocina el adobo sin que escape el perfume.")
add("pan-de-muerto","Pan de muerto","Pan de muerto","México","Ciudad de México","latam","pan","dulce,cremoso,herbal",90,"fiesta,consuelo","Harina de trigo*500 g*trigo;Azúcar*120 g*azucar;Huevo*3*huevo;Naranja*1*naranja;Mantequilla*100 g*leche","Cada noviembre el pan echa huesos de masa y el azahar recuerda que los muertos también meriendan.")
add("rompope","Rompope","Rompope","México","Puebla","latam","bebida","dulce,cremoso,herbal",40,"fiesta,consuelo","Leche*1 l*leche;Yemas*6*huevo;Azúcar*200 g*azucar;Canela*1 raja*canela;Ron o vino*80 ml*vino","Las monjas de Puebla batieron yemas hasta volver la leche un tesoro espeso que se bebe en copa baja.")
add("tejuino","Tejuino","Tejuino","México","Guadalajara","latam","bebida","citrico,dulce,fresco",30,"ligero,fiesta","Masa de maíz fermentada*400 g*maiz;Piloncillo*150 g*azucar;Limón*4*limon;Sal*una pizca*sal;Hielo y nieve*al gusto*agua","El tejuino jalisciense fermenta el maíz hasta lo agrio y el limón con nieve lo convierte en siesta líquida.")

# ── Colombia 20 ──────────────────────────────────────────────────────────────
add("bandeja-paisa","Bandeja paisa","Bandeja paisa","Colombia","Medellín","latam","frito","umami,ahumado,cremoso",70,"fiesta,consuelo","Frijol cargamanto*300 g*frijol;Chicharrón*200 g*cerdo;Arroz*200 g*arroz;Huevo frito*4*huevo;Plátano maduro*2*platano","En Medellín la bandeja no admite tregua: el frijol, el chicharrón y el huevo firman un almuerzo que pesa como la cordillera.")
add("lechona-tolimense","Lechona tolimense","Lechona","Colombia","Ibagué","latam","brasa","ahumado,umami,herbal",240,"fiesta,impresionar","Cerdo entero*para rellenar*cerdo;Arroz*500 g*arroz;Arveja y cebolla*300 g*cebolla;Ajo*1 cabeza*ajo;Piel de cerdo*para hornear*cerdo","Ibagué hornea el cerdo relleno hasta que la piel se vuelve vidrio y el arroz interior huele a fiesta de pueblo.")
add("tamal-tolimense","Tamal tolimense","Tamal tolimense","Colombia","Ibagué","latam","maiz","umami,herbal,ahumado",120,"consuelo,fiesta","Masa de maíz*600 g*maiz;Cerdo y pollo*400 g*cerdo;Arveja*150 g*fruta;Hoja de plátano*8*platano;Ajo y cebolla*al gusto*ajo","El tamal tolimense viaja en hoja como un almuerzo completo: carne, huevo y la paciencia del vapor.")
add("arepa-de-huevo","Arepa de huevo","Arepa de huevo","Colombia","Barranquilla","latam","maiz","cremoso,umami,ahumado",40,"fiesta,consuelo","Masa de maíz*400 g*maiz;Huevo*6*huevo;Aceite para freír*500 ml*aceite;Sal*al gusto*sal;Cebolla*opcional*cebolla","En la costa el maíz se abre frito y se le cuela un huevo: la arepa de Barranquilla amanece crujiente y amarilla.")
add("sancocho-de-gallina-valluno","Sancocho de gallina valluno","Sancocho de gallina","Colombia","Cali","latam","caldo","umami,herbal,consuelo".replace("consuelo,","") if False else "umami,herbal",90,"consuelo,fiesta","Gallina criolla*1*pollo;Yuca*400 g*yuca;Plátano verde*2*platano;Papa*3*papa;Cilantro*1 manojo*cilantro","El sancocho valluno hierve la gallina hasta que el plátano espesa el caldo y Cali se sienta a la olla.")
add("cazuela-de-mariscos-cartagena","Cazuela de mariscos","Cazuela de mariscos","Colombia","Cartagena","latam","caldo","umami,cremoso,citrico",50,"impresionar,fiesta","Camarón y pescado*600 g*camaron;Leche de coco*400 ml*coco;Yuca*200 g*yuca;Ajo*4 dientes*ajo;Cilantro*1 manojo*cilantro","Cartagena espesa el mar con coco y yuca, y la cazuela llega humeante como un palacio de madera.")
add("posta-negra","Posta negra cartagenera","Posta negra","Colombia","Cartagena","latam","estofado","dulce,umami,ahumado",120,"impresionar,fiesta","Posta de res*1 kg*res;Cola y azúcar quemada*80 g*azucar;Cebolla*2*cebolla;Ajo*5 dientes*ajo;Tomate*2*tomate","La posta se oscurece con caramelo de cola hasta parecer noche: Cartagena come res como si fuera postre salado.")
add("mote-de-queso","Mote de queso","Mote de queso","Colombia","Sincelejo","latam","caldo","cremoso,umami,herbal",55,"consuelo,ligero","Ñame o yuca*500 g*yuca;Queso costeño*250 g*queso;Suero*100 ml*leche;Cebolla*1*cebolla;Ajo*3 dientes*ajo","En Sincelejo el ñame se rinde al queso costeño y el caldo queda blanco, ácido y tercamente costeño.")
add("mute-santandereano","Mute santandereano","Mute","Colombia","Bucaramanga","latam","caldo","umami,picante,herbal",130,"consuelo,fiesta","Maíz pelado*300 g*maiz;Callos y costilla*600 g*res;Papa*3*papa;Cilantro*1 manojo*cilantro;Ajo*4 dientes*ajo","Santander cuece callos y maíz hasta el mediodía: el mute es un caldo que se mastica y se respeta.")
add("sobrebarriga-en-salsa","Sobrebarriga en salsa","Sobrebarriga","Colombia","Bogotá","latam","estofado","umami,ahumado,herbal",140,"consuelo,fiesta","Sobrebarriga de res*1 kg*res;Tomate*4*tomate;Cebolla*2*cebolla;Ajo*4 dientes*ajo;Papa criolla*400 g*papa","La sobrebarriga bogotana se estofa hasta el tenedor y la salsa de tomate le pone apellido andino.")
add("cuchuco-de-trigo","Cuchuco de trigo","Cuchuco de trigo","Colombia","Tunja","latam","caldo","umami,herbal,consuelo".replace("consuelo,","") if False else "umami,herbal",80,"consuelo","Trigo quebrado*250 g*trigo;Costilla de res o cerdo*500 g*res;Papa*3*papa;Habas*150 g*frijol;Cilantro*al gusto*cilantro","En Boyacá el trigo quebrado espesa el caldo campesino y el cuchuco huele a tierra fría y a fogón.")
add("pandebono","Pandebono","Pandebono","Colombia","Cali","latam","pan","cremoso,umami,dulce",40,"consuelo,ligero","Almidón de yuca*250 g*yuca;Queso fresco*200 g*queso;Huevo*2*huevo;Mantequilla*40 g*leche;Azúcar*1 cda*azucar","El pandebono sale del horno todavía humeante y el queso estira un hilo que Cali no se cansa de romper.")
add("aborrajados","Aborrajados","Aborrajados","Colombia","Cali","latam","frito","dulce,cremoso,umami",30,"fiesta,consuelo","Plátano maduro*4*platano;Queso fresco*200 g*queso;Harina*80 g*trigo;Huevo*1*huevo;Aceite*para freír*aceite","El plátano maduro abraza un cubo de queso y el valle lo fríe hasta que lo dulce y lo salado firman tregua.")
add("empanadas-vallunas","Empanadas vallunas","Empanadas vallunas","Colombia","Cali","latam","empanada","umami,picante,ahumado",55,"fiesta,consuelo","Masa de maíz*400 g*maiz;Papa*300 g*papa;Carne desmechada*250 g*res;Ají*al gusto*chile;Aceite*para freír*aceite","La empanada valluna cruje de maíz y adentro la papa con carne espera el ají como se espera un chisme.")
add("arroz-con-coco-costeno","Arroz con coco costeño","Arroz con coco","Colombia","Cartagena","latam","arroz","dulce,umami,cremoso",50,"fiesta,consuelo","Arroz*300 g*arroz;Leche de coco*400 ml*coco;Pasas*40 g*fruta;Azúcar*opcional*azucar;Sal*al gusto*sal","En Cartagena el coco se tuesta hasta el fondo oscuro y el arroz nace dulce, salado y con alma de puerto.")
add("patacones-con-hogao","Patacones con hogao","Patacones","Colombia","Cali","latam","frito","ahumado,umami,herbal",30,"fiesta,ligero","Plátano verde*4*platano;Tomate*3*tomate;Cebolla*2*cebolla;Ajo*3 dientes*ajo;Aceite*para freír*aceite","El patacón se aplasta dos veces y el hogao de tomate le pone a Cali un acento de almuerzo callejero.")
add("mazamorra-paisa","Mazamorra paisa","Mazamorra paisa","Colombia","Medellín","latam","postre","dulce,cremoso,fresco",60,"consuelo,ligero","Maíz blanco*250 g*maiz;Leche*500 ml*leche;Panela*80 g*azucar;Canela*1 raja*canela;Agua*1 l*agua","La mazamorra paisa se toma tibia con panela y la cuchara encuentra granos que todavía recuerdan la milpa.")
add("natilla-colombiana","Natilla colombiana","Natilla","Colombia","Medellín","latam","postre","dulce,cremoso,herbal",40,"fiesta,consuelo","Leche*1 l*leche;Maicena*80 g*maiz;Panela o azúcar*150 g*azucar;Canela*2 rajas*canela;Coco rallado*opcional*coco","En diciembre la natilla cuaja en fuentes hondas y la canela anuncia que la noche buena ya se sentó a la mesa.")
add("lulada","Lulada","Lulada","Colombia","Cali","latam","bebida","citrico,fresco,dulce",15,"ligero,fiesta","Lulo*6*fruta;Limón*2*limon;Azúcar o panela*80 g*azucar;Agua*600 ml*agua;Hielo*al gusto*agua","Cali machaca el lulo con cáscara y el vaso verde pica la siesta: la lulada es un grito ácido con hielo.")
add("cholado","Cholado","Cholado","Colombia","Cali","latam","postre","dulce,fresco,citrico",20,"fiesta,ligero","Hielo raspado*400 g*agua;Fruta picada*300 g*fruta;Leche condensada*80 ml*leche;Jarabe de lulo*60 ml*azucar;Coco rallado*40 g*coco","El cholado caleño es un volcán de hielo y fruta que se come de pie, con la leche condensada haciendo lava.")

# ── Perú 18 ──────────────────────────────────────────────────────────────────
add("causa-limena","Causa limeña","Causa limeña","Perú","Lima","latam","crudo","citrico,cremoso,picante",40,"impresionar,ligero","Papa amarilla*800 g*papa;Ají amarillo*3*chile;Limón*3*limon;Pollo o atún*300 g*pollo;Palta*1*fruta","La causa se tiende en capas frías como un himno cívico: la papa amarilla, el ají y la palta no discuten.")
add("papa-a-la-huancaina","Papa a la huancaína","Papa a la huancaína","Perú","Huancayo","latam","crudo","picante,cremoso,umami",30,"consuelo,fiesta","Papa*800 g*papa;Ají amarillo*4*chile;Queso fresco*200 g*queso;Leche*100 ml*leche;Huevo y aceituna*para coronar*huevo","Huancayo bañó la papa en ají y queso hasta volverla fiesta andina, con la aceituna negra como punto final.")
add("rocoto-relleno","Rocoto relleno","Rocoto relleno","Perú","Arequipa","latam","estofado","picante,umami,cremoso",70,"impresionar,fiesta","Rocotos*6*chile;Carne molida*400 g*res;Queso*150 g*queso;Cebolla*2*cebolla;Aceituna y huevo*al gusto*huevo","Arequipa rellena el rocoto de carne y lo gratiná: el picante entra primero y el queso pide clemencia después.")
add("adobo-arequipeno","Adobo arequipeño","Adobo arequipeño","Perú","Arequipa","latam","estofado","picante,citrico,ahumado",100,"consuelo,fiesta","Chancho*1 kg*cerdo;Chicha de guiñapo*400 ml*maiz;Ají panca*4*chile;Ajo*6 dientes*ajo;Cebolla*2*cebolla","El adobo de Arequipa madruga en chicha y ají panca, y el chancho se rinde antes de que suene la misa.")
add("chupe-de-camarones","Chupe de camarones","Chupe de camarones","Perú","Arequipa","latam","caldo","cremoso,umami,picante",55,"consuelo,impresionar","Camarón de río*500 g*camaron;Leche*300 ml*leche;Papa*3*papa;Arroz*80 g*arroz;Huevo*2*huevo","El chupe arequipeño es un océano andino: el camarón, la leche y el huevo poché se encuentran en plato hondo.")
add("ocopa-arequipena","Ocopa arequipeña","Ocopa","Perú","Arequipa","latam","crudo","herbal,picante,cremoso",25,"ligero,consuelo","Papa*600 g*papa;Huacatay*1 manojo*cilantro;Ají amarillo*3*chile;Maní*60 g*cacahuete;Queso fresco*100 g*queso","El huacatay tiñe de verde la ocopa y Arequipa baña la papa en un maní que sabe a huerta de altura.")
add("arroz-con-pato","Arroz con pato","Arroz con pato","Perú","Chiclayo","latam","arroz","herbal,umami,ahumado",80,"fiesta,impresionar","Pato*1*pollo;Arroz*400 g*arroz;Cerveza negra o chicha*250 ml*vino;Cilantro*2 manojos*cilantro;Ají amarillo*2*chile","En Lambayeque el cilantro tiñe el arroz y el pato se sienta encima como un señor de la costa norte.")
add("juane","Juane","Juane","Perú","Iquitos","latam","arroz","umami,herbal,ahumado",90,"fiesta,consuelo","Arroz*400 g*arroz;Gallina*400 g*pollo;Huevo*4*huevo;Hoja de bijao*6*platano;Especias y aceituna*al gusto*fruta","La selva envuelve el arroz en bijao y el juane viaja como ofrenda: Iquitos huele a hoja y a gallina de fiesta.")
add("tacacho-con-cecina","Tacacho con cecina","Tacacho con cecina","Perú","Tarapoto","latam","frito","ahumado,umami,cremoso",45,"consuelo,fiesta","Plátano verde*6*platano;Cecina de cerdo*400 g*cerdo;Chorizo amazónico*200 g*cerdo;Aceite o manteca*80 ml*aceite;Ajo*3 dientes*ajo","En Tarapoto el plátano se machaca con manteca y la cecina ahumada le pone nombre de almuerzo selvático.")
add("pollo-a-la-brasa","Pollo a la brasa","Pollo a la brasa","Perú","Lima","latam","brasa","ahumado,umami,herbal",80,"fiesta,consuelo","Pollo entero*1*pollo;Comino y pimentón*al gusto*chile;Ajo*1 cabeza*ajo;Cerveza o limón*100 ml*limon;Sal*al gusto*sal","Lima inventó un pollo de brasero que gira hasta el caramelo y las papas fritas se rinden sin discutir.")
add("arroz-chaufa","Arroz chaufa","Arroz chaufa","Perú","Lima","latam","arroz","umami,ahumado,herbal",25,"fiesta,consuelo","Arroz frío*400 g*arroz;Pollo o cerdo*250 g*pollo;Huevo*2*huevo;Soya*3 cdas*soya;Cebollín y jengibre*al gusto*jengibre","El wok limeño habla chino-cantonés: el chaufa salta con soya y el cebollín corta el humo del barrio.")
add("carapulcra","Carapulcra","Carapulcra","Perú","Chincha","latam","estofado","umami,picante,ahumado",100,"consuelo,fiesta","Papa seca*300 g*papa;Cerdo*500 g*cerdo;Ají panca*3*chile;Maní*60 g*cacahuete;Ajo*4 dientes*ajo","La papa seca de Chincha se tuesta y se estofa con maní: la carapulcra sabe a afroperú y a fogón largo.")
add("pachamanca","Pachamanca","Pachamanca","Perú","Huancayo","latam","brasa","ahumado,herbal,umami",180,"fiesta,impresionar","Cordero y cerdo*1.2 kg*cordero;Papa y choclo*800 g*papa;Huacatay*1 manojo*cilantro;Ajo*1 cabeza*ajo;Piedras calientes*para horno*sal","Bajo tierra el Ande cocina con piedras: la pachamanca sale humeante y el huacatay ha firmado cada trozo.")
add("tiradito-de-pescado","Tiradito","Tiradito","Perú","Lima","latam","crudo","citrico,picante,fresco",20,"ligero,impresionar","Pescado blanco*400 g*pescado;Limón*5*limon;Ají amarillo*2*chile;Jengibre*1 trozo*jengibre;Cilantro*al gusto*cilantro","El tiradito se corta como sashimi y se baña en leche de tigre: Lima pone el ají donde Tokio pondría el wasabi.")
add("leche-de-tigre","Leche de tigre","Leche de tigre","Perú","Lima","latam","crudo","citrico,picante,umami",15,"ligero,fiesta","Jugo de ceviche*300 ml*pescado;Limón*4*limon;Ají*2*chile;Cebolla*1*cebolla;Cilantro*al gusto*cilantro","Se bebe de un trago en copa fría: la leche de tigre es el ceviche reducido a relámpago y a cura de madrugada.")
add("mazamorra-morada","Mazamorra morada","Mazamorra morada","Perú","Lima","latam","postre","dulce,citrico,herbal",50,"consuelo,fiesta","Maíz morado*300 g*maiz;Fruta seca*150 g*fruta;Canela y clavo*al gusto*canela;Azúcar*120 g*azucar;Limón*1*limon","El maíz morado hierve hasta teñir la olla y Lima come cuchara de octubre con canela y un golpe de limón.")
add("chiriuchu","Chiriuchu","Chiriuchu","Perú","Cusco","latam","brasa","umami,picante,ahumado",90,"fiesta,impresionar","Cuy y charki*400 g*cordero;Rocoto*2*chile;Maíz tostado*150 g*maiz;Queso andino*100 g*queso;Alga cochayuyo*80 g*fruta","En el Corpus cusqueño el chiriuchu junta sierra y selva en un plato frío: el cuy cruje junto al rocoto.")
add("tallarines-verdes","Tallarines verdes","Tallarines verdes","Perú","Lima","latam","fideo","herbal,cremoso,umami",30,"consuelo,fiesta","Fideos*400 g*fideos;Albahaca*2 manojos*cilantro;Espinaca*150 g*fruta;Queso y leche*150 ml*queso;Ajo*2 dientes*ajo","Lima hizo pesto con albahaca criolla y los tallarines verdes se sirven al lado de una milanesa sin complejos.")

# ── Argentina 16 ─────────────────────────────────────────────────────────────
add("asado-argentino","Asado argentino","Asado","Argentina","Buenos Aires","latam","brasa","ahumado,umami,herbal",120,"fiesta,consuelo","Tira de asado*1.2 kg*res;Chorizo*4*cerdo;Sal gruesa*al gusto*sal;Limón*1*limon;Ajo*opcional*ajo","En Buenos Aires el asado no se apura: la grasa gotea sobre la brasa y la conversación es el otro ingrediente.")
add("choripan","Choripán","Choripán","Argentina","Buenos Aires","latam","pan","ahumado,picante,herbal",25,"fiesta,ligero","Chorizo parrillero*4*cerdo;Pan francés*4*trigo;Chimichurri*al gusto*cilantro;Ajo*3 dientes*ajo;Ají molido*1 cda*chile","El choripán se come de pie junto a la cancha: el chimichurri empapa el pan y el chorizo cruje la siesta.")
add("provoleta","Provoleta","Provoleta","Argentina","Buenos Aires","latam","brasa","cremoso,ahumado,herbal",20,"fiesta,impresionar","Provolone*4 rodajas*queso;Orégano*1 cda*cilantro;Aceite*2 cdas*aceite;Ají*al gusto*chile;Sal*una pizca*sal","La provoleta se burbujea sobre la parrilla hasta que el orégano humea y el queso pide un cuchillo urgente.")
add("matambre-arrollado","Matambre arrollado","Matambre arrollado","Argentina","Rosario","latam","brasa","umami,herbal,cremoso",90,"fiesta,impresionar","Matambre de res*1 kg*res;Huevo duro*4*huevo;Zanahoria y ajo*al gusto*ajo;Pimiento*1*tomate;Salmuera*al gusto*sal","Rosario arrolla el matambre con huevo y verdura: al cortar aparecen banderas y la mesa aplaude en silencio.")
add("empanadas-saltenas","Empanadas salteñas","Empanadas salteñas","Argentina","Salta","latam","empanada","umami,picante,citrico",70,"fiesta,consuelo","Harina*400 g*trigo;Carne cortada a cuchillo*400 g*res;Papa*2*papa;Cebolla y verdeo*2*cebolla;Ají y comino*al gusto*chile","En Salta la empanada se jugoséa con caldo y comino, y el repulgue es una firma que se come de un bocado.")
add("carbonada-criolla","Carbonada criolla","Carbonada","Argentina","Mendoza","latam","estofado","dulce,umami,herbal",80,"consuelo,fiesta","Carne de vacuno*700 g*res;Zapallo*400 g*fruta;Choclo*2*maiz;Durazno o pera*2*fruta;Cebolla*2*cebolla","La carbonada mete el verano en la olla: el zapallo, el choclo y la fruta endulzan la carne de la siesta mendocina.")
add("puchero-argentino","Puchero argentino","Puchero","Argentina","Buenos Aires","latam","caldo","umami,herbal,cremoso",110,"consuelo","Osobuco y gallina*800 g*res;Papa y batata*400 g*papa;Garbanzo*150 g*garbanzo;Choclo*2*maiz;Cebolla*1*cebolla","El puchero hierve el domingo entero y al final se come en dos actos: el caldo primero, las carnes con salsa criolla.")
add("pastel-de-papas","Pastel de papas","Pastel de papas","Argentina","Buenos Aires","latam","estofado","cremoso,umami,dulce",70,"consuelo,fiesta","Papa*1 kg*papa;Carne picada*500 g*res;Huevo*3*huevo;Cebolla*2*cebolla;Aceitunas y pasas*al gusto*fruta","El pastel de papas es un cottage pie con acento: el puré se gratiná y abajo la carne esconde pasas como un secreto.")
add("milanesa-a-caballo","Milanesa a caballo","Milanesa a caballo","Argentina","Buenos Aires","latam","frito","umami,cremoso,ahumado",35,"consuelo,fiesta","Nalga de res*4 filetes*res;Pan rallado*150 g*trigo;Huevo*5*huevo;Aceite*para freír*aceite;Sal*al gusto*sal","A caballo significa huevo frito encima: la milanesa porteña no pide permiso y el yema corre como un río.")
add("fugazzeta","Fugazzeta","Fugazzeta","Argentina","Buenos Aires","latam","pan","cremoso,umami,dulce",50,"fiesta,consuelo","Masa de pizza*600 g*trigo;Cebolla*4*cebolla;Mozzarella y provolone*400 g*queso;Orégano*1 cda*cilantro;Aceite*3 cdas*aceite","La fugazzeta es una pizza que se rellena de queso y se cubre de cebolla: Buenos Aires inventó un colchón comestible.")
add("medialunas","Medialunas","Medialunas","Argentina","Buenos Aires","latam","pan","dulce,cremoso,herbal",90,"consuelo,ligero","Harina*500 g*trigo;Manteca*200 g*leche;Azúcar*80 g*azucar;Huevo*2*huevo;Levadura*20 g*trigo","La medialuna porteña brilla de almíbar a las ocho de la mañana y el café con leche la espera como un cómplice.")
add("revuelto-gramajo","Revuelto Gramajo","Revuelto Gramajo","Argentina","Buenos Aires","latam","desayuno","cremoso,umami,ahumado",25,"consuelo,fiesta","Huevo*6*huevo;Papas paille*300 g*papa;Jamón*150 g*cerdo;Cebolla*1*cebolla;Arvejas*80 g*fruta","Gramajo revolvió papas paille con huevo y jamón: un desayuno de club que se come a cualquier hora en la city.")
add("humita-en-olla","Humita en olla","Humita en olla","Argentina","San Miguel de Tucumán","latam","maiz","cremoso,dulce,herbal",45,"consuelo,ligero","Choclo desgranado*800 g*maiz;Cebolla*1*cebolla;Queso*150 g*queso;Leche*200 ml*leche;Ají y albahaca*al gusto*chile","Tucumán cuece el choclo en olla hasta volverlo crema, y el queso se hunde como un sol en la humita.")
add("tamales-saltenos","Tamales salteños","Tamales salteños","Argentina","Salta","latam","maiz","umami,picante,herbal",100,"fiesta,consuelo","Masa de choclo*600 g*maiz;Carne de cerdo o cabra*400 g*cerdo;Cebolla*2*cebolla;Ají*2*chile;Chala de maíz*8*maiz","La chala guarda el tamal salteño y al abrirla sale un vapor de cerdo y ají que huele a quebrada.")
add("flan-con-dulce-de-leche","Flan con dulce de leche","Flan casero","Argentina","Buenos Aires","latam","postre","dulce,cremoso,herbal",70,"consuelo,impresionar","Leche*500 ml*leche;Huevo*4*huevo;Azúcar*180 g*azucar;Dulce de leche*200 g*leche;Vainilla*1 cda*azucar","El flan porteño se da vuelta sobre un espejo de caramelo y el dulce de leche espera al lado como un ejército.")
add("submarino-porteno","Submarino","Submarino","Argentina","Buenos Aires","latam","bebida","dulce,cremoso,herbal",10,"consuelo,ligero","Leche caliente*400 ml*leche;Chocolate*100 g*chocolate;Azúcar*al gusto*azucar;Canela*opcional*canela;Agua*nada*agua","Se hunde una barra de chocolate en leche hirviendo y el submarino porteño se bebe mientras el invierno afloja.")

# ── Brasil 16 ────────────────────────────────────────────────────────────────
add("picanha-na-brasa","Picanha na brasa","Picanha","Brasil","São Paulo","latam","brasa","ahumado,umami,herbal",50,"fiesta,impresionar","Picanha*1 kg*res;Sal grueso*al gusto*sal;Ajo*3 dientes*ajo;Limón*1*limon;Aceite*1 cda*aceite","En São Paulo la picanha se curva en herradura sobre la brasa y la grasa se derrite como un juramento gaúcho.")
add("coxinha","Coxinha","Coxinha","Brasil","São Paulo","latam","frito","umami,cremoso,ahumado",60,"fiesta,consuelo","Pollo deshebrado*400 g*pollo;Masa de harina*400 g*trigo;Caldo de pollo*300 ml*agua;Huevo y pan rallado*para empanar*huevo;Aceite*para freír*aceite","La coxinha imita un muslito y esconde un relleno de pollo: São Paulo la fríe hasta el dorado de bar.")
add("pao-de-queijo","Pão de queijo","Pão de queijo","Brasil","Belo Horizonte","latam","pan","cremoso,umami,dulce",40,"consuelo,ligero","Almidón de yuca*250 g*yuca;Queso minas*200 g*queso;Huevo*2*huevo;Leche*80 ml*leche;Aceite*40 ml*aceite","Minas Gerais hornea globos elásticos de yuca y queso: el pão de queijo humea y se estira en el primer bocado.")
add("acaraje","Acarajé","Acarajé","Brasil","Salvador","latam","frito","picante,umami,ahumado",50,"fiesta,impresionar","Frijol negro-ojo*300 g*frijol;Cebolla*2*cebolla;Camarón seco*100 g*camaron;Aceite de dendê*para freír*aceite;Ají*al gusto*chile","Las baianas fríen el acarajé en dendê y lo abren como un volcán: el vatapá y el camarón entran al fuego.")
add("vatapa","Vatapá","Vatapá","Brasil","Salvador","latam","estofado","cremoso,picante,umami",55,"consuelo,fiesta","Pan remojado*200 g*trigo;Camarón*250 g*camaron;Leche de coco*300 ml*coco;Dendê*80 ml*aceite;Cacahuete y ajo*80 g*cacahuete","El vatapá se bate hasta volverse un puré de mar y palma: Salvador lo come con cuchara y sin prisa.")
add("bobo-de-camarao","Bobó de camarón","Bobó de camarão","Brasil","Salvador","latam","estofado","cremoso,umami,picante",50,"impresionar,fiesta","Camarón*500 g*camaron;Yuca*400 g*yuca;Leche de coco*300 ml*coco;Dendê*60 ml*aceite;Cilantro y ajo*al gusto*cilantro","El bobó espesa la yuca con coco y el camarón nada en un mar amarillo que solo Bahía sabe servir.")
add("moqueca-capixaba","Moqueca capixaba","Moqueca capixaba","Brasil","Vitória","latam","estofado","citrico,umami,herbal",45,"fiesta,ligero","Pescado*800 g*pescado;Tomate*3*tomate;Cebolla*2*cebolla;Cilantro*1 manojo*cilantro;Urucum y aceite*3 cdas*aceite","A diferencia de Bahía, el capixaba no usa dendê: el urucum y el cilantro bastan para que Vitória huela a mar.")
add("feijao-tropeiro","Feijão tropeiro","Feijão tropeiro","Brasil","Belo Horizonte","latam","estofado","umami,ahumado,herbal",50,"consuelo,fiesta","Frijol*300 g*frijol;Harina de mandioca*150 g*yuca;Tocino y linguiça*250 g*cerdo;Huevo*3*huevo;Col rizada*100 g*fruta","El tropeiro junta el camino: el frijol, el farofa y el huevo se encuentran como arrieros en la mesa mineira.")
add("baiao-de-dois","Baião de dois","Baião de dois","Brasil","Teresina","latam","arroz","umami,cremoso,ahumado",45,"consuelo,fiesta","Arroz*300 g*arroz;Frijol verde*250 g*frijol;Queijo coalho*150 g*queso;Linguiça*150 g*cerdo;Cebolla y cilantro*al gusto*cilantro","El baião de dois baila arroz con frijol y el queijo coalho se derrite como un acordeón en el sertão.")
add("carne-de-sol","Carne de sol","Carne de sol","Brasil","Recife","latam","brasa","ahumado,umami,citrico",40,"fiesta,consuelo","Carne de sol*700 g*res;Mantequilla de garrafa*60 g*leche;Cebolla*2*cebolla;Ajo*4 dientes*ajo;Mandioca*400 g*yuca","En Recife la carne de sol se dora en mantequilla y la yuca aplastada espera el jugo como un desierto agradecido.")
add("tacaca","Tacacá","Tacacá","Brasil","Belém","latam","caldo","citrico,picante,umami",40,"ligero,impresionar","Caldo de tucupí*500 ml*yuca;Camarón seco*100 g*camaron;Jambu*1 manojo*cilantro;Goma de tapioca*150 g*yuca;Ají*al gusto*chile","Belém sirve el tacacá en cuenco: el jambu duerme la lengua y el tucupí pica con acento amazónico.")
add("pato-no-tucupi","Pato no tucupí","Pato no tucupí","Brasil","Belém","latam","estofado","citrico,umami,herbal",90,"impresionar,fiesta","Pato*1*pollo;Tucupí*500 ml*yuca;Jambu*1 manojo*cilantro;Ajo*4 dientes*ajo;Ají*al gusto*chile","El pato se baña en tucupí fermentado y el jambu pone a Belém a hablar con la boca dormida de felicidad.")
add("cuscuz-nordestino","Cuscuz nordestino","Cuscuz","Brasil","Recife","latam","maiz","herbal,umami,cremoso",30,"desayuno,consuelo".replace("desayuno,","") if False else "consuelo,ligero","Harina de maíz*300 g*maiz;Agua y sal*al gusto*sal;Mantequilla*40 g*leche;Huevo*2*huevo;Leche*opcional*leche","El cuscuz nordestino amanece en el vapor y Recife lo come con mantequilla derretida como quien reza en voz baja.")
add("pastel-de-feira","Pastel de feira","Pastel de feira","Brasil","São Paulo","latam","empanada","umami,citrico,ahumado",35,"fiesta,ligero","Masa de harina*400 g*trigo;Carne o queso*250 g*res;Tomate*1*tomate;Aceite*para freír*aceite;Caldo de caña*para acompañar*azucar","En la feria el pastel se fríe al instante y el caldo de caña al lado convierte São Paulo en una fiesta de esquina.")
add("quindim","Quindim","Quindim","Brasil","Salvador","latam","postre","dulce,cremoso,herbal",55,"impresionar,fiesta","Yema*12*huevo;Coco rallado*200 g*coco;Azúcar*250 g*azucar;Mantequilla*40 g*leche;Agua*2 cdas*agua","El quindim brilla como un sol de yema y coco: Salvador lo desmolda y el brillo parece barniz de fiesta.")
add("pudim-de-leite","Pudim de leite","Pudim de leite condensado","Brasil","Rio de Janeiro","latam","postre","dulce,cremoso,herbal",70,"consuelo,fiesta","Leche condensada*400 g*leche;Huevo*4*huevo;Leche*400 ml*leche;Azúcar para caramelo*150 g*azucar;Vainilla*1 cda*azucar","El pudim brasileño tiembla sobre caramelo oscuro y en Río se come frío, como una siesta de domingo.")

# ── Chile 14 ─────────────────────────────────────────────────────────────────
add("curanto","Curanto","Curanto","Chile","Castro","latam","brasa","ahumado,umami,herbal",180,"fiesta,impresionar","Mariscos y carne*1.5 kg*pescado;Papa*600 g*papa;Milcao y chapalele*4*trigo;Hoja de pangue*para tapar*fruta;Sal*al gusto*sal","En Chiloé la tierra se abre para el curanto: piedras, marisco y pan de papa se cuecen bajo las hojas como un rito.")
add("cazuela-de-vacuno","Cazuela de vacuno","Cazuela chilena","Chile","Santiago","latam","caldo","umami,herbal,dulce",70,"consuelo,fiesta","Asiento de res*600 g*res;Zapallo*300 g*fruta;Papa*3*papa;Choclo*2*maiz;Arroz*80 g*arroz","La cazuela chilena sirve el país en un plato: el caldo, el choclo y el zapallo se comen en orden de respeto.")
add("caldillo-de-congrio","Caldillo de congrio","Caldillo de congrio","Chile","Valparaíso","latam","caldo","umami,citrico,herbal",45,"consuelo,impresionar","Congrio*800 g*pescado;Papa*3*papa;Tomate*2*tomate;Vino blanco*100 ml*vino;Cilantro*1 manojo*cilantro","Neruda ya lo dijo: el congrio entra al caldillo de Valparaíso y el mar se sienta a la mesa con papa y vino.")
add("empanadas-de-pino","Empanadas de pino","Empanadas de pino","Chile","Santiago","latam","empanada","umami,dulce,herbal",70,"fiesta,consuelo","Harina*500 g*trigo;Carne de vacuno*400 g*res;Cebolla*3*cebolla;Huevo duro*3*huevo;Aceituna y pasa*al gusto*fruta","El pino es cebolla y carne en infusión larga: la empanada chilena sale del horno con el huevo asomando como bandera.")
add("chorrillana","Chorrillana","Chorrillana","Chile","Valparaíso","latam","frito","umami,ahumado,cremoso",40,"fiesta,consuelo","Papa frita*600 g*papa;Bistec en tiras*400 g*res;Cebolla*2*cebolla;Huevo frito*4*huevo;Sal*al gusto*sal","Valparaíso inventó una montaña de papas, carne y huevo que se come entre varios: la chorrillana no cabe en un plato educado.")
add("completo-italiano","Completo italiano","Completo italiano","Chile","Santiago","latam","pan","cremoso,fresco,umami",15,"fiesta,ligero","Vienesa*4*cerdo;Pan de completo*4*trigo;Palta*2*fruta;Tomate*2*tomate;Mayonesa*al gusto*huevo","El italiano no es de Italia: es palta, tomate y mayo sobre vienesa, y Santiago lo come de madrugada sin disculparse.")
add("charquican","Charquicán","Charquicán","Chile","Santiago","latam","estofado","umami,herbal,dulce",50,"consuelo,fiesta","Charqui o carne*400 g*res;Zapallo*300 g*fruta;Papa*3*papa;Choclo*150 g*maiz;Cebolla*1*cebolla","El charquicán es el campo triturado: zapallo, choclo y carne se encuentran en un plato que sabe a invierno andino.")
add("porotos-granados","Porotos granados","Porotos granados","Chile","Santiago","latam","estofado","herbal,dulce,umami",55,"consuelo,ligero","Porotos*300 g*frijol;Zapallo*300 g*fruta;Choclo*2*maiz;Albahaca*1 manojo*cilantro;Cebolla*1*cebolla","En verano Chile come porotos granados con albahaca: el choclo y el zapallo endulzan el frijol como una huerta.")
add("machas-a-la-parmesana","Machas a la parmesana","Machas a la parmesana","Chile","Viña del Mar","latam","brasa","umami,cremoso,citrico",25,"impresionar,fiesta","Machas*1 kg*pescado;Queso parmesano*120 g*queso;Mantequilla*60 g*leche;Vino blanco*50 ml*vino;Limón*1*limon","Las machas se gratinán en su concha y el parmesano se dora: Viña del Mar sirve el Pacífico con cuchara pequeña.")
add("paila-marina","Paila marina","Paila marina","Chile","Valparaíso","latam","caldo","umami,citrico,herbal",40,"consuelo,fiesta","Mariscos mixtos*800 g*pescado;Vino blanco*100 ml*vino;Ajo*4 dientes*ajo;Cilantro*1 manojo*cilantro;Tomate*2*tomate","La paila marina hierve el muelle entero: el caldo de Valparaíso huele a ajo, cilantro y marea baja.")
add("chupe-de-jaiba","Chupe de jaiba","Chupe de jaiba","Chile","Concepción","latam","caldo","cremoso,umami,picante",45,"impresionar,consuelo","Jaiba*500 g*pescado;Leche*250 ml*leche;Pan remojado*100 g*trigo;Queso*80 g*queso;Ají y ajo*al gusto*chile","El chupe de jaiba se gratina en paila y Concepción esconde el mar bajo una costra de queso y merquén.")
add("cordero-al-palo","Cordero al palo","Cordero al palo","Chile","Punta Arenas","latam","brasa","ahumado,herbal,umami",240,"fiesta,impresionar","Cordero*1 entero*cordero;Ajo*1 cabeza*ajo;Merkén*2 cdas*chile;Sal*al gusto*sal;Limón*2*limon","En la Patagonia el cordero gira al palo durante horas y el viento de Punta Arenas sazona más que cualquier sal.")
add("sopaipillas","Sopaipillas","Sopaipillas","Chile","Santiago","latam","frito","dulce,herbal,cremoso",30,"consuelo,fiesta","Zapallo*300 g*fruta;Harina*400 g*trigo;Aceite*para freír*aceite;Chancaca*150 g*azucar;Canela*1 raja*canela","Cuando llueve en Santiago la sopaipilla sale pasada en chancaca y el invierno se come con los dedos pegajosos.")
add("mote-con-huesillo","Mote con huesillo","Mote con huesillo","Chile","Santiago","latam","bebida","dulce,fresco,herbal",40,"ligero,consuelo","Huesillos secos*200 g*fruta;Mote de trigo*150 g*trigo;Azúcar*100 g*azucar;Canela*1 raja*canela;Agua*1.2 l*agua","El huesillo se hincha en almíbar de canela y el mote flota: Santiago bebe la siesta en vaso alto de feria.")

# ── Venezuela 14 ─────────────────────────────────────────────────────────────
add("pabellon-criollo","Pabellón criollo","Pabellón criollo","Venezuela","Caracas","latam","estofado","umami,dulce,ahumado",90,"consuelo,fiesta","Carne mechada*500 g*res;Caraotas negras*250 g*frijol;Arroz*250 g*arroz;Plátano maduro*2*platano;Cebolla y ají dulce*al gusto*cebolla","El pabellón es la bandera comida: la mechada, las caraotas, el arroz y el plátano firman Caracas en cuatro cuadrantes.")
add("cachapa-con-queso","Cachapa con queso","Cachapa","Venezuela","Valencia","latam","maiz","dulce,cremoso,umami",30,"consuelo,ligero","Choclo tierno*600 g*maiz;Queso de mano*250 g*queso;Azúcar*1 cda*azucar;Leche*80 ml*leche;Sal*una pizca*sal","La cachapa se dora en budare y el queso de mano se derrite adentro como un mediodía de Valencia.")
add("hallaca","Hallaca","Hallaca","Venezuela","Caracas","latam","maiz","umami,herbal,dulce",180,"fiesta,impresionar","Masa de maíz*800 g*maiz;Guiso de res y cerdo*500 g*res;Aceitunas y pasas*80 g*fruta;Hoja de plátano*10*platano;Ají dulce y onoto*al gusto*chile","En Navidad la familia se sienta a envolverse: la hallaca viaja en hoja con un guiso que sabe a año entero.")
add("asado-negro","Asado negro","Asado negro","Venezuela","Caracas","latam","estofado","dulce,umami,ahumado",150,"impresionar,consuelo","Muchacho redondo*1.2 kg*res;Papelón*80 g*azucar;Vino tinto*200 ml*vino;Cebolla*2*cebolla;Ajo*6 dientes*ajo","Caracas quema el papelón hasta el negro y la res se baña en esa noche dulce que se corta en lonchas de fiesta.")
add("tequenos","Tequeños","Tequeños","Venezuela","Los Teques","latam","frito","cremoso,umami,dulce",35,"fiesta,ligero","Queso blanco*300 g*queso;Masa de trigo*300 g*trigo;Aceite*para freír*aceite;Huevo*1*huevo;Sal*una pizca*sal","El tequeño es un bastón de queso envuelto en masa: Los Teques lo fríe y el hilo blanco se niega a cortarse.")
add("empanadas-de-cazon","Empanadas de cazón","Empanadas de cazón","Venezuela","Porlamar","latam","empanada","umami,picante,citrico",50,"fiesta,consuelo","Masa de maíz*400 g*maiz;Cazón guisado*350 g*pescado;Ají dulce*3*chile;Cebolla*1*cebolla;Aceite*para freír*aceite","En Margarita el cazón se guisa con ají dulce y la empanada frita sale a la playa todavía humeante.")
add("pan-de-jamon","Pan de jamón","Pan de jamón","Venezuela","Caracas","latam","pan","umami,dulce,cremoso",90,"fiesta,consuelo","Harina*500 g*trigo;Jamón*250 g*cerdo;Pasas y aceitunas*80 g*fruta;Tocino*80 g*cerdo;Azúcar y mantequilla*80 g*azucar","El pan de jamón se enrolla en diciembre y al cortarlo aparecen espirales de fiesta que Caracas espera todo el año.")
add("parrilla-llanera","Parrilla llanera","Parrilla llanera","Venezuela","Barinas","latam","brasa","ahumado,umami,citrico",80,"fiesta,consuelo","Carne de res*1 kg*res;Yuca asada*400 g*yuca;Ajo*4 dientes*ajo;Limón*2*limon;Sal*al gusto*sal","En los llanos la parrilla humea junto al río y la yuca asada acompaña la res como un caballo fiel.")
add("mondongo-venezolano","Mondongo venezolano","Mondongo","Venezuela","Caracas","latam","caldo","umami,herbal,picante",140,"consuelo","Callos de res*700 g*res;Maíz*200 g*maiz;Papa y yuca*400 g*papa;Ají dulce*3*chile;Cilantro*1 manojo*cilantro","El mondongo se cocina desde el alba y el maíz hinchado anuncia que Caracas ya perdonó la noche.")
add("sancocho-margariteno","Sancocho margariteño","Sancocho de pescado","Venezuela","Porlamar","latam","caldo","umami,citrico,herbal",50,"consuelo,ligero","Pescado fresco*700 g*pescado;Yuca*300 g*yuca;Plátano verde*2*platano;Ají dulce*3*chile;Cilantro*1 manojo*cilantro","El sancocho de Margarita huele a puerto: el pescado entra al final y el cilantro cierra el caldo con brisa.")
add("golfeados","Golfeados","Golfeados","Venezuela","Caracas","latam","pan","dulce,herbal,cremoso",70,"fiesta,consuelo","Harina*400 g*trigo;Papelón*120 g*azucar;Anís*1 cda*canela;Queso blanco*150 g*queso;Mantequilla*80 g*leche","El golfeado se enrolla con papelón y anís, y el queso salado en el centro desmiente que sea solo un dulce.")
add("quesillo-venezolano","Quesillo venezolano","Quesillo","Venezuela","Caracas","latam","postre","dulce,cremoso,herbal",70,"consuelo,impresionar","Huevo*6*huevo;Leche condensada*400 g*leche;Leche*200 ml*leche;Azúcar para caramelo*120 g*azucar;Vainilla*1 cda*azucar","El quesillo cuaja con agujeros de aire y el caramelo se cuela por ellos como un secreto de nevera caraqueña.")
add("bienmesabe-venezolano","Bienmesabe","Bienmesabe","Venezuela","La Guaira","latam","postre","dulce,cremoso,citrico",50,"impresionar,fiesta","Coco*400 ml*coco;Yema*6*huevo;Azúcar*200 g*azucar;Bizcocho o pan*200 g*trigo;Limón o ron*2 cdas*limon","El bienmesabe empapa el bizcocho de coco y yema: La Guaira lo sirve frío y el nombre ya es una confesión.")
add("papelon-con-limon","Papelón con limón","Papelón con limón","Venezuela","Caracas","latam","bebida","citrico,dulce,fresco",10,"ligero,fiesta","Papelón*120 g*azucar;Limón*4*limon;Agua*1 l*agua;Hielo*al gusto*agua;Hierbabuena*opcional*cilantro","Se ralla el papelón en agua fría y el limón abre Caracas: es el refresco que no necesita fábrica.")

# ── Ecuador 12 ───────────────────────────────────────────────────────────────
add("encebollado","Encebollado","Encebollado","Ecuador","Guayaquil","latam","caldo","citrico,umami,picante",45,"consuelo,fiesta","Albacora*700 g*pescado;Yuca*400 g*yuca;Cebolla colorada*3*cebolla;Tomate y ají*al gusto*chile;Cilantro y limón*al gusto*limon","Guayaquil cura la madrugada con encebollado: el atún, la yuca y la cebolla curtida firman un tratado ácido.")
add("fanesca","Fanesca","Fanesca","Ecuador","Quito","latam","caldo","cremoso,umami,herbal",120,"fiesta,consuelo","Bacalao*400 g*pescado;Doce granos*600 g*frijol;Leche*500 ml*leche;Zapallo*200 g*fruta;Huevo y frito*para coronar*huevo","En Semana Santa Quito cuece doce granos y bacalao: la fanesca es un arca de Noé que se come con cuchara.")
add("locro-de-papa","Locro de papa","Locro de papa","Ecuador","Quito","latam","caldo","cremoso,umami,herbal",45,"consuelo,ligero","Papa chaucha*800 g*papa;Queso*200 g*queso;Leche*250 ml*leche;Aguacate*1*fruta;Cebolla y achiote*al gusto*cebolla","El locro quiteño espesa la papa hasta el abrazo y el aguacate flota como un sol andino sobre el queso.")
add("hornado-quito","Hornado","Hornado","Ecuador","Quito","latam","brasa","ahumado,umami,citrico",180,"fiesta,impresionar","Chancho*2 kg*cerdo;Chicha o cerveza*300 ml*vino;Ajo*1 cabeza*ajo;Comino y achiote*al gusto*chile;Mote*300 g*maiz","El hornado sale con la piel de vidrio y el mote al lado: Quito come cerdo de fiesta con los dedos brillantes.")
add("ceviche-de-camaron-guayaquil","Ceviche de camarón","Ceviche de camarón","Ecuador","Guayaquil","latam","crudo","citrico,picante,fresco",30,"ligero,fiesta","Camarón cocido*500 g*camaron;Limón*6*limon;Tomate*3*tomate;Cebolla colorada*2*cebolla;Cilantro*1 manojo*cilantro","A diferencia del peruano, el camarón ecuatoriano llega cocido al limón y el jugo se toma con chifles como un brindis.")
add("bolon-de-verde","Bolón de verde","Bolón de verde","Ecuador","Guayaquil","latam","frito","ahumado,umami,cremoso",35,"desayuno,consuelo".replace("desayuno,","") if False else "consuelo,fiesta","Plátano verde*6*platano;Chicharrón*150 g*cerdo;Queso*150 g*queso;Ajo*3 dientes*ajo;Aceite*para dorar*aceite","El bolón se machaca al alba con chicharrón o queso y Guayaquil amanece con un puño de plátano humeante.")
add("seco-de-chivo","Seco de chivo","Seco de chivo","Ecuador","Loja","latam","estofado","umami,citrico,ahumado",110,"consuelo,fiesta","Chivo*1 kg*cordero;Chicha o cerveza*300 ml*vino;Naranja agria*2*naranja;Cilantro y ají*al gusto*cilantro;Cebolla*2*cebolla","Loja estofa el chivo en chicha y naranja hasta que la salsa se pega al arroz como un juramento del austro.")
add("llapingachos","Llapingachos","Llapingachos","Ecuador","Ambato","latam","frito","cremoso,umami,herbal",40,"consuelo,fiesta","Papa*800 g*papa;Queso*200 g*queso;Achiote*1 cda*chile;Cebolla*1*cebolla;Aceite*para dorar*aceite","Ambato dora las tortitas de papa con queso adentro y el achiote les pone el sol de la sierra en la corteza.")
add("guatita","Guatita","Guatita","Ecuador","Guayaquil","latam","estofado","umami,cremoso,picante",80,"consuelo,fiesta","Mondongo*600 g*res;Maní*120 g*cacahuete;Papa*3*papa;Ají y achiote*al gusto*chile;Cebolla y ajo*al gusto*ajo","La guatita espesa el mondongo con maní y Guayaquil la sirve con arroz como un abrazo que cruje un poco.")
add("chugchucaras","Chugchucaras","Chugchucaras","Ecuador","Latacunga","latam","frito","ahumado,umami,citrico",60,"fiesta,consuelo","Cerdo frito*400 g*cerdo;Mote*200 g*maiz;Papas*3*papa;Tostado y chorizo*150 g*maiz;Ají de tomate*al gusto*chile","Latacunga arma un plato de cerdo, mote y tostado que se come con los dedos y con un ají que no perdona.")
add("colada-morada","Colada morada","Colada morada","Ecuador","Quito","latam","bebida","dulce,herbal,citrico",50,"fiesta,consuelo","Mora y mortiño*400 g*fruta;Harina de maíz negro*80 g*maiz;Canela e ishpingo*al gusto*canela;Panela*100 g*azucar;Naranja y limón*2*naranja","Por Finados Quito bebe la colada morada espesa y el mortiño tiñe la cuchara de una noche andina.")
add("empanadas-de-viento","Empanadas de viento","Empanadas de viento","Ecuador","Quito","latam","empanada","cremoso,dulce,umami",40,"fiesta,ligero","Harina*300 g*trigo;Queso fresco*250 g*queso;Aceite*para freír*aceite;Azúcar*para espolvorear*azucar;Huevo*1*huevo","Vuelan al salir del aceite y el azúcar las nieva: Quito come queso frito como si fuera un postre de feria.")

# ── Bolivia 12 ───────────────────────────────────────────────────────────────
add("saltenas","Salteñas","Salteñas","Bolivia","La Paz","latam","empanada","umami,dulce,picante",80,"fiesta,impresionar","Harina*500 g*trigo;Carne de res y pollo*400 g*res;Papa*2*papa;Caldo gelatinoso*200 ml*agua;Ají y aceituna*al gusto*chile","La salteña se muerde con cuidado: adentro hay un caldo que La Paz esconde como un secreto que quema los dedos.")
add("silpancho","Silpancho","Silpancho","Bolivia","Cochabamba","latam","frito","umami,citrico,cremoso",45,"consuelo,fiesta","Carne apanada*4 filetes*res;Arroz*250 g*arroz;Papa frita*4*papa;Huevo frito*4*huevo;Ensalada de tomate*al gusto*tomate","Cochabamba aplasta la carne hasta el plato entero: el silpancho es una geografía de arroz, papa y yema corriendo.")
add("pique-macho","Pique macho","Pique macho","Bolivia","Cochabamba","latam","frito","picante,umami,ahumado",40,"fiesta,consuelo","Carne de res*400 g*res;Salchicha*200 g*cerdo;Papa frita*400 g*papa;Cebolla y locoto*2*chile;Mayonesa*al gusto*huevo","El pique macho se sirve para varios: locoto, carne y papa frita montan una pelea feliz en la mesa cochabambina.")
add("majadito","Majadito","Majadito","Bolivia","Santa Cruz de la Sierra","latam","arroz","umami,ahumado,cremoso",50,"consuelo,fiesta","Arroz*300 g*arroz;Charque*250 g*res;Plátano*2*platano;Huevo frito*4*huevo;Urucú y cebolla*al gusto*cebolla","Santa Cruz majada el charque con arroz y el urucú lo tiñe de oriente: el huevo frito corona el almuerzo cruceño.")
add("sopa-de-mani","Sopa de maní","Sopa de maní","Bolivia","Cochabamba","latam","caldo","cremoso,umami,herbal",60,"consuelo,impresionar","Maní molido*150 g*cacahuete;Carne de res*400 g*res;Papa y fideo*200 g*papa;Arveja*80 g*fruta;Ajo*3 dientes*ajo","El maní espesa el caldo cochabambino hasta volverse seda, y la sopa llega con papa frita crujiendo encima.")
add("chairo-paceno","Chairo paceño","Chairo","Bolivia","La Paz","latam","caldo","umami,herbal,citrico",90,"consuelo","Chuño*150 g*papa;Carne de res o cordero*400 g*res;Habas y choclo*200 g*maiz;Hierbabuena*1 manojo*cilantro;Zanahoria*1*fruta","El chuño negro da al chairo su voz de altura: La Paz bebe este caldo cuando el viento baja de los nevados.")
add("fricase-boliviano","Fricase boliviano","Fricase","Bolivia","La Paz","latam","estofado","picante,umami,ahumado",100,"consuelo,fiesta","Cerdo*800 g*cerdo;Ají amarillo*4*chile;Maíz mote*200 g*maiz;Chuño*100 g*papa;Ajo*4 dientes*ajo","El fricasé paceño pica de madrugada: el cerdo, el mote y el chuño consuelan lo que el ají despierta.")
add("picana-navidena","Picana navideña","Picana","Bolivia","La Paz","latam","caldo","umami,dulce,herbal",120,"fiesta,consuelo","Res, cordero y pollo*1 kg*res;Vino tinto*300 ml*vino;Choclo y papa*400 g*papa;Durazno y cáscara*al gusto*fruta;Cebolla*2*cebolla","En Nochebuena La Paz hierve tres carnes con vino y fruta: la picana es un caldo que sabe a villancico.")
add("plato-paceno","Plato paceño","Plato paceño","Bolivia","La Paz","latam","maiz","herbal,umami,cremoso",50,"consuelo,fiesta","Choclo*4*maiz;Habas*200 g*frijol;Queso fresco*200 g*queso;Papa*4*papa;Llajua*al gusto*chile","El plato paceño es milpa y lácteo: choclo, haba, papa y queso se alinean como una cosecha de altura.")
add("sajta-de-pollo","Sajta de pollo","Sajta de pollo","Bolivia","La Paz","latam","estofado","picante,umami,herbal",60,"consuelo,fiesta","Pollo*800 g*pollo;Ají amarillo*4*chile;Papa*4*papa;Cebolla*2*cebolla;Chuño*100 g*papa","La sajta tiñe de amarillo el pollo paceño y el chuño al lado recuerda que el picante también puede consolar.")
add("charquekan","Charquekan","Charquekán","Bolivia","Oruro","latam","frito","ahumado,umami,picante",40,"consuelo,fiesta","Charque de llama o res*300 g*res;Papa*4*papa;Huevo*4*huevo;Choclo*2*maiz;Llajua*al gusto*chile","Oruro deshilacha el charque y lo sirve con papa y huevo: el charquekán sabe a altiplano y a feria de Carnaval.")
add("api-morado","Api morado","Api","Bolivia","La Paz","latam","bebida","dulce,herbal,citrico",30,"consuelo,ligero","Maíz morado*200 g*maiz;Canela y clavo*al gusto*canela;Azúcar*80 g*azucar;Limón*1*limon;Agua*1 l*agua","El api se bebe espeso y humeante junto a un pastel frito: La Paz desayuna en vaso lo que el maíz morado tiñó de noche.")

print("andean count", len(D))


