#!/usr/bin/env python3
"""Generate src/lib/atlas-asia.ts from curated real-world dishes."""
from __future__ import annotations

import json
import re
from collections import Counter
from pathlib import Path

# slug, name, local, country, city, region, family, flavors, time, moods, ings, story
DISHES: list[tuple] = []

# ---------------------------------------------------------------------------
# China (30)
# ---------------------------------------------------------------------------
DISHES += [
    ("shengjianbao", "Shengjianbao", "生煎包", "China", "Shanghai", "asia-este", "empanada", "umami,ahumado", 35, "consuelo,fiesta",
     "Cerdo picado*300 g*cerdo;Masa de trigo*400 g*trigo;Jengibre*20 g*jengibre;Salsa de soya*2 cdas*soya;Cebollín*1 manojo*cebolla",
     "En los callejones de Shanghai el shengjianbao estalla en caldo y enseña que el desayuno también puede ser un secreto que quema los dedos."),
    ("har-gow", "Har gow", "虾饺", "China", "Guangzhou", "asia-este", "empanada", "umami,fresco", 50, "impresionar,ligero",
     "Camarón*300 g*camaron;Masa de trigo*250 g*trigo;Jengibre*10 g*jengibre;Aceite de sésamo*1 cda*aceite",
     "Cantón pliega el mar en una piel translúcida: el har gow no se muerde, se adivina."),
    ("siu-mai", "Siu mai", "烧卖", "China", "Guangzhou", "asia-este", "empanada", "umami", 45, "fiesta,consuelo",
     "Cerdo picado*250 g*cerdo;Camarón*100 g*camaron;Jengibre*1 trozo*jengibre;Soya*1 cda*soya",
     "Abiertos como copas, los siu mai de Guangzhou no se cierran: el vapor es su tapa y el yum cha su hora."),
    ("jiaozi-shui", "Jiaozi al agua", "水饺", "China", "Harbin", "asia-este", "empanada", "umami,herbal", 50, "consuelo,fiesta",
     "Cerdo*400 g*cerdo;Repollo y cebollín*200 g*cebolla;Jengibre*15 g*jengibre;Masa de trigo*400 g*trigo",
     "En Harbin el invierno se responde con jiaozi que flotan como barcas: cada pliegue es un voto de año nuevo."),
    ("rou-jia-mo", "Roujiamo", "肉夹馍", "China", "Xi'an", "asia-este", "pan", "umami,ahumado", 50, "fiesta,consuelo",
     "Cerdo estofado*400 g*cerdo;Pan mo*4 piezas*trigo;Cilantro*un manojo*cilantro;Chile*al gusto*chile",
     "Xi'an inventó el sándwich antes de llamarlo así: el roujiamo es carne lenta dentro de un pan que cruje a la Ruta de la Seda."),
    ("cong-you-bing", "Panqueque de cebollín", "葱油饼", "China", "Shanghai", "asia-este", "pan", "umami,ahumado", 25, "consuelo,ligero",
     "Harina*300 g*trigo;Cebollín*2 manojos*cebolla;Aceite*4 cdas*aceite;Sal*al gusto*sal",
     "Las capas del cong you bing crujen como un periódico doblado: Shanghai desayuna aceite, cebollín y prisa."),
    ("zha-jiang-mian", "Zhajiangmian", "炸酱面", "China", "Beijing", "asia-este", "fideo", "umami,ahumado", 40, "consuelo",
     "Fideos de trigo*400 g*fideos;Cerdo picado*250 g*cerdo;Pasta de soya*4 cdas*soya;Cebollín*1 manojo*cebolla",
     "Pekín no pide caldo: el zhajiangmian se viste de salsa frita y pepino, y el verano cabe en un tazón."),
    ("lamian-lanzhou", "Lamian de Lanzhou", "兰州拉面", "China", "Lanzhou", "asia-este", "fideo", "umami,herbal", 90, "consuelo",
     "Fideos estirados*400 g*fideos;Hueso de res*1 kg*res;Cilantro*un manojo*cilantro;Chile rojo*2 cdas*chile;Ajo*4 dientes*ajo",
     "En Lanzhou la mano estira la masa hasta que el trigo se vuelve hilo y el caldo de res, una fe clara."),
    ("biangbiang-mian", "Biangbiang mian", "油泼扯面", "China", "Xi'an", "asia-este", "fideo", "picante,umami,ahumado", 35, "fiesta,consuelo",
     "Fideos anchos*400 g*fideos;Aceite hirviendo*80 ml*aceite;Chile*3 cdas*chile;Ajo*6 dientes*ajo;Cilantro*un manojo*cilantro",
     "El aceite se derrama sobre el chile y el trigo ancho de Xi'an suena biang: el nombre es un golpe, no una letra."),
    ("luosifen", "Luosifen", "螺蛳粉", "China", "Liuzhou", "asia-este", "fideo", "umami,picante", 40, "fiesta",
     "Fideos de arroz*300 g*fideos;Caracoles de río*200 g*pescado;Bambú encurtido*100 g*limon;Chile*2 cdas*chile;Cacahuete*40 g*cacahuete",
     "Liuzhou no pide permiso al olfato: el luosifen llega ácido, picante y obstinado, como un río que fermentó."),
    ("chongqing-xiaomian", "Xiaomian de Chongqing", "重庆小面", "China", "Chongqing", "asia-este", "fideo", "picante,umami", 30, "consuelo,fiesta",
     "Fideos*300 g*fideos;Chile picado*3 cdas*chile;Soya*2 cdas*soya;Cebollín*1 manojo*cebolla;Cacahuete*30 g*cacahuete",
     "En Chongqing el xiaomian no es pequeño: es un incendio de sésamo y chile que cabe en un tazón de calle."),
    ("hong-shao-rou", "Cerdo rojo estofado", "红烧肉", "China", "Shanghai", "asia-este", "estofado", "umami,dulce", 90, "consuelo,impresionar",
     "Panceta de cerdo*800 g*cerdo;Azúcar*40 g*azucar;Soya oscura*4 cdas*soya;Jengibre*1 trozo*jengibre;Vino Shaoxing*80 ml*vino",
     "Shanghai carameliza la panceta hasta el rojo lacre: el hong shao rou es paciencia que brilla como laca."),
    ("dongpo-rou", "Cerdo Dongpo", "东坡肉", "China", "Hangzhou", "asia-este", "estofado", "umami,dulce", 150, "impresionar,consuelo",
     "Panceta de cerdo*1 kg*cerdo;Soya*100 ml*soya;Vino Shaoxing*150 ml*vino;Azúcar*50 g*azucar;Jengibre*1 trozo*jengibre",
     "El poeta Su Dongpo dejó un cuadrado de panceta que se corta con la cuchara: Hangzhou lo sirve como verso lento."),
    ("hui-guo-rou", "Cerdo dos veces cocido", "回锅肉", "China", "Chengdu", "asia-este", "estofado", "picante,umami", 40, "fiesta,consuelo",
     "Panceta de cerdo*500 g*cerdo;Chile doubanjiang*2 cdas*chile;Puerro*2*cebolla;Ajo*4 dientes*ajo;Jengibre*1 trozo*jengibre",
     "Chengdu cuece el cerdo, lo vuelve a la wok y lo casa con doubanjiang: el hui guo rou es un regreso que pica."),
    ("yu-xiang-qiezi", "Berenjena yu xiang", "鱼香茄子", "China", "Chengdu", "asia-este", "estofado", "picante,dulce,umami", 35, "consuelo",
     "Berenjena*600 g*tomate;Ajo*5 dientes*ajo;Jengibre*1 trozo*jengibre;Chile*2 cdas*chile;Azúcar y vinagre*al gusto*azucar",
     "Se llama perfume de pez y no lleva pez: Sichuan enseña que el nombre puede ser un aroma y la berenjena, el río."),
    ("shi-zi-tou", "Cabezas de león", "红烧狮子头", "China", "Yangzhou", "asia-este", "estofado", "umami,dulce", 80, "impresionar,consuelo",
     "Cerdo picado*600 g*cerdo;Huevo*1*huevo;Jengibre*15 g*jengibre;Soya*3 cdas*soya;Col*4 hojas*cebolla",
     "Yangzhou nombra leones a unas albóndigas que se hunden en caldo: el tamaño es orgullo, no amenaza."),
    ("suan-cai-yu", "Pescado con encurtido", "酸菜鱼", "China", "Chongqing", "asia-este", "caldo", "picante,citrico,umami", 50, "consuelo,fiesta",
     "Filete de pescado*600 g*pescado;Mostaza encurtida*200 g*limon;Chile*3 cdas*chile;Jengibre*1 trozo*jengibre;Ajo*4 dientes*ajo",
     "Chongqing pone el pescado a nadar en un caldo agrio y rojo: el suan cai yu es un río que muerde con cortesía."),
    ("hotpot-chongqing", "Hot pot de Chongqing", "重庆火锅", "China", "Chongqing", "asia-este", "caldo", "picante,umami,ahumado", 90, "fiesta",
     "Caldo de chile y pimienta*2 l*chile;Res en láminas*400 g*res;Tofu*300 g*tofu;Verduras*al gusto*cebolla;Ajo*1 cabeza*ajo",
     "La mesa es una olla y la olla es un volcán: Chongqing invita a cocer la noche en un círculo de aceite rojo."),
    ("xi-hu-niurou-geng", "Sopa del Lago del Oeste", "西湖牛肉羹", "China", "Hangzhou", "asia-este", "caldo", "umami,cremoso", 40, "ligero,impresionar",
     "Res picada*200 g*res;Clara de huevo*2*huevo;Jengibre*1 trozo*jengibre;Almidón*2 cdas*trigo;Cilantro*al gusto*cilantro",
     "Hangzhou espesa el lago en una sopa de res que tiembla: el West Lake cabe en la cuchara si el fuego no se apresura."),
    ("kou-shui-ji", "Pollo baba", "口水鸡", "China", "Chengdu", "asia-este", "crudo", "picante,umami,herbal", 45, "fiesta,impresionar",
     "Pollo*1 entero*pollo;Chile rojo*4 cdas*chile;Soya*3 cdas*soya;Ajo*4 dientes*ajo;Cacahuete*40 g*cacahuete",
     "El pollo se sirve frío para que el chile hable: Chengdu llama baba a una salsa que obliga a tragar."),
    ("zui-ji", "Pollo borracho", "醉鸡", "China", "Shanghai", "asia-este", "crudo", "umami,herbal", 60, "impresionar,ligero",
     "Pollo*1 entero*pollo;Vino Shaoxing*300 ml*vino;Jengibre*1 trozo*jengibre;Cebollín*2*cebolla;Sal*al gusto*sal",
     "Shanghai emborracha el pollo con Shaoxing y lo deja dormir: el zui ji se come frío, lúcido y perfumado."),
    ("fuqi-feipian", "Fuqi feipian", "夫妻肺片", "China", "Chengdu", "asia-este", "crudo", "picante,umami", 50, "fiesta",
     "Vísceras de res*400 g*res;Chile*3 cdas*chile;Cacahuete*50 g*cacahuete;Cilantro*un manojo*cilantro;Soya*2 cdas*soya",
     "Un matrimonio de Chengdu cortó la res en láminas y las bañó de chile: el nombre es tierno, el plato no."),
    ("gan-bian-sijidou", "Judías salteadas secas", "干煸四季豆", "China", "Chengdu", "asia-este", "frito", "picante,umami,ahumado", 25, "fiesta,ligero",
     "Judías verdes*400 g*cebolla;Carne picada*100 g*cerdo;Chile*2 cdas*chile;Ajo*3 dientes*ajo;Soya*1 cda*soya",
     "Sichuan fríe la judía hasta que se arruga y guarda el humo: el gan bian es un crujido que pica después."),
    ("tang-cu-paigu", "Costillas agridulces", "糖醋排骨", "China", "Wuxi", "asia-este", "frito", "dulce,citrico,umami", 45, "fiesta,consuelo",
     "Costillas de cerdo*800 g*cerdo;Azúcar*60 g*azucar;Vinagre*50 ml*limon;Soya*2 cdas*soya;Ajo*3 dientes*ajo",
     "Wuxi barniza las costillas con un agridulce que brilla de noche: el hueso se chupa como un acuerdo."),
    ("chou-doufu", "Tofu maloliente", "臭豆腐", "China", "Changsha", "asia-este", "frito", "umami,picante,ahumado", 20, "fiesta",
     "Tofu fermentado*400 g*tofu;Aceite*500 ml*aceite;Chile*2 cdas*chile;Ajo*3 dientes*ajo;Soya*1 cda*soya",
     "Changsha fríe un perfume que asusta a dos calles: el chou doufu enamora cuando el crujiente gana al miedo."),
    ("baozai-fan", "Arroz en cazuela", "煲仔饭", "China", "Guangzhou", "asia-este", "arroz", "umami,ahumado", 40, "consuelo",
     "Arroz*300 g*arroz;Cerdo o pollo*250 g*cerdo;Soya*2 cdas*soya;Cebollín*1 manojo*cebolla;Aceite*1 cda*aceite",
     "Cantón sirve el arroz en barro hasta que el fondo se dora: el baozai fan es un socarrat del sur que huele a soya."),
    ("zongzi", "Zongzi", "粽子", "China", "Jiaxing", "asia-este", "arroz", "umami,herbal", 120, "fiesta,consuelo",
     "Arroz glutinoso*400 g*arroz;Panceta*200 g*cerdo;Yema de huevo de pato*4*huevo;Hoja de bambú*12*cilantro",
     "Jiaxing envuelve el Dragón en hoja de bambú: el zongzi es un nudo de arroz que se desata con los dientes."),
    ("tangyuan", "Tangyuan", "汤圆", "China", "Ningbo", "asia-este", "postre", "dulce,cremoso", 40, "consuelo,fiesta",
     "Harina de arroz glutinoso*250 g*arroz;Pasta de sésamo negro*120 g*cacahuete;Azúcar*80 g*azucar;Agua*400 ml*agua",
     "Ningbo flota lunas de arroz en un caldo dulce: el tangyuan reúne a la familia cuando el año se cierra."),
    ("yuebing", "Pastel de luna", "月饼", "China", "Suzhou", "asia-este", "postre", "dulce", 150, "fiesta,impresionar",
     "Pasta de lotus*300 g*azucar;Yema de huevo de pato*4*huevo;Harina*200 g*trigo;Aceite*80 ml*aceite",
     "Suzhou hornea la luna llena en un disco denso: el yuebing se parte en cuatro y el otoño cabe en la palma."),
    ("suan-mei-tang", "Jugo de ciruela agria", "酸梅汤", "China", "Beijing", "asia-este", "bebida", "citrico,dulce,herbal", 30, "ligero,fiesta",
     "Ciruela umeboshi seca*80 g*fruta;Azúcar*60 g*azucar;Canela y anís*al gusto*canela;Agua*1 l*agua",
     "Pekín responde al calor con un vaso oscuro y agrio: el suan mei tang es sombra líquida en un patio de tejas."),
]

# ---------------------------------------------------------------------------
# India (26)
# ---------------------------------------------------------------------------
DISHES += [
    ("rogan-josh", "Rogan josh", "रोगन जोश", "India", "Srinagar", "asia-sur", "curry", "picante,umami,herbal", 90, "consuelo,impresionar",
     "Cordero*800 g*cordero;Yogur*150 g*yogurt;Chile cachemir*2 cdas*chile;Ajo*6 dientes*ajo;Jengibre*1 trozo*jengibre",
     "Cachemira tiñe el cordero de un rojo que no quema: el rogan josh es grasa de cola y paciencia de montaña."),
    ("tandoori-chicken", "Pollo tandoori", "तंदूरी चिकन", "India", "Delhi", "asia-sur", "brasa", "picante,ahumado,cremoso", 70, "fiesta,impresionar",
     "Pollo*1 kg*pollo;Yogur*200 g*yogurt;Chile*2 cdas*chile;Ajo*6 dientes*ajo;Jengibre*1 trozo*jengibre;Limón*2*limon",
     "El tandoor de Delhi marca el pollo con cicatrices de fuego: el rojo es especias, no disfraz."),
    ("chicken-tikka", "Pollo tikka", "चिकन टिक्का", "India", "Delhi", "asia-sur", "brasa", "picante,ahumado,cremoso", 50, "fiesta,impresionar",
     "Pechuga de pollo*600 g*pollo;Yogur*150 g*yogurt;Garam masala*2 cdas*chile;Limón*1*limon;Ajo*4 dientes*ajo",
     "El tikka se ensarta para que el yogur sobreviva al carbón: Delhi lo come con cebolla cruda y un limón partido."),
    ("malai-kofta", "Malai kofta", "मलाई कोफ्ता", "India", "Lucknow", "asia-sur", "curry", "cremoso,dulce,herbal", 60, "impresionar,consuelo",
     "Papa*400 g*papa;Queso panir*200 g*queso;Nata*150 ml*leche;Tomate*3*tomate;Anacardos*40 g*cacahuete",
     "Lucknow hunde albóndigas de panir en una nata que no pide perdón: el malai kofta es fiesta de nawab."),
    ("lamb-korma", "Korma de cordero", "गोश्त कोरमा", "India", "Lucknow", "asia-sur", "curry", "cremoso,herbal,dulce", 90, "impresionar,consuelo",
     "Cordero*800 g*cordero;Yogur*200 g*yogurt;Cebolla*3*cebolla;Ajo*6 dientes*ajo;Canela*1 rama*canela",
     "El korma awadhi no grita chile: Lucknow susurra yogur, cebolla frita y un cordero que se rinde."),
    ("goan-fish-curry", "Curry de pescado de Goa", "गोअन फिश करी", "India", "Panaji", "asia-sur", "curry", "picante,citrico,cremoso", 40, "fiesta,ligero",
     "Pescado*600 g*pescado;Coco rallado*200 g*coco;Tamarindo*2 cdas*limon;Chile*3*chile;Ajo*4 dientes*ajo",
     "Goa casa el coco con el tamarindo y el mar entra en la cazuela sin pedir mapa."),
    ("hyderabadi-mutton-biryani", "Biryani de cordero de Hyderabad", "حیدرآبادی دم بریانی", "India", "Hyderabad", "asia-sur", "arroz", "picante,umami,herbal", 120, "impresionar,fiesta",
     "Cordero*800 g*cordero;Arroz basmati*400 g*arroz;Yogur*150 g*yogurt;Azafrán y chile*al gusto*chile;Cebolla frita*2*cebolla",
     "Hyderabad sella el dum y el vapor casa el basmati con el cordero: el biryani aquí es un tratado, no un adorno."),
    ("lemon-rice", "Arroz al limón", "எலுமிச்சை சாதம்", "India", "Chennai", "asia-sur", "arroz", "citrico,herbal,fresco", 25, "ligero,consuelo",
     "Arroz*300 g*arroz;Limón*2*limon;Mostaza en grano*1 cda*sal;Cúrcuma*1 cdita*chile;Cacahuete*30 g*cacahuete",
     "Tamil Nadu agría el arroz con un limón que basta: el chitranna es un mediodía que no pesa."),
    ("curd-rice", "Arroz con yogur", "தயிர் சாதம்", "India", "Chennai", "asia-sur", "arroz", "cremoso,fresco,herbal", 20, "consuelo,ligero",
     "Arroz*300 g*arroz;Yogur*250 g*yogurt;Mostaza*1 cdita*sal;Hoja de curry*10*cilantro;Aceite*1 cda*aceite",
     "El thayir sadam apaga el chile del día: Chennai lo come cuando el calor pide tregua y no espectáculo."),
    ("appam-stew", "Appam con estofado", "ആപ്പവും സ്റ്റൂവും", "India", "Kochi", "asia-sur", "desayuno", "cremoso,herbal,dulce", 50, "consuelo,ligero",
     "Harina de arroz*250 g*arroz;Coco*200 ml*coco;Pollo*400 g*pollo;Cebolla*2*cebolla;Jengibre*1 trozo*jengibre",
     "Kerala fermenta el appam hasta que el centro queda tierno: el stew de coco es la marea que lo acompaña."),
    ("uttapam", "Uttapam", "உத்தப்பம்", "India", "Chennai", "asia-sur", "desayuno", "umami,picante,fresco", 35, "consuelo,fiesta",
     "Masa de arroz y lenteja*400 g*arroz;Cebolla*1*cebolla;Tomate*1*tomate;Chile verde*2*chile;Aceite*2 cdas*aceite",
     "El uttapam es un dosa que no se dobló: Chennai lo carga de cebolla y tomate y lo come con chutney de coco."),
    ("poha", "Poha", "पोहा", "India", "Indore", "asia-sur", "desayuno", "citrico,herbal,fresco", 20, "ligero,consuelo",
     "Arroz aplastado*250 g*arroz;Cebolla*1*cebolla;Cacahuete*40 g*cacahuete;Limón*1*limon;Cúrcuma*1 cdita*chile",
     "Indore desayuna copos de arroz que se hinchan en un suspiro: el poha es ligero y huele a mostaza."),
    ("aloo-paratha", "Paratha de papa", "आलू पराठा", "India", "Amritsar", "asia-sur", "pan", "umami,cremoso,picante", 40, "consuelo,fiesta",
     "Harina*300 g*trigo;Papa*400 g*papa;Chile verde*2*chile;Ghee*3 cdas*leche;Cilantro*un manojo*cilantro",
     "Punjab rellena el pan de papa especiada y lo dora en ghee: el aloo paratha pide yogur y no disculpas."),
    ("pav-bhaji", "Pav bhaji", "पाव भाजी", "India", "Mumbai", "asia-sur", "pan", "picante,umami,citrico", 45, "fiesta,consuelo",
     "Papa*400 g*papa;Tomate*3*tomate;Mantequilla*60 g*leche;Pan pav*8*trigo;Limón*2*limon;Cilantro*un manojo*cilantro",
     "Bombay machaca el mercado en una sartén de mantequilla: el pav bhaji se come de pie, con pan tostado y un limón."),
    ("vada-pav", "Vada pav", "वडा पाव", "India", "Mumbai", "asia-sur", "frito", "picante,umami", 35, "fiesta,consuelo",
     "Papa*400 g*papa;Harina de garbanzo*150 g*garbanzo;Pan pav*8*trigo;Chile*3*chile;Ajo*6 dientes*ajo",
     "El vada pav es la hamburguesa que Bombay no pidió prestada: papa frita, chutney verde y un pan que cabe en el tren."),
    ("samosa", "Samosa", "समोसा", "India", "Delhi", "asia-sur", "empanada", "picante,umami", 50, "fiesta,consuelo",
     "Harina*300 g*trigo;Papa*350 g*papa;Guisantes*80 g*frijol;Comino y chile*al gusto*chile;Aceite*500 ml*aceite",
     "El triángulo de Delhi cruje y suelta vapor de papa: la samosa es un secreto de comino que viaja en papel."),
    ("rasam", "Rasam", "ரசம்", "India", "Madurai", "asia-sur", "caldo", "citrico,picante,herbal", 30, "ligero,consuelo",
     "Tamarindo*3 cdas*limon;Tomate*2*tomate;Lenteja*50 g*lenteja;Pimienta y comino*1 cda*chile;Ajo*3 dientes*ajo",
     "Madurai sirve un caldo agrio que aclara la cabeza: el rasam es medicina de tamarindo y no pide arroz, aunque lo acepta."),
    ("rasgulla", "Rasgulla", "রসগোল্লা", "India", "Kolkata", "asia-sur", "postre", "dulce,cremoso", 60, "fiesta,impresionar",
     "Queso chena*400 g*queso;Azúcar*300 g*azucar;Agua*800 ml*agua;Agua de rosas*1 cda*fruta",
     "Calcuta esponja el chena en almíbar hasta que flota: la rasgulla se muerde y suelta un río dulce."),
    ("jalebi", "Jalebi", "जलेबी", "India", "Delhi", "asia-sur", "postre", "dulce,citrico", 40, "fiesta,consuelo",
     "Harina*200 g*trigo;Azúcar*250 g*azucar;Azafrán*una pizca*azucar;Aceite*400 ml*aceite;Limón*1*limon",
     "Delhi dibuja espirales que se bañan en almíbar caliente: la jalebi cruje un segundo y después se rinde."),
    ("filter-coffee", "Café de filtro", "காப்பி", "India", "Chennai", "asia-sur", "bebida", "umami,dulce,cremoso", 15, "consuelo,impresionar",
     "Café molido*4 cdas*cafe;Leche*400 ml*leche;Azúcar*al gusto*azucar;Agua*200 ml*agua",
     "Tamil Nadu decanta el café de un filtro de metal y lo bate hasta espuma: el grado se discute como un credo."),
    ("dhokla", "Dhokla", "ઢોકળા", "India", "Ahmedabad", "asia-sur", "desayuno", "citrico,herbal,fresco", 40, "ligero,fiesta",
     "Harina de garbanzo*250 g*garbanzo;Yogur*100 g*yogurt;Mostaza*1 cdita*sal;Cilantro*un manojo*cilantro;Aceite*2 cdas*aceite",
     "Guyarat vaporiza un pastel amarillo que tiembla: el dhokla es ligero, templado y se come con chutney verde."),
    ("misal-pav", "Misal pav", "मिसळ पाव", "India", "Pune", "asia-sur", "pan", "picante,umami", 50, "fiesta,consuelo",
     "Brotes de moth*300 g*frijol;Pan pav*8*trigo;Cebolla*1*cebolla;Farsan*80 g*trigo;Chile*3 cdas*chile",
     "Pune sirve un usal rojo que pica de verdad: el misal pav se come con pan y un vaso de suero cerca."),
    ("kadai-paneer", "Kadai paneer", "कड़ाई पनीर", "India", "Delhi", "asia-sur", "curry", "picante,umami,herbal", 40, "fiesta,consuelo",
     "Queso panir*400 g*queso;Pimiento*2*tomate;Tomate*3*tomate;Chile*2 cdas*chile;Cilantro*un manojo*cilantro",
     "El kadai huele a semilla de cilantro tostada: Delhi saltea el panir hasta que el pimiento aún cruje."),
    ("baingan-bharta", "Baingan bharta", "बैंगन का भरता", "India", "Amritsar", "asia-sur", "estofado", "ahumado,picante,umami", 45, "consuelo,fiesta",
     "Berenjena*2 grandes*tomate;Tomate*2*tomate;Ajo*4 dientes*ajo;Chile*2*chile;Cilantro*un manojo*cilantro;Aceite*3 cdas*aceite",
     "Punjab asa la berenjena hasta el humo y la machaca: el bharta es un puré que aún recuerda el fuego."),
    ("chettinad-chicken", "Pollo Chettinad", "செட்டிநாடு கோழி", "India", "Karaikudi", "asia-sur", "curry", "picante,umami,ahumado", 55, "fiesta,impresionar",
     "Pollo*800 g*pollo;Coco*80 g*coco;Pimienta negra*1 cda*chile;Ajo*6 dientes*ajo;Jengibre*1 trozo*jengibre",
     "Chettinad tuesta la pimienta hasta que el pollo habla fuerte: Karaikudi no suaviza el masala para nadie."),
    ("bhel-puri", "Bhel puri", "भेल पुरी", "India", "Mumbai", "asia-sur", "crudo", "citrico,picante,fresco", 15, "ligero,fiesta",
     "Arroz inflado*100 g*arroz;Cebolla*1*cebolla;Tomate*1*tomate;Cilantro*un manojo*cilantro;Tamarindo*2 cdas*limon;Chile*1 cda*chile",
     "El Marine Drive se come en un cucurucho: el bhel puri es crujiente, agrio y se acaba antes de que el mar lo humedezca."),
]

# ---------------------------------------------------------------------------
# Japón (22)
# ---------------------------------------------------------------------------
DISHES += [
    ("miso-shiru", "Sopa de miso", "味噌汁", "Japón", "Tokio", "asia-este", "caldo", "umami,herbal", 15, "consuelo,ligero",
     "Pasta de miso*3 cdas*soya;Tofu*150 g*tofu;Wakame*10 g*agua;Cebollín*2*cebolla;Agua*800 ml*agua",
     "Tokio desayuna un caldo que no se hierven de más: el miso shiru es la casa medida en cucharas."),
    ("shabu-shabu", "Shabu-shabu", "しゃぶしゃぶ", "Japón", "Osaka", "asia-este", "caldo", "umami,fresco", 50, "fiesta,ligero",
     "Res en láminas*500 g*res;Caldo de kombu*1.5 l*agua;Tofu*200 g*tofu;Soya*4 cdas*soya;Cebollín*1 manojo*cebolla",
     "Osaka sumerge la res un instante y la saca: el shabu-shabu es un sonido, no una receta larga."),
    ("sukiyaki", "Sukiyaki", "すき焼き", "Japón", "Tokio", "asia-este", "estofado", "dulce,umami", 40, "fiesta,consuelo",
     "Res*500 g*res;Soya*80 ml*soya;Azúcar*40 g*azucar;Tofu*200 g*tofu;Huevo crudo*4*huevo",
     "El sukiyaki se cocina en la mesa y se moja en yema: Tokio enseña que el dulce de soya también es invierno."),
    ("chanko-nabe", "Chanko nabe", "ちゃんこ鍋", "Japón", "Tokio", "asia-este", "caldo", "umami,herbal", 70, "consuelo,fiesta",
     "Pollo*600 g*pollo;Tofu*300 g*tofu;Repollo*400 g*cebolla;Caldo*1.5 l*agua;Cebollín*1 manojo*cebolla",
     "Los rikishi de Ryogoku se hacen en esta olla: el chanko nabe es abundancia que no pide adorno."),
    ("kitsune-udon", "Kitsune udon", "きつねうどん", "Japón", "Osaka", "asia-este", "fideo", "umami,dulce", 25, "consuelo,ligero",
     "Udon*400 g*fideos;Tofu frito aburaage*4*tofu;Caldo dashi*1 l*agua;Soya*3 cdas*soya;Cebollín*2*cebolla",
     "Osaka pone un tofu dulce sobre el udon y lo llama zorro: el kitsune es consuelo que se desliza."),
    ("zaru-soba", "Soba fría", "ざるそば", "Japón", "Tokio", "asia-este", "fideo", "umami,fresco", 20, "ligero,impresionar",
     "Soba de alforfón*300 g*fideos;Soya*80 ml*soya;Wasabi y cebollín*al gusto*cebolla;Alga nori*1 hoja*agua",
     "El verano de Tokio se come en un zaru: la soba fría se moja y se aspira, y el trigo sarraceno huele a montaña."),
    ("yakisoba", "Yakisoba", "焼きそば", "Japón", "Hiroshima", "asia-este", "fideo", "umami,dulce,ahumado", 25, "fiesta,consuelo",
     "Fideos de trigo*400 g*fideos;Cerdo*200 g*cerdo;Repollo*200 g*cebolla;Salsa yakisoba*4 cdas*soya;Aceite*2 cdas*aceite",
     "Hiroshima saltea el yakisoba en plancha de feria: el agridulce se pega al tenedor y a la manga."),
    ("tsukemen", "Tsukemen", "つけ麺", "Japón", "Tokio", "asia-este", "fideo", "umami,ahumado", 40, "consuelo,impresionar",
     "Fideos*400 g*fideos;Caldo concentrado*600 ml*pollo;Soya*4 cdas*soya;Cebollín*1 manojo*cebolla;Cerdo*150 g*cerdo",
     "Tokio separa el fideo del caldo para que el moje sea un acto: el tsukemen no es ramen, es una reverencia."),
    ("onigiri", "Onigiri", "おにぎり", "Japón", "Kioto", "asia-este", "arroz", "umami,fresco", 20, "ligero,consuelo",
     "Arroz*400 g*arroz;Alga nori*4 hojas*agua;Salmón o umeboshi*120 g*pescado;Sal*al gusto*sal",
     "Kioto cierra el arroz en un triángulo que viaja: el onigiri es la comida del tren y de la mano."),
    ("gyudon", "Gyudon", "牛丼", "Japón", "Tokio", "asia-este", "arroz", "umami,dulce", 25, "consuelo,fiesta",
     "Res en láminas*400 g*res;Cebolla*2*cebolla;Soya*4 cdas*soya;Arroz*400 g*arroz;Jengibre*20 g*jengibre",
     "El gyudon es el mediodía de Tokio en un bowl: res dulce, cebolla y prisa que aún sabe a casa."),
    ("unadon", "Unadon", "鰻丼", "Japón", "Tokio", "asia-este", "arroz", "umami,dulce,ahumado", 40, "impresionar,consuelo",
     "Anguila*400 g*pescado;Soya*4 cdas*soya;Mirin y azúcar*3 cdas*azucar;Arroz*400 g*arroz",
     "Nihonbashi barniza la anguila hasta el lacre: el unadon es un verano que se come con palillos humildes."),
    ("karaage", "Karaage", "唐揚げ", "Japón", "Oita", "asia-este", "frito", "umami,ahumado", 30, "fiesta,consuelo",
     "Pollo*600 g*pollo;Soya*3 cdas*soya;Jengibre*1 trozo*jengibre;Ajo*3 dientes*ajo;Aceite*500 ml*aceite",
     "Oita marina el pollo en jengibre y lo fríe dos veces: el karaage cruje y el jugo se queda dentro."),
    ("tempura", "Tempura", "天ぷら", "Japón", "Tokio", "asia-este", "frito", "umami,fresco", 35, "impresionar,ligero",
     "Camarón*8*camaron;Harina*150 g*trigo;Agua helada*200 ml*agua;Aceite*1 l*aceite;Soya*4 cdas*soya",
     "El tempura de Ginza es una nube que dura un minuto: el aceite no se ve, solo se oye el crujido."),
    ("yakitori", "Yakitori", "焼き鳥", "Japón", "Tokio", "asia-este", "brasa", "umami,ahumado,dulce", 35, "fiesta,consuelo",
     "Pollo*600 g*pollo;Soya*4 cdas*soya;Azúcar*1 cda*azucar;Cebollín*4*cebolla;Sal*al gusto*sal",
     "Bajo el tren de Yurakucho el humo pinta el pollo: el yakitori se come de pie, con una cerveza y poco discurso."),
    ("yakiniku", "Yakiniku", "焼肉", "Japón", "Osaka", "asia-este", "brasa", "umami,ahumado,picante", 40, "fiesta,impresionar",
     "Res*500 g*res;Soya*4 cdas*soya;Ajo*4 dientes*ajo;Azúcar*1 cda*azucar;Sesamo*2 cdas*cacahuete",
     "Osaka pone la parrilla en el centro y cada uno es su chef: el yakiniku es un pacto de humo y ajo."),
    ("tamagoyaki", "Tamagoyaki", "卵焼き", "Japón", "Tokio", "asia-este", "desayuno", "dulce,umami,cremoso", 20, "consuelo,impresionar",
     "Huevo*4*huevo;Azúcar*1 cda*azucar;Soya*1 cdita*soya;Aceite*1 cda*aceite",
     "El tamagoyaki se enrolla en capas como un diario: Tokio lo mete en el bento y el día queda dulce."),
    ("natto-gohan", "Nattō con arroz", "納豆ご飯", "Japón", "Mito", "asia-este", "desayuno", "umami,fresco", 10, "consuelo,ligero",
     "Nattō*100 g*soya;Arroz*300 g*arroz;Soya*1 cda*soya;Cebollín*2*cebolla;Huevo crudo*1*huevo",
     "Mito enseña a amar lo pegajoso: el nattō sobre arroz caliente es un desayuno que no se negocia."),
    ("taiyaki", "Taiyaki", "たい焼き", "Japón", "Tokio", "asia-este", "postre", "dulce,cremoso", 30, "fiesta,consuelo",
     "Harina*200 g*trigo;Pasta de judía roja*150 g*frijol;Azúcar*40 g*azucar;Huevo*1*huevo",
     "El pez se hornea en molde y esconde anko: Tokio muerde la cola primero, por superstición y por gusto."),
    ("dorayaki", "Dorayaki", "どら焼き", "Japón", "Tokio", "asia-este", "postre", "dulce,cremoso", 35, "consuelo,fiesta",
     "Harina*150 g*trigo;Huevo*2*huevo;Pasta de judía*150 g*frijol;Azúcar*80 g*azucar;Miel*1 cda*azucar",
     "Dos pancakes abrazan el anko y el dorayaki cabe en la palma: Tokio lo merienda sin prisa de ceremonia."),
    ("sakura-mochi", "Sakura mochi", "桜餅", "Japón", "Tokio", "asia-este", "postre", "dulce,herbal", 40, "impresionar,fiesta",
     "Harina de arroz*200 g*arroz;Pasta de judía*120 g*frijol;Hoja de cerezo*8*cilantro;Azúcar*50 g*azucar",
     "Envuelto en hoja de cerezo, el sakura mochi sabe a marzo: Tokio lo come cuando los pétalos aún no han caído."),
    ("mugicha", "Té de cebada", "麦茶", "Japón", "Fukuoka", "asia-este", "bebida", "herbal,fresco", 15, "ligero,consuelo",
     "Cebada tostada*30 g*te;Agua*1 l*agua;Hielo*al gusto*agua",
     "El mugicha se sirve helado y tostado: Fukuoka apaga el verano con un vaso que no pide azúcar."),
    ("hiyayakko", "Tofu frío", "冷奴", "Japón", "Kioto", "asia-este", "crudo", "fresco,umami", 10, "ligero,consuelo",
     "Tofu fresco*400 g*tofu;Jengibre*20 g*jengibre;Cebollín*2*cebolla;Soya*2 cdas*soya",
     "Kioto corta el tofu frío y le pone jengibre: el hiyayakko es un silencio que se come con cuchara."),
]

# ---------------------------------------------------------------------------
# Tailandia (16)
# ---------------------------------------------------------------------------
DISHES += [
    ("pad-krapao", "Pad krapao", "ผัดกระเพรา", "Tailandia", "Bangkok", "asia-sur", "frito", "picante,herbal,umami", 20, "fiesta,consuelo",
     "Carne picada*400 g*cerdo;Albahaca holy*2 manojos*cilantro;Chile*8*chile;Ajo*6 dientes*ajo;Salsa de pescado*2 cdas*pescado;Huevo frito*4*huevo",
     "Bangkok saltea la albahaca hasta que el wok humea: el pad krapao pide un huevo frito y no pide permiso."),
    ("pad-see-ew", "Pad see ew", "ผัดซีอิ๊ว", "Tailandia", "Bangkok", "asia-sur", "fideo", "umami,dulce,ahumado", 25, "consuelo,fiesta",
     "Fideos de arroz anchos*300 g*fideos;Cerdo*200 g*cerdo;Soya oscura*3 cdas*soya;Huevo*2*huevo;Verdura china*150 g*cebolla",
     "Los fideos anchos se caramelizan en soya oscura: Bangkok come pad see ew cuando el pad thai ya cansó."),
    ("rad-na", "Rad na", "ราดหน้า", "Tailandia", "Bangkok", "asia-sur", "fideo", "umami,cremoso", 30, "consuelo",
     "Fideos de arroz*300 g*fideos;Salsa espesa de soya*200 ml*soya;Cerdo o marisco*200 g*cerdo;Brócoli chino*150 g*cebolla",
     "El rad na cubre los fideos con una salsa que napar: Bangkok lo pide cuando quiere consuelo y no fuego."),
    ("kuay-teow-reua", "Fideos de barca", "ก๋วยเตี๋ยวเรือ", "Tailandia", "Ayutthaya", "asia-sur", "fideo", "picante,umami,herbal", 40, "consuelo,fiesta",
     "Fideos de arroz*300 g*fideos;Res*250 g*res;Sangre coagulada*80 g*res;Chile tostado*2 cdas*chile;Albahaca*un manojo*cilantro",
     "Ayutthaya sirvió este caldo desde una barca: el kuay teow reua es oscuro, picante y huele a galanga."),
    ("jok-thai", "Jok", "โจ๊ก", "Tailandia", "Bangkok", "asia-sur", "desayuno", "umami,cremoso", 40, "consuelo",
     "Arroz*200 g*arroz;Cerdo picado*200 g*cerdo;Jengibre*1 trozo*jengibre;Huevo*4*huevo;Cebollín*1 manojo*cebolla",
     "El jok de Bangkok es un arroz que se rindió al caldo: el jengibre y el huevo crudo cierran la madrugada."),
    ("kai-jeow", "Tortilla tailandesa", "ไข่เจียว", "Tailandia", "Bangkok", "asia-sur", "desayuno", "umami,ahumado", 15, "consuelo,ligero",
     "Huevo*4*huevo;Salsa de pescado*1 cda*pescado;Aceite*200 ml*aceite;Cebollín*2*cebolla",
     "La tortilla tailandesa se fríe en aceite alto hasta encaje: Bangkok la pone sobre arroz y el desayuno queda resuelto."),
    ("moo-ping", "Moo ping", "หมูปิ้ง", "Tailandia", "Bangkok", "asia-sur", "brasa", "dulce,ahumado,umami", 40, "fiesta,consuelo",
     "Cerdo*500 g*cerdo;Soya*2 cdas*soya;Leche de coco*80 ml*coco;Ajo*4 dientes*ajo;Azúcar de palma*2 cdas*azucar",
     "Los pinchos de cerdo humean en la acera: el moo ping se come con arroz pegajoso y una salsa que pica tarde."),
    ("gai-yang", "Gai yang", "ไก่ย่าง", "Tailandia", "Khon Kaen", "asia-sur", "brasa", "ahumado,picante,herbal", 60, "fiesta,impresionar",
     "Pollo*1 entero*pollo;Ajo*8 dientes*ajo;Cilantro raíz*un manojo*cilantro;Salsa de pescado*3 cdas*pescado;Chile*2*chile",
     "Isan abre el pollo y lo asa al carbón hasta la piel lacada: el gai yang se come con som y arroz pegajoso."),
    ("nam-tok-moo", "Nam tok de cerdo", "น้ำตกหมู", "Tailandia", "Ubon Ratchathani", "asia-sur", "crudo", "picante,citrico,herbal", 35, "fiesta,ligero",
     "Cerdo a la brasa*400 g*cerdo;Lima*2*limon;Arroz tostado*2 cdas*arroz;Menta y cebollín*un manojo*cilantro;Chile*2 cdas*chile",
     "Ubon corta el cerdo asado y lo baña de lima y arroz tostado: el nam tok es una cascada que pica."),
    ("yum-woonsen", "Yum woon sen", "ยำวุ้นเส้น", "Tailandia", "Bangkok", "asia-sur", "crudo", "citrico,picante,fresco", 20, "ligero,fiesta",
     "Fideos de soja*200 g*fideos;Camarón*150 g*camaron;Lima*3*limon;Chile*4*chile;Cilantro*un manojo*cilantro",
     "Bangkok aliña el fideo de soja con lima hasta que duele rico: el yum woon sen es ensalada que no se esconde."),
    ("gaeng-phet", "Curry rojo", "แกงเผ็ด", "Tailandia", "Bangkok", "asia-sur", "curry", "picante,cremoso,herbal", 40, "fiesta,impresionar",
     "Pasta de curry rojo*3 cdas*chile;Leche de coco*400 ml*coco;Pollo*500 g*pollo;Albahaca thai*un manojo*cilantro;Salsa de pescado*2 cdas*pescado",
     "El curry rojo no pide disculpas: Bangkok lo cuece en coco y el color es un aviso, no un adorno."),
    ("gaeng-som", "Gaeng som", "แกงส้ม", "Tailandia", "Hua Hin", "asia-sur", "curry", "citrico,picante,herbal", 40, "ligero,fiesta",
     "Pescado*500 g*pescado;Pasta agria*3 cdas*limon;Tamarindo*2 cdas*limon;Verduras*300 g*cebolla;Chile*3*chile",
     "El sur agrío el curry hasta que el tamarindo manda: el gaeng som de Hua Hin es un río naranja que despierta."),
    ("gaeng-karee", "Curry amarillo", "แกงกะหรี่", "Tailandia", "Phuket", "asia-sur", "curry", "cremoso,picante,dulce", 45, "consuelo,fiesta",
     "Pollo*500 g*pollo;Leche de coco*400 ml*coco;Curry en polvo*2 cdas*chile;Papa*2*papa;Cebolla*1*cebolla",
     "Phuket dulcifica el curry con papa y coco: el gaeng karee es el primo amable que aún pica."),
    ("khao-pad", "Arroz frito tailandés", "ข้าวผัด", "Tailandia", "Bangkok", "asia-sur", "arroz", "umami,citrico", 20, "consuelo,fiesta",
     "Arroz del día anterior*400 g*arroz;Huevo*2*huevo;Salsa de pescado*2 cdas*pescado;Cebollín*3*cebolla;Lima*1*limon",
     "El khao pad de Bangkok se hace con arroz de ayer y un wok que no perdona: la lima al final es el país."),
    ("sangkhaya", "Sangkhaya", "สังขยา", "Tailandia", "Bangkok", "asia-sur", "postre", "dulce,cremoso", 50, "impresionar,consuelo",
     "Leche de coco*300 ml*coco;Huevo*4*huevo;Azúcar de palma*80 g*azucar;Calabaza*1*fruta",
     "La custodia de coco se cuece dentro de la calabaza: Bangkok sirve sangkhaya como un templo comestible."),
    ("oliang", "Oliang", "โอเลี้ยง", "Tailandia", "Bangkok", "asia-sur", "bebida", "dulce,ahumado", 10, "consuelo,fiesta",
     "Café tostado*4 cdas*cafe;Azúcar*3 cdas*azucar;Hielo*abundante*agua;Agua*300 ml*agua",
     "El oliang se sirve negro, dulce y sobre hielo: Yaowarat lo bebe para aguantar la noche de fideos."),
]
