#!/usr/bin/env python3
"""Generate src/lib/atlas-europa.ts from a validated dish table."""

from __future__ import annotations

import re
from collections import Counter
from pathlib import Path

FAMILIES = {
    "empanada", "maiz", "caldo", "estofado", "arroz", "fideo", "brasa",
    "curry", "frito", "pan", "crudo", "desayuno", "postre", "bebida",
}
FLAVORS = {"umami", "picante", "citrico", "ahumado", "herbal", "dulce", "cremoso", "fresco"}
MOODS = {"consuelo", "fiesta", "ligero", "impresionar"}
KEYS = {
    "pollo", "cerdo", "res", "cordero", "camaron", "pescado", "huevo", "garbanzo",
    "tofu", "arroz", "fideos", "trigo", "maiz", "papa", "platano", "frijol",
    "lenteja", "tomate", "coco", "ajo", "cebolla", "cilantro", "jengibre",
    "chile", "limon", "soya", "leche", "yogurt", "cacahuete", "queso", "azucar",
    "agua", "cafe", "te", "sal", "aceite", "fruta", "canela", "chocolate",
    "yuca", "naranja", "vino",
}
MED = {"Italia", "España", "Grecia", "Portugal"}
COUNTRIES = {
    "Italia", "Francia", "España", "Reino Unido", "Alemania", "Portugal", "Grecia",
    "Polonia", "Rusia", "Austria", "Hungría", "Irlanda", "Suecia", "Suiza",
    "Dinamarca", "Ucrania", "Bélgica", "Países Bajos", "Noruega", "Finlandia",
    "Chequia", "Rumania", "Georgia", "Croacia",
}
FORBIDDEN = {
    "pizza-margherita", "spaghetti-carbonara", "lasagna", "pesto-alla-genovese",
    "cacio-e-pepe", "vongole", "risotto-ai-funghi", "osso-buco", "tiramisu",
    "panna-cotta", "cannoli", "negroni", "paella-valenciana", "gazpacho",
    "tortilla-espanola", "pan-con-tomate", "fideua", "churros", "pastel-de-nata",
    "tarta-santiago", "sangria", "chocolate-a-la-taza", "boeuf-bourguignon",
    "coq-au-vin", "cassoulet", "ratatouille", "creme-brulee", "tarte-citron",
    "croque-madame", "fish-and-chips", "full-english", "sticky-toffee",
    "shepherds-pie", "beef-wellington", "irish-stew", "irish-coffee", "schnitzel",
    "sauerbraten", "choucroute", "gluhwein", "selva-negra", "goulash", "paprikash",
    "pierogi", "bigos", "borscht", "pelmeni", "stroganoff", "fondue",
    "kaiserschmarrn", "sacher-torte", "smorrebrod", "kanelbulle",
    "swedish-meatballs", "kaesespaetzle", "waffles-liege", "bacalhau-bras",
    "caldo-verde", "francesinha", "moussaka", "souvlaki", "spanakopita",
    "kleftiko", "youvetsi", "dakos", "imam-bayildi",
}

# slug, name, local, country, city, family, flavors, time, moods, ings, story
DISHES: list[tuple] = [
    # ── Italia 26 ──
    ("saltimbocca-alla-romana", "Saltimbocca a la romana", "Saltimbocca alla romana", "Italia", "Roma", "frito", "umami,herbal", 25, "impresionar,consuelo",
     "Ternera*8 medallones*res;Jamón crudo*8 lonchas*cerdo;Salvia*un manojo*cilantro;Vino blanco*100 ml*vino;Mantequilla*40 g*leche",
     "Roma clava una hoja de salvia sobre la ternera y el jamón: el salto a la boca no admite traducción."),
    ("bucatini-amatriciana", "Bucatini all'amatriciana", "Bucatini all'amatriciana", "Italia", "Amatrice", "fideo", "umami,picante", 35, "consuelo,fiesta",
     "Bucatini*400 g*fideos;Guanciale*150 g*cerdo;Tomate*400 g*tomate;Pecorino*80 g*queso;Guindilla*1*chile;Aceite*2 cdas*aceite",
     "Amatrice enseña que el guanciale, el tomate y el pecorino bastan para fundar una pasta."),
    ("parmigiana-melanzane", "Parmigiana de berenjena", "Parmigiana di melanzane", "Italia", "Nápoles", "estofado", "umami,dulce,cremoso", 70, "consuelo,fiesta",
     "Berenjena*4*tomate;Tomate*500 g*tomate;Mozzarella*250 g*queso;Parmesano*80 g*queso;Albahaca*un ramito*cilantro;Aceite*100 ml*aceite",
     "Nápoles apila berenjena, tomate y queso hasta que el horno los convierte en domingo."),
    ("vitello-tonnato", "Vitello tonnato", "Vitello tonnato", "Italia", "Turín", "crudo", "umami,cremoso,citrico", 90, "impresionar,ligero",
     "Ternera*600 g*res;Atún*150 g*pescado;Yema*2*huevo;Limón*1*limon;Alcaparras*2 cdas*sal;Aceite*80 ml*aceite",
     "Turín sirve la ternera fría bajo un velo de atún: el Piamonte en un silencio rosa."),
    ("brasato-al-barolo", "Brasato al Barolo", "Brasato al Barolo", "Italia", "Alba", "estofado", "umami,ahumado,herbal", 180, "consuelo,impresionar",
     "Tapa de res*1.2 kg*res;Barolo*750 ml*vino;Cebolla*2*cebolla;Zanahoria*2*tomate;Ajo*4 dientes*ajo;Romero*1 ramito*cilantro",
     "Alba cuece la res en Barolo hasta que el vino y la carne se perdonan."),
    ("risotto-alla-milanese", "Risotto a la milanesa", "Risotto alla milanese", "Italia", "Milán", "arroz", "umami,cremoso,dulce", 35, "impresionar,consuelo",
     "Arroz arborio*320 g*arroz;Azafrán*1 pizca*sal;Tuétano*40 g*res;Caldo*1 l*agua;Parmesano*80 g*queso;Cebolla*1*cebolla",
     "Milán tiñe el arroz de azafrán y tuétano: el lujo cabe en una cuchara."),
    ("cotoletta-alla-milanese", "Cotoletta a la milanesa", "Cotoletta alla milanese", "Italia", "Milán", "frito", "umami,citrico", 30, "consuelo,fiesta",
     "Chuleta de ternera*4*res;Huevo*2*huevo;Pan rallado*150 g*trigo;Mantequilla*80 g*leche;Limón*1*limon;Sal*al gusto*sal",
     "La cotoletta milanesa es hueso, pan rallado y un limón que no se discute."),
    ("polenta-taragna", "Polenta taragna", "Polenta taragna", "Italia", "Sondrio", "maiz", "cremoso,umami", 50, "consuelo",
     "Harina de maíz*250 g*maiz;Alforfón*150 g*trigo;Queso bitto*200 g*queso;Mantequilla*80 g*leche;Sal*al gusto*sal",
     "En Valtellina el maíz se casa con alforfón y bitto hasta espesar como manta."),
    ("farinata-di-ceci", "Farinata de garbanzo", "Farinata di ceci", "Italia", "Génova", "pan", "herbal,ahumado", 40, "ligero,fiesta",
     "Harina de garbanzo*250 g*garbanzo;Agua*750 ml*agua;Aceite de oliva*80 ml*aceite;Romero*1 ramito*cilantro;Sal*al gusto*sal",
     "Génova hornea el garbanzo en cobre: una lámina dorada que sabe a puerto."),
    ("orecchiette-cime-di-rapa", "Orecchiette con grelos", "Orecchiette alle cime di rapa", "Italia", "Bari", "fideo", "herbal,umami,picante", 35, "consuelo,ligero",
     "Orecchiette*400 g*fideos;Grelos*500 g*cilantro;Anchoas*4*pescado;Ajo*3 dientes*ajo;Guindilla*1*chile;Aceite*4 cdas*aceite",
     "Bari moldea orejas de pasta y las baña de grelos amargos y anchoa."),
    ("bistecca-alla-fiorentina", "Bistecca a la florentina", "Bistecca alla fiorentina", "Italia", "Florencia", "brasa", "umami,ahumado", 25, "fiesta,impresionar",
     "Chuletón de chianina*1.2 kg*res;Sal gruesa*al ras*sal;Aceite*un hilo*aceite;Limón*1*limon;Pimienta*al gusto*chile",
     "Florencia no adoba el chuletón: la brasa y la sal son toda la retórica."),
    ("pappa-al-pomodoro", "Pappa al pomodoro", "Pappa al pomodoro", "Italia", "Florencia", "caldo", "dulce,herbal,umami", 40, "consuelo,ligero",
     "Pan toscano*300 g*trigo;Tomate*800 g*tomate;Albahaca*un ramito*cilantro;Ajo*3 dientes*ajo;Aceite*5 cdas*aceite;Caldo*500 ml*agua",
     "El pan duro de Florencia revive en tomate y albahaca hasta volverse cuchara."),
    ("panzanella", "Panzanella", "Panzanella", "Italia", "Florencia", "crudo", "fresco,citrico,herbal", 20, "ligero,fiesta",
     "Pan toscano*250 g*trigo;Tomate*4*tomate;Pepino*1*limon;Cebolla morada*1*cebolla;Albahaca*un ramito*cilantro;Aceite*4 cdas*aceite",
     "El verano toscano se come empapado: pan, tomate y un aceite que perdona."),
    ("cacciucco-livornese", "Cacciucco livornés", "Cacciucco alla livornese", "Italia", "Livorno", "caldo", "umami,picante,ahumado", 70, "fiesta,consuelo",
     "Pescado de roca*800 g*pescado;Calamar y gamba*300 g*camaron;Tomate*400 g*tomate;Vino tinto*200 ml*vino;Ajo*4 dientes*ajo;Guindilla*1*chile",
     "Livorno junta cinco pescados en un caldo de vino y chile: el puerto cabe en un plato hondo."),
    ("pici-all-aglione", "Pici all'aglione", "Pici all'aglione", "Italia", "Siena", "fideo", "dulce,herbal,umami", 40, "consuelo,ligero",
     "Pici*400 g*fideos;Ajo ajolón*8 dientes*ajo;Tomate*500 g*tomate;Aceite*5 cdas*aceite;Albahaca*un ramito*cilantro;Sal*al gusto*sal",
     "Siena estira el trigo a mano y lo baña de ajolón dulce: la Val d'Orcia en hebra."),
    ("porchetta-di-aricia", "Porchetta de Ariccia", "Porchetta di Ariccia", "Italia", "Ariccia", "brasa", "ahumado,herbal,umami", 180, "fiesta,impresionar",
     "Panceta de cerdo*2 kg*cerdo;Hinojo silvestre*un manojo*cilantro;Ajo*8 dientes*ajo;Pimienta*al ras*chile;Sal*al gusto*sal;Vino blanco*100 ml*vino",
     "Ariccia rellena el cerdo de hinojo y lo gira hasta que la piel canta."),
    ("tagliatelle-al-ragu", "Tagliatelle al ragù", "Tagliatelle al ragù alla bolognese", "Italia", "Bolonia", "fideo", "umami,dulce,cremoso", 180, "consuelo,fiesta",
     "Tagliatelle*400 g*fideos;Carne picada mixta*400 g*res;Panceta*100 g*cerdo;Leche*200 ml*leche;Vino tinto*150 ml*vino;Tomate*300 g*tomate",
     "Bolonia no admite prisa: el ragù se cocina hasta que la leche y el vino se olvidan."),
    ("tortellini-in-brodo", "Tortellini in brodo", "Tortellini in brodo", "Italia", "Bolonia", "caldo", "umami,cremoso", 90, "consuelo,impresionar",
     "Tortellini*400 g*trigo;Carne de capón*300 g*pollo;Caldo de capón*1.5 l*agua;Parmesano*80 g*queso;Nuez moscada*1 pizca*canela;Sal*al gusto*sal",
     "El ombligo de Venus flota en caldo de capón: Navidad boloñesa en cucharón."),
    ("ragu-napoletano", "Ragù napolitano", "Ragù napoletano", "Italia", "Nápoles", "estofado", "umami,dulce", 240, "consuelo,fiesta",
     "Costilla de cerdo*800 g*cerdo;Chorizo fresco*300 g*cerdo;Tomate*1 kg*tomate;Cebolla*2*cebolla;Vino tinto*200 ml*vino;Albahaca*un ramito*cilantro",
     "Nápoles deja el domingo sobre el fuego: el ragù es un pacto de carne y tomate."),
    ("spaghetti-alla-puttanesca", "Spaghetti alla puttanesca", "Spaghetti alla puttanesca", "Italia", "Nápoles", "fideo", "umami,picante,citrico", 25, "fiesta,ligero",
     "Spaghetti*400 g*fideos;Anchoas*6*pescado;Aceitunas*80 g*sal;Alcaparras*2 cdas*limon;Tomate*400 g*tomate;Ajo*3 dientes*ajo",
     "Anchoa, alcaparra y aceituna: Nápoles inventa una salsa que no pide permiso."),
    ("pasta-e-fagioli", "Pasta e fagioli", "Pasta e fagioli", "Italia", "Nápoles", "fideo", "umami,cremoso,herbal", 50, "consuelo",
     "Pasta corta*250 g*fideos;Frijoles borlotti*400 g*frijol;Tomate*200 g*tomate;Ajo*3 dientes*ajo;Romero*1 ramito*cilantro;Aceite*3 cdas*aceite",
     "La pasta y el frijol se entienden en la olla napolitana como dos primos pobres."),
    ("sfogliatella", "Sfogliatella", "Sfogliatella riccia", "Italia", "Nápoles", "postre", "dulce,citrico,cremoso", 90, "fiesta,impresionar",
     "Masa hojaldrada*400 g*trigo;Ricotta*300 g*queso;Azúcar*80 g*azucar;Cáscara de naranja*2 cdas*naranja;Canela*1 pizca*canela;Huevo*1*huevo",
     "Cada capa de la sfogliatella es un pliegue del golfo: ricotta y cáscara de naranja."),
    ("pizza-fritta-napoletana", "Pizza fritta", "Pizza fritta napoletana", "Italia", "Nápoles", "frito", "umami,cremoso", 40, "fiesta,consuelo",
     "Masa de pizza*500 g*trigo;Ricotta*200 g*queso;Ciccioli*100 g*cerdo;Mozzarella*150 g*queso;Aceite para freír*500 ml*aceite;Sal*al gusto*sal",
     "Nápoles fríe la pizza cuando el horno no basta: ricotta y ciccioli en media luna."),
    ("suppli-al-telefono", "Supplì al telefono", "Supplì al telefono", "Italia", "Roma", "frito", "umami,cremoso", 45, "fiesta,consuelo",
     "Arroz*300 g*arroz;Mozzarella*150 g*queso;Salsa de tomate*200 g*tomate;Huevo*2*huevo;Pan rallado*100 g*trigo;Aceite*500 ml*aceite",
     "Roma fríe el risotto de ayer hasta que la mozzarella hace hilo de teléfono."),
    ("carciofi-alla-giudia", "Alcachofas a la judía", "Carciofi alla giudia", "Italia", "Roma", "frito", "herbal,citrico,ahumado", 35, "ligero,impresionar",
     "Alcachofas romanas*8*limon;Aceite*500 ml*aceite;Sal*al gusto*sal;Limón*1*limon;Ajo*2 dientes*ajo;Perejil*un ramito*cilantro",
     "El ghetto de Roma abre la alcachofa como una flor y la fríe hasta crujir."),
    ("coda-alla-vaccinara", "Coda alla vaccinara", "Coda alla vaccinara", "Italia", "Roma", "estofado", "umami,dulce,herbal", 180, "consuelo,impresionar",
     "Rabo de res*1.2 kg*res;Apio*4 tallos*cilantro;Tomate*400 g*tomate;Vino tinto*250 ml*vino;Cacao*1 cda*chocolate;Cebolla*2*cebolla",
     "Los vaccinari de Testaccio estofaron el rabo con apio y cacao: la quinta cuartel de la res."),
    # ── Francia 22 ──
    ("bouillabaisse", "Bouillabaisse", "Bouillabaisse", "Francia", "Marsella", "caldo", "umami,ahumado,citrico", 90, "fiesta,impresionar",
     "Pescado de roca*1.2 kg*pescado;Azafrán*1 pizca*sal;Hinojo*1*cilantro;Tomate*3*tomate;Ajo*4 dientes*ajo;Aceite*4 cdas*aceite",
     "Marsella no discute la bouillabaisse: el azafrán y la roca son el credo del puerto."),
    ("quiche-lorraine", "Quiche lorraine", "Quiche lorraine", "Francia", "Nancy", "desayuno", "cremoso,umami,ahumado", 50, "consuelo,fiesta",
     "Masa quebrada*1*trigo;Panceta*150 g*cerdo;Huevo*3*huevo;Nata*200 ml*leche;Queso gruyère*80 g*queso;Nuez moscada*1 pizca*canela",
     "Lorraine hornea nata, huevo y panceta hasta que el molde se sostiene solo."),
    ("confit-de-canard", "Confit de pato", "Confit de canard", "Francia", "Cahors", "estofado", "umami,ahumado,herbal", 180, "consuelo,impresionar",
     "Muslos de pato*4*pollo;Grasa de pato*500 g*aceite;Ajo*6 dientes*ajo;Tomillo*1 ramito*cilantro;Sal*al ras*sal;Pimienta*al gusto*chile",
     "Cahors sumerge el pato en su propia grasa: el tiempo hace lo que el fuego no debe."),
    ("blanquette-de-veau", "Blanquette de ternera", "Blanquette de veau", "Francia", "París", "estofado", "cremoso,umami,herbal", 120, "consuelo,impresionar",
     "Ternera*1 kg*res;Nata*200 ml*leche;Yema*2*huevo;Cebolla*2*cebolla;Champiñón*200 g*sal;Vino blanco*150 ml*vino",
     "París niega el dorado: la blanquette es ternera blanca, nata y un silencio de limón."),
    ("pot-au-feu", "Pot-au-feu", "Pot-au-feu", "Francia", "París", "caldo", "umami,herbal", 180, "consuelo,fiesta",
     "Morcillo de res*1 kg*res;Hueso de tuétano*2*res;Puerro*2*cebolla;Zanahoria*3*tomate;Clavo*4*canela;Sal*al gusto*sal",
     "El pot-au-feu es Francia en dos servicios: primero el caldo, después la carne que lo inventó."),
    ("soupe-a-loignon", "Sopa de cebolla", "Soupe à l'oignon", "Francia", "París", "caldo", "umami,dulce,ahumado", 70, "consuelo",
     "Cebolla*6*cebolla;Caldo de res*1.2 l*res;Pan*4 rebanadas*trigo;Gruyère*120 g*queso;Vino blanco*100 ml*vino;Mantequilla*40 g*leche",
     "París carameliza la cebolla hasta el cobrizo y la cubre de gruyère que se estira."),
    ("steak-frites", "Steak frites", "Steak frites", "Francia", "París", "brasa", "umami,ahumado", 25, "fiesta,consuelo",
     "Entrecot*2*res;Papa*800 g*papa;Mantequilla*40 g*leche;Sal*al gusto*sal;Aceite*para freír*aceite;Pimienta*al gusto*chile",
     "El bistró parisino no negocia: carne al punto y papa que cruje, nada más."),
    ("croque-monsieur", "Croque-monsieur", "Croque-monsieur", "Francia", "París", "pan", "cremoso,umami", 20, "consuelo,fiesta",
     "Pan de molde*8 rebanadas*trigo;Jamón*4 lonchas*cerdo;Gruyère*120 g*queso;Bechamel*200 ml*leche;Mantequilla*30 g*leche;Mostaza*1 cda*sal",
     "El croque-monsieur es el almuerzo de cincuentavos: jamón, bechamel y un gratinado que cierra."),
    ("tarte-tatin", "Tarta Tatin", "Tarte Tatin", "Francia", "Lamotte-Beuvron", "postre", "dulce,ahumado,citrico", 60, "impresionar,consuelo",
     "Manzana*8*fruta;Azúcar*150 g*azucar;Mantequilla*80 g*leche;Masa hojaldrada*1*trigo;Limón*1*limon;Canela*1 pizca*canela",
     "Las hermanas Tatin invirtieron la tarta y el caramelo perdonó el accidente."),
    ("madeleines-de-commercy", "Magdalenas de Commercy", "Madeleines de Commercy", "Francia", "Commercy", "postre", "dulce,citrico", 30, "consuelo,ligero",
     "Huevo*3*huevo;Azúcar*120 g*azucar;Harina*120 g*trigo;Mantequilla*120 g*leche;Limón*1*limon;Polvo de hornear*1 cta*sal",
     "Commercy hornea una concha de mantequilla: Proust no inventó el sabor, lo nombró."),
    ("galette-bretonne", "Galette bretona", "Galette complète", "Francia", "Rennes", "desayuno", "umami,cremoso,ahumado", 25, "consuelo,fiesta",
     "Harina de alforfón*200 g*trigo;Huevo*5*huevo;Jamón*4 lonchas*cerdo;Queso*80 g*queso;Mantequilla*40 g*leche;Leche*250 ml*leche",
     "Bretaña dobla el alforfón sobre huevo, jamón y queso: el completo cabe en un pliegue."),
    ("kouign-amann", "Kouign-amann", "Kouign-amann", "Francia", "Douarnenez", "postre", "dulce,cremoso,ahumado", 90, "impresionar,fiesta",
     "Harina*300 g*trigo;Mantequilla*250 g*leche;Azúcar*200 g*azucar;Levadura*8 g*sal;Agua*150 ml*agua;Sal*1 pizca*sal",
     "Douarnenez laminó mantequilla y azúcar hasta que el hojaldre crujió en bretón."),
    ("baeckeoffe", "Baeckeoffe", "Baeckeoffe", "Francia", "Estrasburgo", "estofado", "umami,herbal,ahumado", 180, "consuelo,fiesta",
     "Cerdo*400 g*cerdo;Res*400 g*res;Cordero*300 g*cordero;Papa*800 g*papa;Vino blanco de Alsacia*500 ml*vino;Puerro*2*cebolla",
     "El horno del panadero alsaciano custodia tres carnes y papa bajo un sello de masa."),
    ("tarte-flambee", "Tarta flambeada", "Flammekueche", "Francia", "Estrasburgo", "pan", "cremoso,ahumado,umami", 25, "fiesta,consuelo",
     "Masa fina*400 g*trigo;Nata*200 ml*leche;Panceta*120 g*cerdo;Cebolla*2*cebolla;Nuez moscada*1 pizca*canela;Sal*al gusto*sal",
     "Alsacia estira la masa como una hoja y la cubre de nata, cebolla y panceta."),
    ("daube-provencale", "Daube provenzal", "Daube provençale", "Francia", "Aviñón", "estofado", "umami,herbal,ahumado", 180, "consuelo,impresionar",
     "Carrillera de res*1.2 kg*res;Vino tinto*750 ml*vino;Naranja*1*naranja;Aceitunas*80 g*sal;Ajo*5 dientes*ajo;Tomillo*1 ramito*cilantro",
     "Aviñón marina la res en vino y naranja: la daube espera el lunes para saber a domingo."),
    ("soupe-au-pistou", "Sopa au pistou", "Soupe au pistou", "Francia", "Niza", "caldo", "herbal,fresco,umami", 60, "ligero,consuelo",
     "Alubias*300 g*frijol;Calabacín*2*tomate;Pasta corta*100 g*fideos;Albahaca*un manojo*cilantro;Ajo*3 dientes*ajo;Aceite*4 cdas*aceite",
     "Niza machaca albahaca y ajo sobre un caldo de verdura: el pistou es el Mediterráneo en cucharón."),
    ("pissaladiere", "Pissaladière", "Pissaladière", "Francia", "Niza", "pan", "dulce,umami,herbal", 50, "fiesta,ligero",
     "Masa de pan*400 g*trigo;Cebolla*6*cebolla;Anchoas*10*pescado;Aceitunas negras*80 g*sal;Aceite*5 cdas*aceite;Tomillo*1 ramito*cilantro",
     "Niza carameliza cebolla sobre masa y la firma con anchoa: la pizza que no se llama pizza."),
    ("socca", "Socca", "Socca", "Francia", "Niza", "pan", "ahumado,herbal", 25, "ligero,fiesta",
     "Harina de garbanzo*250 g*garbanzo;Agua*500 ml*agua;Aceite*80 ml*aceite;Pimienta*al gusto*chile;Sal*al gusto*sal;Romero*1 ramito*cilantro",
     "El cobre de Niza tuesta el garbanzo hasta el borde negro: la socca se come de pie."),
    ("aligot", "Aligot", "Aligot", "Francia", "Aubrac", "estofado", "cremoso,umami", 40, "consuelo,fiesta",
     "Papa*1 kg*papa;Tomme fraîche*400 g*queso;Nata*100 ml*leche;Ajo*2 dientes*ajo;Mantequilla*40 g*leche;Sal*al gusto*sal",
     "Aubrac estira la papa con tomme hasta que el hilo no se rompe: el aligot es oficio de muñeca."),
    ("tartiflette", "Tartiflette", "Tartiflette", "Francia", "Annecy", "estofado", "cremoso,ahumado,umami", 50, "consuelo,fiesta",
     "Papa*1 kg*papa;Reblochon*1*queso;Panceta*150 g*cerdo;Cebolla*2*cebolla;Nata*100 ml*leche;Vino blanco*80 ml*vino",
     "Annecy cubre la papa de reblochon fundido: la montaña se come con cuchara y nieve en la ventana."),
    ("gratin-dauphinois", "Gratin dauphinois", "Gratin dauphinois", "Francia", "Grenoble", "estofado", "cremoso,umami", 70, "consuelo,impresionar",
     "Papa*1.2 kg*papa;Nata*400 ml*leche;Ajo*2 dientes*ajo;Nuez moscada*1 pizca*canela;Mantequilla*30 g*leche;Sal*al gusto*sal",
     "El Delfinado lamina la papa en nata y ajo: el gratin no pide queso, pide paciencia."),
    ("canele-de-bordeaux", "Canelé de Burdeos", "Canelé de Bordeaux", "Francia", "Burdeos", "postre", "dulce,cremoso", 80, "impresionar,consuelo",
     "Leche*500 ml*leche;Yema*4*huevo;Azúcar*200 g*azucar;Harina*100 g*trigo;Vainilla*1 vaina*azucar;Ron*2 cdas*vino",
     "Burdeos hornea el canelé hasta el borde caramelizado y el centro de flan: el muelle en un bocado."),
    # ── España 20 ──
    ("cocido-madrileno", "Cocido madrileño", "Cocido madrileño", "España", "Madrid", "caldo", "umami,ahumado", 180, "consuelo,fiesta",
     "Garbanzo*400 g*garbanzo;Morcillo*400 g*res;Chorizo y morcilla*2 y 2*cerdo;Gallina*media*pollo;Papa*4*papa;Repollo*1*cilantro",
     "Madrid sirve el cocido en tres vuelcos: caldo, garbanzo y la carne que los sostuvo."),
    ("callos-a-la-madrilena", "Callos a la madrileña", "Callos a la madrileña", "España", "Madrid", "estofado", "umami,picante,ahumado", 150, "consuelo,fiesta",
     "Callos de ternera*1 kg*res;Chorizo*150 g*cerdo;Morcilla*150 g*cerdo;Pimentón*2 cdas*chile;Tomate*200 g*tomate;Ajo*4 dientes*ajo",
     "Los callos madrileños piden pimentón y morcilla: el invierno se come con cuchara de bar."),
    ("fabada-asturiana", "Fabada asturiana", "Fabada asturiana", "España", "Oviedo", "estofado", "umami,ahumado,cremoso", 180, "consuelo,fiesta",
     "Fabes*500 g*frijol;Compango*400 g*cerdo;Chorizo*2*cerdo;Morcilla asturiana*2*cerdo;Azafrán*1 pizca*sal;Agua*2 l*agua",
     "Asturias cuece la faba con el compango hasta que el caldo se vuelve manta."),
    ("pulpo-a-feira", "Pulpo a la gallega", "Polbo á feira", "España", "Ourense", "estofado", "umami,picante,citrico", 60, "fiesta,ligero",
     "Pulpo*1.5 kg*pescado;Papa*600 g*papa;Pimentón dulce y picante*2 cdas*chile;Aceite de oliva*80 ml*aceite;Sal gruesa*al ras*sal",
     "Ourense golpea el pulpo contra la piedra y lo corona de pimentón en plato de madera."),
    ("empanada-gallega", "Empanada gallega", "Empanada galega", "España", "A Coruña", "empanada", "umami,ahumado,herbal", 70, "fiesta,consuelo",
     "Harina*500 g*trigo;Atún o zamburiñas*400 g*pescado;Cebolla*3*cebolla;Pimiento*2*tomate;Aceite*100 ml*aceite;Pimentón*1 cda*chile",
     "Galicia cierra el mar entre dos masas: la empanada viaja mejor que el barco."),
    ("marmitako", "Marmitako", "Marmitako", "España", "Bermeo", "estofado", "umami,picante,ahumado", 50, "consuelo,fiesta",
     "Bonito*600 g*pescado;Papa*800 g*papa;Pimiento choricero*2*chile;Cebolla*2*cebolla;Tomate*2*tomate;Ajo*3 dientes*ajo",
     "La marmita del bonitero vasco cuaja papa y pimiento hasta que el atún entra al final."),
    ("bacalao-al-pil-pil", "Bacalao al pil-pil", "Bakailao pil-pilean", "España", "Bilbao", "estofado", "umami,cremoso,picante", 40, "impresionar,consuelo",
     "Bacalao*800 g*pescado;Ajo*8 dientes*ajo;Guindilla*2*chile;Aceite de oliva*250 ml*aceite;Perejil*un ramito*cilantro",
     "Bilbao mueve la cazuela hasta que el aceite y el bacalao emulsiona: el pil-pil es un oído."),
    ("chuleton-de-vaca", "Chuletón de buey", "Txuletón", "España", "Tolosa", "brasa", "umami,ahumado", 30, "fiesta,impresionar",
     "Chuletón de vaca vieja*1.2 kg*res;Sal gruesa*al ras*sal;Pimiento de Gernika*4*chile;Aceite*un hilo*aceite",
     "Tolosa no adoba el chuletón: la brasa vasca y la sal gorda firman el silencio."),
    ("ajo-blanco", "Ajo blanco", "Ajo blanco", "España", "Málaga", "crudo", "fresco,cremoso,citrico", 20, "ligero,impresionar",
     "Almendra*150 g*cacahuete;Ajo*2 dientes*ajo;Pan*80 g*trigo;Aceite*80 ml*aceite;Vinagre*2 cdas*limon;Uva*12*fruta",
     "Málaga licúa almendra y ajo hasta el blanco: la uva moscatel es el contrapunto."),
    ("salmorejo", "Salmorejo", "Salmorejo", "España", "Córdoba", "crudo", "dulce,fresco,umami", 20, "ligero,consuelo",
     "Tomate*1 kg*tomate;Pan*200 g*trigo;Ajo*1 diente*ajo;Aceite*150 ml*aceite;Huevo duro*2*huevo;Jamón*80 g*cerdo",
     "Córdoba espesa el tomate con pan hasta que el salmorejo se come con cuchara y jamón."),
    ("rabo-de-toro", "Rabo de toro", "Rabo de toro", "España", "Córdoba", "estofado", "umami,ahumado,dulce", 180, "consuelo,impresionar",
     "Rabo de toro*1.5 kg*res;Vino tinto*500 ml*vino;Cebolla*2*cebolla;Zanahoria*2*tomate;Ajo*4 dientes*ajo;Laurel*2 hojas*cilantro",
     "Córdoba estofa el rabo hasta que se rinde al vino: la plaza se come al día siguiente."),
    ("pescaito-frito", "Pescaíto frito", "Pescaíto frito", "España", "Cádiz", "frito", "citrico,umami,ahumado", 25, "fiesta,ligero",
     "Boquerón y pijota*600 g*pescado;Harina de garbanzo*150 g*garbanzo;Aceite de oliva*500 ml*aceite;Limón*2*limon;Sal*al gusto*sal",
     "Cádiz enharina el choco y el boquerón: el pescaíto se come de pie, con los dedos y el mar."),
    ("cochinillo-de-segovia", "Cochinillo de Segovia", "Cochinillo de Segovia", "España", "Segovia", "brasa", "umami,ahumado,cremoso", 120, "fiesta,impresionar",
     "Cochinillo*1*cerdo;Agua*200 ml*agua;Sal*al ras*sal;Manteca*2 cdas*aceite;Laurel*2 hojas*cilantro;Ajo*4 dientes*ajo",
     "Segovia parte el cochinillo con un plato: la piel debe ceder como si fuera oblea."),
    ("lechazo-asado", "Lechazo asado", "Lechazo asado", "España", "Aranda de Duero", "brasa", "umami,herbal,ahumado", 120, "fiesta,impresionar",
     "Lechazo*1.5 kg*cordero;Agua*150 ml*agua;Manteca*2 cdas*aceite;Sal*al ras*sal;Tomillo*1 ramito*cilantro",
     "Aranda hornea el lechazo en horno de leña: el cordero de leche no pide más que sal."),
    ("patatas-bravas", "Patatas bravas", "Patatas bravas", "España", "Madrid", "frito", "picante,ahumado,citrico", 35, "fiesta,consuelo",
     "Papa*800 g*papa;Tomate*200 g*tomate;Pimentón*1 cda*chile;Guindilla*1*chile;Ajo*2 dientes*ajo;Aceite*para freír*aceite",
     "Madrid fríe la papa y la cubre de bravura: el picante es un acuerdo de bar, no de receta."),
    ("pisto-manchego", "Pisto manchego", "Pisto manchego", "España", "Toledo", "estofado", "dulce,herbal,umami", 50, "consuelo,ligero",
     "Calabacín*2*tomate;Pimiento*2*chile;Tomate*4*tomate;Cebolla*2*cebolla;Huevo*4*huevo;Aceite*5 cdas*aceite",
     "La Mancha sofríe el huerto hasta el confitado: el pisto se corona de huevo y silencio."),
    ("arroz-negro", "Arroz negro", "Arròs negre", "España", "Barcelona", "arroz", "umami,ahumado", 50, "fiesta,impresionar",
     "Arroz*400 g*arroz;Tinta de calamar*2 sobres*pescado;Calamar*400 g*pescado;Caldo de pescado*1.2 l*agua;Ajo*3 dientes*ajo;Ñora*1*chile",
     "Barcelona tiñe el grano de tinta: el arroz negro pide alioli y no pide disculpas."),
    ("escalivada", "Escalivada", "Escalivada", "España", "Barcelona", "brasa", "ahumado,dulce,herbal", 50, "ligero,fiesta",
     "Berenjena*2*tomate;Pimiento rojo*3*chile;Cebolla*2*cebolla;Aceite*4 cdas*aceite;Ajo*2 dientes*ajo;Sal*al gusto*sal",
     "Cataluña cubre la verdura de brasa hasta la piel negra: la escalivada se pela con los dedos."),
    ("crema-catalana", "Crema catalana", "Crema catalana", "España", "Girona", "postre", "dulce,citrico,cremoso", 40, "impresionar,consuelo",
     "Yema*8*huevo;Leche*1 l*leche;Azúcar*150 g*azucar;Cáscara de limón*1*limon;Canela*1 rama*canela;Almidón*2 cdas*trigo",
     "Girona quema el azúcar con un hierro: la crema catalana cruje antes de rendirse al limón."),
    ("papas-arrugadas", "Papas arrugadas", "Papas arrugadas con mojo", "España", "La Laguna", "estofado", "picante,citrico,ahumado", 40, "fiesta,ligero",
     "Papa bonita*1 kg*papa;Sal marina*200 g*sal;Pimiento choricero*4*chile;Ajo*4 dientes*ajo;Comino*1 cta*canela;Vinagre*2 cdas*limon",
     "Tenerife cuece la papa en agua de mar y la moja de mojo rojo: el Atlántico cabe en un cuenco."),
    # ── Reino Unido 16 ──
    ("sunday-roast", "Sunday roast", "Sunday roast", "Reino Unido", "York", "brasa", "umami,herbal,ahumado", 120, "fiesta,consuelo",
     "Solomillo de res*1.2 kg*res;Papa*800 g*papa;Zanahoria*4*tomate;Yorkshire pudding*4*trigo;Gravy*300 ml*res;Romero*1 ramito*cilantro",
     "York asó el domingo entero: la res, la papa y el gravy son la liturgia británica."),
    ("yorkshire-pudding", "Yorkshire pudding", "Yorkshire pudding", "Reino Unido", "York", "pan", "umami,cremoso", 40, "consuelo,fiesta",
     "Harina*150 g*trigo;Huevo*3*huevo;Leche*200 ml*leche;Grasa de asado*4 cdas*res;Sal*1 pizca*sal",
     "El pudding de York sube en la grasa caliente como un globo salado que pide gravy."),
    ("bangers-and-mash", "Bangers and mash", "Bangers and mash", "Reino Unido", "Londres", "estofado", "umami,cremoso,herbal", 40, "consuelo",
     "Salchichas*8*cerdo;Papa*1 kg*papa;Cebolla*3*cebolla;Mantequilla*60 g*leche;Leche*100 ml*leche;Tomillo*1 ramito*cilantro",
     "Londres responde al frío con salchicha, puré y una salsa de cebolla que consuela."),
    ("toad-in-the-hole", "Toad in the hole", "Toad in the hole", "Reino Unido", "Sheffield", "pan", "umami,cremoso", 50, "consuelo,fiesta",
     "Salchichas*6*cerdo;Harina*150 g*trigo;Huevo*3*huevo;Leche*200 ml*leche;Grasa*2 cdas*aceite;Sal*al gusto*sal",
     "Sheffield hunde la salchicha en rebozado: el sapo del horno es un chiste que se come."),
    ("cottage-pie", "Cottage pie", "Cottage pie", "Reino Unido", "Londres", "estofado", "umami,cremoso,herbal", 70, "consuelo,fiesta",
     "Carne picada de res*600 g*res;Papa*1 kg*papa;Zanahoria*2*tomate;Cebolla*2*cebolla;Guisantes*100 g*frijol;Mantequilla*50 g*leche",
     "El cottage pie cubre la res con puré gratinado: el pastor se queda con el cordero, la casa con la vaca."),
    ("cornish-pasty", "Cornish pasty", "Cornish pasty", "Reino Unido", "Penzance", "empanada", "umami,herbal", 60, "consuelo,fiesta",
     "Harina*400 g*trigo;Falda de res*350 g*res;Papa*200 g*papa;Nabo*150 g*tomate;Cebolla*1*cebolla;Manteca*120 g*aceite",
     "Cornualles cerró el almuerzo del minero en un crimp: la pasty se come por el mango de masa."),
    ("scotch-egg", "Scotch egg", "Scotch egg", "Reino Unido", "Londres", "frito", "umami,cremoso", 40, "fiesta,consuelo",
     "Huevo*6*huevo;Salchicha*400 g*cerdo;Pan rallado*100 g*trigo;Harina*50 g*trigo;Aceite*500 ml*aceite;Mostaza*para servir*sal",
     "Londres envuelve el huevo en carne y lo fríe: el picnic cabe en la palma."),
    ("haggis", "Haggis", "Haggis", "Reino Unido", "Edimburgo", "estofado", "umami,herbal,ahumado", 90, "fiesta,consuelo",
     "Asaduras de cordero*400 g*cordero;Avena*150 g*trigo;Cebolla*2*cebolla;Sebo*100 g*aceite;Pimienta de Jamaica*1 cda*chile;Sal*al gusto*sal",
     "Edimburgo cuece el haggis en su propia bolsa: Burns lo recitó, Escocia lo come con neeps."),
    ("cullen-skink", "Cullen skink", "Cullen skink", "Reino Unido", "Cullen", "caldo", "ahumado,cremoso,umami", 40, "consuelo",
     "Eglefino ahumado*400 g*pescado;Papa*500 g*papa;Leche*500 ml*leche;Cebolla*1*cebolla;Mantequilla*30 g*leche;Cebollino*un ramito*cilantro",
     "Cullen hace sopa del eglefino ahumado: el skink es el mar del Norte en una taza."),
    ("welsh-rarebit", "Welsh rarebit", "Welsh rarebit", "Reino Unido", "Cardiff", "pan", "umami,picante,cremoso", 20, "consuelo,fiesta",
     "Pan*4 rebanadas*trigo;Queso cheddar*200 g*queso;Cerveza*80 ml*vino;Mostaza*1 cda*sal;Worcestershire*1 cda*soya;Huevo*1 yema*huevo",
     "Gales funde cheddar con cerveza sobre el pan tostado: el rarebit es un conejo que nunca lo fue."),
    ("eton-mess", "Eton mess", "Eton mess", "Reino Unido", "Eton", "postre", "dulce,fresco,cremoso", 20, "fiesta,ligero",
     "Fresas*400 g*fruta;Nata*300 ml*leche;Merengue*80 g*azucar;Azúcar*2 cdas*azucar;Limón*1 cda*limon",
     "Eton destrozó el merengue y la fresa: el desorden del internado se come con cuchara."),
    ("lancashire-hotpot", "Lancashire hotpot", "Lancashire hotpot", "Reino Unido", "Lancaster", "estofado", "umami,herbal,ahumado", 150, "consuelo,fiesta",
     "Paletilla de cordero*1 kg*cordero;Papa*800 g*papa;Cebolla*3*cebolla;Caldo*500 ml*agua;Tomillo*1 ramito*cilantro;Mantequilla*30 g*leche",
     "Lancashire tapa el cordero con tejas de papa: el hotpot espera en el horno mientras el turno acaba."),
    ("steak-and-kidney-pie", "Steak and kidney pie", "Steak and kidney pie", "Reino Unido", "Londres", "empanada", "umami,herbal,ahumado", 120, "consuelo,fiesta",
     "Res*500 g*res;Riñón*200 g*res;Masa hojaldrada*1*trigo;Cebolla*2*cebolla;Cerveza negra*200 ml*vino;Tomillo*1 ramito*cilantro",
     "Londres encierra res y riñón bajo hojaldre: el pie humea como un pub un viernes."),
    ("chicken-tikka-masala", "Chicken tikka masala", "Chicken tikka masala", "Reino Unido", "Glasgow", "curry", "picante,cremoso,ahumado", 50, "fiesta,consuelo",
     "Pollo*700 g*pollo;Yogur*150 g*yogurt;Tomate*400 g*tomate;Nata*100 ml*leche;Garam masala*2 cdas*chile;Jengibre*1 trozo*jengibre",
     "Glasgow tiñó de crema el tikka: el curry británico nació entre el tandoor y la lluvia."),
    ("cock-a-leekie", "Cock-a-leekie", "Cock-a-leekie", "Reino Unido", "Edimburgo", "caldo", "umami,dulce,herbal", 90, "consuelo",
     "Pollo*1*pollo;Puerro*4*cebolla;Ciruela pasa*12*fruta;Caldo*1.5 l*agua;Perejil*un ramito*cilantro;Sal*al gusto*sal",
     "Edimburgo cuece el gallo con puerro y ciruela: el caldo escocés endulza sin pedir postre."),
    ("welsh-cakes", "Welsh cakes", "Pice ar y maen", "Reino Unido", "Cardiff", "postre", "dulce,cremoso", 25, "consuelo,fiesta",
     "Harina*250 g*trigo;Manteca*110 g*leche;Azúcar*80 g*azucar;Pasa*80 g*fruta;Huevo*1*huevo;Canela*1 cta*canela",
     "Gales tuesta la tortita en piedra: la welsh cake cabe en el bolsillo y en el té."),
    # ── Alemania 16 ──
    ("nuremberger-rostbratwurst", "Nürnberger Rostbratwurst", "Nürnberger Rostbratwurst", "Alemania", "Núremberg", "brasa", "ahumado,herbal,umami", 25, "fiesta,consuelo",
     "Bratwurst de Núremberg*12*cerdo;Mostaza*para servir*sal;Pan*4*trigo;Mejorana*1 cda*cilantro;Aceite*1 cda*aceite",
     "Núremberg asa las salchichas delgadas a docenas: la mostaza y el pan son el resto del discurso."),
    ("currywurst", "Currywurst", "Currywurst", "Alemania", "Berlín", "frito", "picante,dulce,umami", 20, "fiesta,consuelo",
     "Bratwurst*4*cerdo;Kétchup*150 ml*tomate;Curry en polvo*2 cdas*chile;Aceite*2 cdas*aceite;Papa frita*para servir*papa",
     "Berlín inventó el currywurst entre escombros: el polvo amarillo sobre la salchicha es historia."),
    ("eisbein", "Eisbein", "Eisbein", "Alemania", "Berlín", "estofado", "umami,ahumado", 150, "consuelo,fiesta",
     "Codillo curado*1.2 kg*cerdo;Chucrut*500 g*limon;Papa*600 g*papa;Laurel*2 hojas*cilantro;Pimienta*al gusto*chile;Mostaza*para servir*sal",
     "Berlín cuece el codillo hasta que el hueso brilla: el eisbein pide chucrut y una cerveza larga."),
    ("koenigsberger-klopse", "Königsberger Klopse", "Königsberger Klopse", "Alemania", "Berlín", "estofado", "cremoso,citrico,umami", 50, "consuelo,impresionar",
     "Carne picada de ternera*500 g*res;Anchoa*4*pescado;Alcaparra*2 cdas*limon;Nata*150 ml*leche;Huevo*1*huevo;Caldo*700 ml*agua",
     "Königsberg aderezó la albóndiga de alcaparra y anchoa: Berlín la heredó con salsa blanca."),
    ("labskaus", "Labskaus", "Labskaus", "Alemania", "Hamburgo", "estofado", "ahumado,umami,citrico", 40, "consuelo",
     "Corned beef*400 g*res;Papa*600 g*papa;Remolacha*200 g*tomate;Arenque*4*pescado;Huevo*4*huevo;Cebolla*2*cebolla",
     "Hamburgo machaca res curada, papa y remolacha: el labskaus es el desayuno del muelle."),
    ("rindrouladen", "Rinderrouladen", "Rinderrouladen", "Alemania", "Colonia", "estofado", "umami,herbal,ahumado", 120, "consuelo,fiesta",
     "Filete de res*4*res;Bacon*4 lonchas*cerdo;Pepinillo*4*limon;Cebolla*2*cebolla;Mostaza*2 cdas*sal;Caldo*400 ml*agua",
     "Colonia enrolla la res con pepinillo y bacon: el rollo se estima en salsa oscura."),
    ("reibekuchen", "Reibekuchen", "Reibekuchen", "Alemania", "Düsseldorf", "frito", "ahumado,dulce", 30, "fiesta,consuelo",
     "Papa*1 kg*papa;Cebolla*1*cebolla;Huevo*2*huevo;Harina*3 cdas*trigo;Aceite*para freír*aceite;Compota de manzana*para servir*fruta",
     "Düsseldorf ralla la papa y la fríe en tortita: el Reibekuchen pide manzana y feria."),
    ("schweinshaxe", "Schweinshaxe", "Schweinshaxe", "Alemania", "Múnich", "brasa", "ahumado,umami", 150, "fiesta,consuelo",
     "Codillo de cerdo*1.4 kg*cerdo;Cerveza*300 ml*vino;Ajo*4 dientes*ajo;Comino*1 cta*canela;Sal*al ras*sal;Chucrut*para servir*limon",
     "Múnich asa el codillo hasta la corteza de cristal: la cerveza baña lo que el horno tuesta."),
    ("weisswurst", "Weisswurst", "Weißwurst", "Alemania", "Múnich", "caldo", "herbal,umami,cremoso", 25, "desayuno,consuelo".replace("desayuno,", "") if False else "consuelo,fiesta",
     "Weisswurst*8*cerdo;Perejil*un ramito*cilantro;Leche*50 ml*leche;Pretzel*4*trigo;Mostaza dulce*para servir*sal;Agua*1 l*agua",
     "Múnich no deja que la weisswurst vea el mediodía: se pela con los dedos y mostaza dulce."),
    ("maultaschen", "Maultaschen", "Maultaschen", "Alemania", "Stuttgart", "empanada", "umami,herbal", 60, "consuelo,fiesta",
     "Masa de pasta*400 g*trigo;Carne picada*250 g*res;Espinaca*200 g*cilantro;Cebolla*1*cebolla;Huevo*1*huevo;Caldo*1 l*agua",
     "Suabia escondió la carne en pasta para el Viernes Santo: el Maultaschen es un secreto comestible."),
    ("linsen-spaetzle", "Lentejas con spätzle", "Linsen mit Spätzle", "Alemania", "Stuttgart", "fideo", "umami,citrico,herbal", 50, "consuelo",
     "Spätzle*400 g*fideos;Lenteja*300 g*lenteja;Salchicha Saitenwurst*4*cerdo;Vinagre*2 cdas*limon;Cebolla*1*cebolla;Laurel*1 hoja*cilantro",
     "Stuttgart cubre el spätzle de lenteja agria: el plato suabo pide salchicha al lado, no encima."),
    ("gruenkohl-pinkel", "Grünkohl mit Pinkel", "Grünkohl mit Pinkel", "Alemania", "Bremen", "estofado", "herbal,ahumado,umami", 90, "consuelo,fiesta",
     "Col rizada*1 kg*cilantro;Pinkel*400 g*cerdo;Papa*500 g*papa;Avena*en la salchicha*trigo;Cebolla*2*cebolla;Mostaza*1 cda*sal",
     "Bremen cuece la col con la salchicha de avena: el invierno del norte se come después de la caminata."),
    ("dresdner-stollen", "Stollen de Dresde", "Dresdner Christstollen", "Alemania", "Dresde", "postre", "dulce,citrico,cremoso", 90, "fiesta,consuelo",
     "Harina*500 g*trigo;Mantequilla*250 g*leche;Fruta confitada*200 g*fruta;Almendra*80 g*cacahuete;Azúcar glas*80 g*azucar;Cáscara de limón*1*limon",
     "Dresde hornea el stollen como un niño envuelto: la mantequilla y la fruta son el Adviento."),
    ("nuremberger-lebkuchen", "Lebkuchen", "Nürnberger Lebkuchen", "Alemania", "Núremberg", "postre", "dulce,herbal,citrico", 40, "fiesta,consuelo",
     "Almendra*200 g*cacahuete;Miel*150 g*azucar;Especias*2 cdas*canela;Cáscara de naranja*2 cdas*naranja;Huevo*2*huevo;Oblea*12*trigo",
     "Núremberg perfuma la miel con especias: el lebkuchen es feria y canela sobre oblea."),
    ("thueringer-rostbratwurst", "Thüringer Rostbratwurst", "Thüringer Rostbratwurst", "Alemania", "Erfurt", "brasa", "ahumado,herbal,umami", 20, "fiesta,consuelo",
     "Thüringer bratwurst*6*cerdo;Mostaza*para servir*sal;Pan*4*trigo;Mejorana*1 cda*cilantro;Comino*1 pizca*canela",
     "Turingia asa la bratwurst al fuego de leña: la receta está protegida, el humo no."),
    ("kartoffelsalat-schwaebisch", "Ensalada de papa suaba", "Schwäbischer Kartoffelsalat", "Alemania", "Stuttgart", "crudo", "citrico,herbal,umami", 30, "ligero,consuelo",
     "Papa*1 kg*papa;Caldo de res*150 ml*res;Vinagre*3 cdas*limon;Cebolla*1*cebolla;Mostaza*1 cda*sal;Aceite*3 cdas*aceite",
     "Suabia veste la papa de caldo y vinagre: la ensalada se sirve tibia, nunca de mayonesa."),
    # ── Portugal 14 ──
    ("bacalhau-gomes-de-sa", "Bacalhau à Gomes de Sá", "Bacalhau à Gomes de Sá", "Portugal", "Oporto", "estofado", "umami,cremoso,herbal", 50, "consuelo,fiesta",
     "Bacalao*600 g*pescado;Papa*600 g*papa;Cebolla*3*cebolla;Huevo*4*huevo;Aceituna*80 g*sal;Aceite*5 cdas*aceite",
     "Oporto lamina bacalao, papa y cebolla: Gomes de Sá dejó el sábado en una fuente."),
    ("bacalhau-com-natas", "Bacalhau com natas", "Bacalhau com natas", "Portugal", "Lisboa", "estofado", "cremoso,umami,ahumado", 50, "consuelo,impresionar",
     "Bacalao*600 g*pescado;Papa*500 g*papa;Nata*300 ml*leche;Cebolla*2*cebolla;Ajo*2 dientes*ajo;Queso*80 g*queso",
     "Lisboa gratinó el bacalao con nata: el horno cierra lo que el Atlántico abrió."),
    ("cataplana-de-marisco", "Cataplana de marisco", "Cataplana de marisco", "Portugal", "Faro", "estofado", "umami,picante,citrico", 45, "fiesta,impresionar",
     "Almeja y gamba*800 g*camaron;Chorizo*80 g*cerdo;Tomate*3*tomate;Ajo*4 dientes*ajo;Vino blanco*150 ml*vino;Cilantro*un ramito*cilantro",
     "El Algarve cierra el cobre de la cataplana: el marisco se cuece en su propio vapor."),
    ("arroz-de-pato", "Arroz de pato", "Arroz de pato", "Portugal", "Braga", "arroz", "umami,ahumado,herbal", 70, "consuelo,fiesta",
     "Pato*1*pollo;Arroz*400 g*arroz;Chorizo*100 g*cerdo;Caldo*1 l*agua;Naranja*1*naranja;Ajo*3 dientes*ajo",
     "Braga hornea el arroz con el caldo del pato y lo corona de chorizo: el domingo en cazuela."),
    ("cozido-a-portuguesa", "Cozido à portuguesa", "Cozido à portuguesa", "Portugal", "Lisboa", "caldo", "umami,ahumado", 180, "fiesta,consuelo",
     "Carne de res*400 g*res;Cerdo*400 g*cerdo;Chorizo*200 g*cerdo;Garbanzo*200 g*garbanzo;Papa*4*papa;Repollo*1*cilantro",
     "Portugal cuece todas las carnes en una sola olla: el cozido es el país sentado a la mesa."),
    ("ameijoas-bulhao-pato", "Almejas à Bulhão Pato", "Amêijoas à Bulhão Pato", "Portugal", "Lisboa", "caldo", "citrico,herbal,umami", 20, "ligero,fiesta",
     "Almeja*1 kg*camaron;Ajo*5 dientes*ajo;Cilantro*un manojo*cilantro;Vino blanco*100 ml*vino;Limón*1*limon;Aceite*4 cdas*aceite",
     "Lisboa abre las almejas con ajo, cilantro y un chorro de verde: Bulhão Pato escribió el resto."),
    ("bifana", "Bifana", "Bifana", "Portugal", "Lisboa", "pan", "picante,umami,citrico", 20, "fiesta,consuelo",
     "Lomo de cerdo*400 g*cerdo;Pan*4*trigo;Ajo*4 dientes*ajo;Piri-piri*1 cda*chile;Vino blanco*80 ml*vino;Laurel*1 hoja*cilantro",
     "La bifana se come de pie: el cerdo marinado cabe en un pan que no perdona el jugo."),
    ("sardinhas-assadas", "Sardinas asadas", "Sardinhas assadas", "Portugal", "Lisboa", "brasa", "ahumado,citrico,umami", 20, "fiesta,ligero",
     "Sardina*12*pescado;Pimiento*4*chile;Pan*4 rebanadas*trigo;Sal gruesa*al ras*sal;Limón*1*limon;Aceite*2 cdas*aceite",
     "Lisboa huele a sardina en junio: la brasa y el pan absorben lo que el Santo António celebra."),
    ("polvo-a-lagareiro", "Pulpo à lagareiro", "Polvo à lagareiro", "Portugal", "Nazaré", "brasa", "ahumado,herbal,umami", 70, "fiesta,impresionar",
     "Pulpo*1.2 kg*pescado;Papa*600 g*papa;Ajo*8 dientes*ajo;Aceite de oliva*120 ml*aceite;Cilantro*un ramito*cilantro;Sal*al gusto*sal",
     "Nazaré baña el pulpo de aceite de lagar: el ajo chasquea sobre la papa arrugada."),
    ("acorda-alentejana", "Açorda alentejana", "Açorda alentejana", "Portugal", "Évora", "caldo", "herbal,citrico,umami", 25, "consuelo,ligero",
     "Pan alentejano*300 g*trigo;Ajo*4 dientes*ajo;Cilantro*un manojo*cilantro;Huevo*4*huevo;Aceite*5 cdas*aceite;Agua*800 ml*agua",
     "El Alentejo machaca ajo y cilantro sobre pan: el huevo poché cierra la açorda."),
    ("leitao-da-bairrada", "Leitão da Bairrada", "Leitão da Bairrada", "Portugal", "Mealhada", "brasa", "ahumado,herbal,umami", 120, "fiesta,impresionar",
     "Lechón*1*cerdo;Manteca*80 g*aceite;Ajo*8 dientes*ajo;Pimienta blanca*al ras*chile;Sal*al gusto*sal;Laurel*2 hojas*cilantro",
     "Mealhada asa el lechón hasta la piel de cristal: la Bairrada se come con las manos."),
    ("carne-de-porco-alentejana", "Carne de porco à alentejana", "Carne de porco à alentejana", "Portugal", "Évora", "estofado", "umami,citrico,picante", 50, "fiesta,consuelo",
     "Cerdo*700 g*cerdo;Almeja*500 g*camaron;Papa frita*400 g*papa;Ajo*4 dientes*ajo;Pimentón*1 cda*chile;Cilantro*un ramito*cilantro",
     "Évora casó el cerdo con la almeja: el Alentejo cabe en una cazuela de dos mares."),
    ("arroz-de-marisco", "Arroz de marisco", "Arroz de marisco", "Portugal", "Aveiro", "arroz", "umami,citrico,herbal", 50, "fiesta,impresionar",
     "Arroz*400 g*arroz;Marisco mixto*800 g*camaron;Tomate*3*tomate;Cilantro*un ramito*cilantro;Vino blanco*150 ml*vino;Ajo*3 dientes*ajo",
     "Aveiro cuece el arroz en el caldo del marisco: el grano queda meloso, nunca seco."),
    ("ovos-moles-de-aveiro", "Ovos moles de Aveiro", "Ovos moles de Aveiro", "Portugal", "Aveiro", "postre", "dulce,cremoso", 40, "impresionar,fiesta",
     "Yema*12*huevo;Azúcar*400 g*azucar;Agua*200 ml*agua;Hostia*para envolver*trigo;Canela*1 pizca*canela",
     "Aveiro guardó las yemas de las monjas en una concha de barco: el dulce es un secreto de ría."),
    # ── Grecia 14 ──
    ("pastitsio", "Pastitsio", "Παστίτσιο", "Grecia", "Atenas", "fideo", "umami,cremoso,dulce", 70, "consuelo,fiesta",
     "Macarrones*400 g*fideos;Carne picada*500 g*res;Bechamel*500 ml*leche;Tomate*200 g*tomate;Canela*1 cta*canela;Queso*100 g*queso",
     "Atenas apila pasta, carne y bechamel: el pastitsio es el domingo en tres capas."),
    ("gemista", "Gemista", "Γεμιστά", "Grecia", "Atenas", "estofado", "herbal,dulce,umami", 80, "ligero,fiesta",
     "Tomate*6*tomate;Pimiento*4*chile;Arroz*200 g*arroz;Cebolla*2*cebolla;Hierbabuena*un ramito*cilantro;Aceite*80 ml*aceite",
     "Atenas rellena el tomate de arroz y hierbabuena: el horno confita lo que el huerto dio."),
    ("stifado", "Stifado", "Στιφάδο", "Grecia", "Corfú", "estofado", "umami,dulce,herbal", 120, "consuelo,impresionar",
     "Res o conejo*1 kg*res;Cebollitas*500 g*cebolla;Vino tinto*200 ml*vino;Canela*1 rama*canela;Tomate*300 g*tomate;Vinagre*2 cdas*limon",
     "Corfú estofa la carne con cebollita y canela: el stifado huele a isla y a clavo."),
    ("fasolada", "Fasolada", "Φασολάδα", "Grecia", "Atenas", "caldo", "herbal,umami,citrico", 90, "consuelo,ligero",
     "Alubia blanca*400 g*frijol;Zanahoria*2*tomate;Apio*2 tallos*cilantro;Tomate*200 g*tomate;Aceite*80 ml*aceite;Cebolla*2*cebolla",
     "La fasolada es el plato nacional que no sale en las postales: alubia, aceite y invierno."),
    ("gigantes-plaki", "Gigantes plaki", "Γίγαντες πλακί", "Grecia", "Tesalónica", "estofado", "herbal,dulce,umami", 80, "consuelo,ligero",
     "Judión*400 g*frijol;Tomate*400 g*tomate;Apio*2 tallos*cilantro;Cebolla*2*cebolla;Aceite*80 ml*aceite;Perejil*un ramito*cilantro",
     "Tesalónica hornea los judiones en tomate: los gigantes se rinden al aceite y al horno lento."),
    ("keftedes", "Keftedes", "Κεφτέδες", "Grecia", "Atenas", "frito", "herbal,umami,citrico", 35, "fiesta,consuelo",
     "Carne picada*500 g*res;Cebolla*1*cebolla;Menta*un ramito*cilantro;Huevo*1*huevo;Pan*80 g*trigo;Aceite*para freír*aceite",
     "Atenas fríe la albóndiga con menta: el keftes se come con tzatziki y la mano."),
    ("paidakia", "Paidakia", "Παϊδάκια", "Grecia", "Atenas", "brasa", "ahumado,herbal,citrico", 30, "fiesta,impresionar",
     "Costillas de cordero*1 kg*cordero;Orégano*2 cdas*cilantro;Limón*2*limon;Aceite*4 cdas*aceite;Ajo*3 dientes*ajo;Sal*al gusto*sal",
     "El cordero griego se asa con orégano y limón: las paidakia se roen junto al fuego."),
    ("horiatiki", "Ensalada horiatiki", "Χωριάτικη σαλάτα", "Grecia", "Atenas", "crudo", "fresco,citrico,herbal", 15, "ligero,fiesta",
     "Tomate*4*tomate;Pepino*1*limon;Queso feta*200 g*queso;Aceituna*80 g*sal;Cebolla*1*cebolla;Aceite*4 cdas*aceite",
     "La aldea griega no mezcla la ensalada: el feta se sienta entero sobre el tomate."),
    ("avgolemono", "Avgolemono", "Αυγολέμονο", "Grecia", "Atenas", "caldo", "citrico,cremoso,umami", 50, "consuelo,ligero",
     "Pollo*media*pollo;Huevo*2*huevo;Limón*2*limon;Arroz*100 g*arroz;Caldo*1.2 l*agua;Sal*al gusto*sal",
     "Atenas liga el caldo de pollo con yema y limón: el avgolemono es un hilo que no debe cortarse."),
    ("loukoumades", "Loukoumades", "Λουκουμάδες", "Grecia", "Atenas", "postre", "dulce,citrico", 30, "fiesta,consuelo",
     "Harina*250 g*trigo;Miel*150 g*azucar;Levadura*8 g*sal;Agua*200 ml*agua;Canela*1 cta*canela;Aceite*para freír*aceite",
     "Atenas fríe buñuelos y los baña de miel: el loukoumas humea en la feria y en la fiesta."),
    ("galaktoboureko", "Galaktoboureko", "Γαλακτομπούρεκο", "Grecia", "Atenas", "postre", "dulce,cremoso,citrico", 70, "impresionar,consuelo",
     "Leche*1 l*leche;Sémola*120 g*trigo;Filo*10 hojas*trigo;Azúcar*300 g*azucar;Limón*1*limon;Mantequilla*120 g*leche",
     "El filo cruje sobre una crema de sémola: Atenas perfuma el almíbar de limón y canela."),
    ("bougatsa", "Bougatsa", "Μπουγάτσα", "Grecia", "Tesalónica", "postre", "dulce,cremoso,canela".replace("canela", "citrico") if True else "dulce,cremoso",
     "Filo*8 hojas*trigo;Crema de sémola*500 ml*leche;Azúcar*80 g*azucar;Canela*1 cda*canela;Mantequilla*80 g*leche;Huevo*2*huevo",
     "Tesalónica parte la bougatsa con un cuchillo y la espolvorea de canela al amanecer."),
    ("saganaki", "Saganaki", "Σαγανάκι", "Grecia", "Tesalónica", "frito", "umami,citrico,cremoso", 15, "fiesta,ligero",
     "Queso kefalotyri*300 g*queso;Harina*50 g*trigo;Aceite*4 cdas*aceite;Limón*1*limon;Orégano*1 pizca*cilantro",
     "Tesalónica dora el queso en la sartén saganaki: el limón apaga lo que el fuego grita."),
    ("fava-santorinis", "Fava de Santorini", "Φάβα Σαντορίνης", "Grecia", "Fira", "crudo", "cremoso,citrico,herbal", 40, "ligero,impresionar",
     "Guisante amarillo*300 g*lenteja;Cebolla*2*cebolla;Limón*1*limon;Alcaparra*2 cdas*sal;Aceite*5 cdas*aceite;Orégano*1 pizca*cilantro",
     "Santorini puré de guisante volcánico: la fava se come tibia, con cebolla y alcaparra."),
]
