/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListaRouteImport } from './routes/lista'
import { Route as ViajeRouteImport } from './routes/viaje'
import { Route as DestinoIdRouteImport } from './routes/destino.$id'
import { Route as PaisSlugRouteImport } from './routes/pais.$slug'
import { Route as RecipeSlugRouteImport } from './routes/recipe.$slug'
import { Route as TipoIdRouteImport } from './routes/tipo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaRoute = ListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const ViajeRoute = ViajeRouteImport.update({
  id: '/viaje',
  path: '/viaje',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinoIdRoute = DestinoIdRouteImport.update({
  id: '/destino/$id',
  path: '/destino/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaisSlugRoute = PaisSlugRouteImport.update({
  id: '/pais/$slug',
  path: '/pais/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeSlugRoute = RecipeSlugRouteImport.update({
  id: '/recipe/$slug',
  path: '/recipe/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TipoIdRoute = TipoIdRouteImport.update({
  id: '/tipo/$id',
  path: '/tipo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lista': typeof ListaRoute
  '/viaje': typeof ViajeRoute
  '/destino/$id': typeof DestinoIdRoute
  '/pais/$slug': typeof PaisSlugRoute
  '/recipe/$slug': typeof RecipeSlugRoute
  '/tipo/$id': typeof TipoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lista': typeof ListaRoute
  '/viaje': typeof ViajeRoute
  '/destino/$id': typeof DestinoIdRoute
  '/pais/$slug': typeof PaisSlugRoute
  '/recipe/$slug': typeof RecipeSlugRoute
  '/tipo/$id': typeof TipoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lista': typeof ListaRoute
  '/viaje': typeof ViajeRoute
  '/destino/$id': typeof DestinoIdRoute
  '/pais/$slug': typeof PaisSlugRoute
  '/recipe/$slug': typeof RecipeSlugRoute
  '/tipo/$id': typeof TipoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lista'
    | '/viaje'
    | '/destino/$id'
    | '/pais/$slug'
    | '/recipe/$slug'
    | '/tipo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lista'
    | '/viaje'
    | '/destino/$id'
    | '/pais/$slug'
    | '/recipe/$slug'
    | '/tipo/$id'
  id:
    | '__root__'
    | '/'
    | '/lista'
    | '/viaje'
    | '/destino/$id'
    | '/pais/$slug'
    | '/recipe/$slug'
    | '/tipo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListaRoute: typeof ListaRoute
  ViajeRoute: typeof ViajeRoute
  DestinoIdRoute: typeof DestinoIdRoute
  PaisSlugRoute: typeof PaisSlugRoute
  RecipeSlugRoute: typeof RecipeSlugRoute
  TipoIdRoute: typeof TipoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista': {
      id: '/lista'
      path: '/lista'
      fullPath: '/lista'
      preLoaderRoute: typeof ListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viaje': {
      id: '/viaje'
      path: '/viaje'
      fullPath: '/viaje'
      preLoaderRoute: typeof ViajeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destino/$id': {
      id: '/destino/$id'
      path: '/destino/$id'
      fullPath: '/destino/$id'
      preLoaderRoute: typeof DestinoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pais/$slug': {
      id: '/pais/$slug'
      path: '/pais/$slug'
      fullPath: '/pais/$slug'
      preLoaderRoute: typeof PaisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$slug': {
      id: '/recipe/$slug'
      path: '/recipe/$slug'
      fullPath: '/recipe/$slug'
      preLoaderRoute: typeof RecipeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tipo/$id': {
      id: '/tipo/$id'
      path: '/tipo/$id'
      fullPath: '/tipo/$id'
      preLoaderRoute: typeof TipoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListaRoute: ListaRoute,
  ViajeRoute: ViajeRoute,
  DestinoIdRoute: DestinoIdRoute,
  PaisSlugRoute: PaisSlugRoute,
  RecipeSlugRoute: RecipeSlugRoute,
  TipoIdRoute: TipoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
